"""ReasonSummaryAgent
====================
AI-powered agent that transforms a persisted RecommendationResult
(including its output_payload_json and reasoning_details_json) into a
richly-structured explanation suitable for display in the workspace UI.

The headline, reasoning_summary, and top_drivers fields are generated by
the LLM (Azure OpenAI / OpenAI) for natural, context-aware explanations.
All structured tables (rules, conditions, alternatives, constraints) are
built deterministically from the stored payload for accuracy and speed.
If the LLM is unavailable the agent falls back gracefully to deterministic
text so the page always renders.

Usage
-----
    from apps.procurement.agents.reason_summary_agent import ReasonSummaryAgent
    ctx = ReasonSummaryAgent.generate(recommendation_result)

The returned dict has these top-level keys:

    headline          (str)  -- AI one-liner "why this system"
    system_name       (str)  -- short product name
    system_code       (str)  -- e.g. "FCU_CHILLED_WATER"
    system_description(str)  -- full product description
    reasoning_summary (str)  -- AI narrative paragraph
    confidence_pct    (int)  -- 0-100
    compliance_status (str)  -- PASS / FAIL / NOT_CHECKED
    capacity_guidance (str)
    human_validation  (bool)
    alternate_option  (str | None) -- alternate system name
    top_drivers       list[str]    -- AI-generated decision drivers
    rules_table       list[dict]   -- {code, description, role, role_class}
    conditions_table  list[dict]   -- {factor, value, derived, impact, highlight}
    alternatives_table list[dict]  -- {system, reason}
    constraints       dict         -- {landlord, environmental, operational, budget}
    assumptions       list[str]
    thought_steps     list[dict]   -- {step, stage, decision, reasoning}
    standards         list[str]
"""
from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Human-readable labels for input keys shown in the Conditions table
# ---------------------------------------------------------------------------
_FIELD_LABELS: Dict[str, str] = {
    "country":                     "Country",
    "city":                        "City",
    "store_type":                  "Store / Facility Type",
    "store_format":                "Store Format",
    "area_sqft":                   "Area (sqft)",
    "area_sqm_derived":            "Area (sqm, derived)",
    "ambient_temp_max":            "Max Ambient Temp (C)",
    "chilled_water_derived":       "Chilled Water Available",
    "outdoor_restriction_derived": "Outdoor Unit Restriction",
    "energy_efficiency_priority":  "Energy Efficiency Priority",
    "maintenance_priority":        "Maintenance Priority",
    "heat_load_category":          "Heat Load Category",
    "zone_count_derived":          "Zone Count (derived)",
    "estimated_cooling_tr":        "Estimated Cooling Load (TR)",
    "dust_exposure":               "Dust Exposure",
    "humidity_level":              "Humidity Level",
    "budget_level":                "Budget Level",
    "footfall_category":           "Footfall Category",
    "fresh_air_requirement":       "Fresh Air Requirement",
}

# Impact description per factor
_FIELD_IMPACT: Dict[str, str] = {
    "country":                     "Geography filter used by ruleset applicability",
    "city":                        "City-level filter used by ruleset applicability",
    "store_type":                  "Primary routing: determines which rule chain fires",
    "area_sqft":                   "Drives size-category classification (small/mid/large)",
    "area_sqm_derived":            "Internal sqm used by rule thresholds (2000 / 5000 sqm bands)",
    "ambient_temp_max":            "High ambient (>=45C) activates GCC desert-heat rules",
    "chilled_water_derived":       "CW='YES' routes MALL to FCU; 'NO' routes to VRF/Split",
    "outdoor_restriction_derived": "Forces FCU or cassette when ODU cannot be installed",
    "energy_efficiency_priority":  "'HIGH' upgrades PACKAGED -> VRF for lifecycle savings",
    "maintenance_priority":        "'HIGH' prefers single-point packaged units over VRF",
    "heat_load_category":          "Used as proxy for zone count (LOW=1, MEDIUM=2, HIGH=3+)",
    "zone_count_derived":          "Multi-zone (>=3) triggers VRF preference",
    "estimated_cooling_tr":        ">200 TR triggers chiller plant; 50-200 TR -> packaged DX",
    "dust_exposure":               "'HIGH' adds filtration constraints; does NOT change system",
    "humidity_level":              "'HIGH' adds anti-corrosion constraints",
    "budget_level":                "'LOW' prevents VRF/Chiller upgrade even if efficiency flags",
    "footfall_category":           "High footfall adds capacity margin advice",
    "fresh_air_requirement":       "'YES' or 'HIGH' triggers ERV/HRV integration constraint",
}

# Whether a field value DIRECTLY changed the system selection
_SYSTEM_DECIDING_FIELDS = {
    "store_type", "area_sqft", "area_sqm_derived", "ambient_temp_max",
    "chilled_water_derived", "outdoor_restriction_derived",
    "zone_count_derived", "estimated_cooling_tr", "budget_level",
    "energy_efficiency_priority", "maintenance_priority", "heat_load_category",
}

# Rule roles
_MODIFIER_PREFIXES = (
    "RULE_04", "RULE_05", "RULE_07", "RULE_08", "RULE_09",
    "RULE_01_OUTDOOR", "RULE_BUDGET_LOW",
)
_RULE_DESCRIPTIONS: Dict[str, str] = {
    "RULE_TECH_ISOLATED_SPLIT":              "Small technical room or isolated intervention (<300 sqft)",
    "RULE_U1_SMALL_AREA_SPLIT_AC":          "Store area below 2,000 sqm -- split AC most practical",
    "RULE_U2_MID_AREA_LOW_BUDGET_PKG":      "Mid-size area with LOW budget -- packaged DX most cost-effective",
    "RULE_S_MEDLARGE_HIAMB_EFF_VRF":        "Medium-large standalone: high ambient + HIGH efficiency -> VRF",
    "RULE_S_MEDLARGE_MAINT_PACKAGED":       "Medium-large standalone: HIGH maintenance posture -> packaged DX",
    "RULE_U3_STANDALONE_MEDLARGE_HIAMB_PACKAGED": "Standalone medium-large, high ambient, low zone count",
    "RULE_S2_LARGE_STANDALONE_HIEFF_VRF":   "Large standalone (>=5,000 sqm) with high efficiency priority",
    "RULE_M1_MALL_FCU_CW":                  "Mall store with confirmed chilled water backbone -> FCU",
    "RULE_M1b_OUTDOOR_RESTRICTION_FORCES_FCU": "Outdoor unit restriction forces FCU on chilled water",
    "RULE_M2_MALL_NO_CW_VRF":              "Mall store without chilled water -- multi-zone VRF",
    "RULE_M3_MALL_NO_CW_SPLIT":             "Mall store without chilled water -- single/low zone -> split",
    "RULE_M3_MALL_NO_CW_SPLIT_RESTRICTED":  "Mall store with outdoor restriction and no chilled water",
    "RULE_S1_STANDALONE_HIGH_AMB_VRF":      "Standalone extreme ambient (>=46C) and multi-zone -> VRF",
    "RULE_S1b_STANDALONE_HIGH_AMB_VRF":     "Standalone high ambient, multi-zone VRF required",
    "RULE_S2_STANDALONE_MEDIUM_VRF":        "Standalone moderate load with VRF for high ambient performance",
    "RULE_S3_STANDALONE_SMALL_SPLIT":       "Small standalone store, single zone -- split systems optimal",
    "RULE_S3b_SEGMENTED_ZONES_EFFICIENCY_VRF": "Segmented zones + strong efficiency -> VRF heat recovery",
    "RULE_S4_STANDALONE_MULTI_VRF":         "Multiple independent zones requiring individual control",
    "RULE_S5_STANDALONE_2ZONE_VRF":         "2-zone standalone with medium/high budget",
    "RULE_S6_STANDALONE_1ZONE_SPLIT":       "Single-zone standalone -- split most practical",
    "RULE_W1_WAREHOUSE_CHILLER":            "Warehouse major cooling load (>200 TR) -> chiller plant",
    "RULE_W2_WAREHOUSE_PACKAGED":           "Warehouse medium load (50-200 TR) -> packaged DX",
    "RULE_W3_WAREHOUSE_SMALL_SPLIT":        "Small warehouse limited cooling scope -> split",
    "RULE_DC_CHILLER":                      "Data centre -- precision cooling with N+1 redundancy",
    "RULE_R1_RESTAURANT_FCU":               "Restaurant/F&B with chilled water available",
    "RULE_R2_RESTAURANT_CASSETTE":          "Restaurant/F&B without chilled water",
    "RULE_01_OUTDOOR_RESTRICTION":          "Outdoor unit restriction by landlord or authority",
    "RULE_04_HIGH_DUST":                    "High dust environment -- enhanced G4+F7 filtration mandatory",
    "RULE_05_HIGH_HUMIDITY":                "High humidity -- anti-corrosion coil treatment required",
    "RULE_05b_COASTAL_ANTI_CORROSION":      "GCC coastal location -- salt-air protection required",
    "RULE_07_EFFICIENCY":                   "Efficiency priority -- minimum SEER/IPLV thresholds apply",
    "RULE_08_FRESH_AIR_ERV":                "Fresh air requirement -- ERV/HRU integration required",
    "RULE_09_HIGH_FOOTFALL":                "High footfall -- capacity margin and low-noise preferred",
    "RULE_BUDGET_LOW_ADJUSTMENT":           "LOW budget -- upfront cost of preferred system flagged",
    "RULE_BUDGET_LOW_COMPLIANCE_RISK":      "LOW budget -- minimum compliant option must still be met",
}

# System display names
_SYSTEM_NAMES: Dict[str, str] = {
    "FCU_CHILLED_WATER":  "Fan Coil Unit on Chilled Water (FCU-CW)",
    "VRF_SYSTEM":         "Variable Refrigerant Flow System (VRF/VRV)",
    "PACKAGED_DX_UNIT":   "Packaged Rooftop DX Unit",
    "SPLIT_SYSTEM":       "Split Air Conditioning System",
    "CASSETTE_SPLIT":     "Ceiling Cassette Split System",
    "CHILLER_PLANT":      "Chiller Plant (Air/Water Cooled)",
    "AHU_DUCTED":         "Air Handling Unit (AHU) - Ducted",
    "ERV":                "Energy Recovery Ventilation Unit (ERV/HRU)",
}

# Highlight class per field value
def _highlight(field: str, value: Any) -> str:
    """Return Bootstrap CSS class for the value cell."""
    v = str(value).upper()
    if field == "chilled_water_derived":
        return "text-success fw-semibold" if v == "YES" else "text-muted"
    if field == "outdoor_restriction_derived":
        return "text-warning fw-semibold" if v == "YES" else "text-muted"
    if field == "ambient_temp_max":
        try:
            if float(value) >= 46:
                return "text-danger fw-semibold"
        except (TypeError, ValueError):
            pass
    if field == "budget_level":
        return "text-danger fw-semibold" if v == "LOW" else (
            "text-warning fw-semibold" if v == "MEDIUM" else "text-success fw-semibold"
        )
    if field == "energy_efficiency_priority":
        return "text-success fw-semibold" if v == "HIGH" else "text-muted"
    if field == "maintenance_priority":
        return "text-warning fw-semibold" if v == "HIGH" else "text-muted"
    if field in _SYSTEM_DECIDING_FIELDS:
        return "text-dark"
    return "text-muted"


class ReasonSummaryAgent:
    """AI-powered agent that explains why a recommendation was made.

    Uses the LLM to generate the headline, reasoning_summary, and top_drivers
    as natural-language narrative from the structured rule output.
    All structured tables are built deterministically for accuracy.
    Falls back to deterministic text if the LLM is unavailable.
    """

    _AI_SYSTEM_PROMPT = (
        "You are an expert HVAC procurement advisor. "
        "You receive structured data about an HVAC system recommendation that was produced "
        "by a deterministic rules engine for a retail or commercial facility in the GCC region. "
        "Your task is to write a clear, professional, procurement-facing explanation of WHY "
        "this specific system was selected.\n\n"
        "Return ONLY valid JSON with exactly these three keys:\n"
        "{\n"
        '  "headline": "One concise sentence (max 25 words) explaining the primary reason this system was selected.",\n'
        '  "reasoning_summary": "Two to four sentences of natural language explaining the recommendation in plain English, '
        'covering the site conditions, key constraints, and how they led to this choice.",\n'
        '  "top_drivers": ["Short phrase 1", "Short phrase 2", "Short phrase 3"]\n'
        "}\n"
        "No markdown. No extra keys. No code fences. All values must be plain ASCII text."
    )

    @staticmethod
    def _generate_ai_summary(
        system_name: str,
        system_code: str,
        rules_fired: List[str],
        conditions_table: List[Dict[str, Any]],
        constraints: Dict[str, Any],
        standards: List[str],
        fallback_headline: str,
        fallback_summary: str,
        fallback_drivers: List[str],
    ) -> Dict[str, str]:
        """Call the LLM to generate headline, reasoning_summary, and top_drivers.

        Returns a dict with keys: headline, reasoning_summary, top_drivers.
        Falls back to deterministic values on any error.
        """
        try:
            from apps.agents.services.llm_client import LLMClient, LLMMessage

            # Build a compact context payload to send to the LLM
            conditions_brief = [
                {"factor": c["factor"], "value": str(c["value"]), "is_key": c.get("is_key", False)}
                for c in conditions_table
            ]
            rules_brief = [
                _RULE_DESCRIPTIONS.get(r, r.replace("_", " ").title())
                for r in rules_fired[:6]  # limit to 6 most relevant rules
            ]
            all_constraints = []
            for group_items in constraints.values():
                if isinstance(group_items, list):
                    all_constraints.extend(group_items)

            context_payload = {
                "recommended_system": system_name,
                "system_code": system_code,
                "rules_fired": rules_brief,
                "key_conditions": [c for c in conditions_brief if c["is_key"]],
                "all_conditions": conditions_brief,
                "constraints": all_constraints[:6],
                "applicable_standards": standards[:4],
            }

            llm = LLMClient()
            response = llm.chat(
                messages=[
                    LLMMessage(role="system", content=ReasonSummaryAgent._AI_SYSTEM_PROMPT),
                    LLMMessage(
                        role="user",
                        content=(
                            "Generate the reasoning explanation for this HVAC recommendation:\n\n"
                            + json.dumps(context_payload, default=str)
                        ),
                    ),
                ],
            )

            text = (response.content or "").strip()
            # Strip markdown code fences if present
            fence_match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
            if fence_match:
                text = fence_match.group(1).strip()
            # Extract JSON object if surrounded by other text
            if not text.startswith("{"):
                obj_match = re.search(r"\{.*\}", text, re.DOTALL)
                if obj_match:
                    text = obj_match.group(0)

            parsed = json.loads(text)
            ai_headline = str(parsed.get("headline") or "").strip()
            ai_summary = str(parsed.get("reasoning_summary") or "").strip()
            ai_drivers = parsed.get("top_drivers") or []
            if isinstance(ai_drivers, list):
                ai_drivers = [str(d).strip() for d in ai_drivers if d]

            return {
                "headline":          ai_headline or fallback_headline,
                "reasoning_summary": ai_summary or fallback_summary,
                "top_drivers":       ai_drivers or fallback_drivers,
                "ai_generated":      True,
            }

        except Exception as exc:
            logger.warning("ReasonSummaryAgent._generate_ai_summary failed: %s", exc)
            return {
                "headline":          fallback_headline,
                "reasoning_summary": fallback_summary,
                "top_drivers":       fallback_drivers,
                "ai_generated":      False,
            }

    @staticmethod
    def generate(result) -> Dict[str, Any]:
        """Generate a structured explanation dict from a RecommendationResult.

        The headline, reasoning_summary, and top_drivers are produced by the LLM.
        All structured tables are built deterministically.

        Parameters
        ----------
        result : RecommendationResult ORM object

        Returns
        -------
        dict  -- keys described in module docstring
        """
        try:
            payload: Dict[str, Any] = result.output_payload_json or {}
            details: Dict[str, Any] = result.reasoning_details_json or {}

            # If reasoning_details_json is empty, fall back to nested key in payload
            if not details:
                details = payload.get("reasoning_details", {})
            else:
                # reasoning_details_json may itself BE the inner reasoning_details dict
                if "source" not in details and "rules_fired" not in details:
                    details = payload.get("reasoning_details", {})

            inputs: Dict[str, Any] = details.get("inputs", {})
            # Backfill geo keys for old records whose stored inputs did not
            # include country/city, so factor rows stay aligned to ruleset.
            try:
                if not inputs.get("country"):
                    _req = getattr(getattr(result, "run", None), "request", None)
                    if _req is not None and getattr(_req, "geography_country", None):
                        inputs["country"] = str(_req.geography_country).strip().upper()
                if not inputs.get("city"):
                    _req = getattr(getattr(result, "run", None), "request", None)
                    if _req is not None and getattr(_req, "geography_city", None):
                        inputs["city"] = str(_req.geography_city).strip().upper()
            except Exception:
                pass
            rules_fired: List[str] = details.get("rules_fired", [])
            system_info: Dict[str, Any] = details.get("system_type", {})
            applicable_standards: List[str] = details.get("applicable_standards", [])

            # -- DB rule match: extract rule code/name/priority from reasoning_details.
            # The stored structure uses "rule_matched" for the code and has a nested
            # "db_rule" object; fall back to simpler keys for forward compatibility.
            _db_rule_obj: Dict[str, Any] = details.get("db_rule", {}) or {}
            db_rule_code: str = (
                details.get("rule_matched", "")
                or _db_rule_obj.get("rule_code", "")
                or details.get("rule_code", "")
            )
            db_rule_name: str = (
                _db_rule_obj.get("rule_name", "")
                or details.get("rule_name", "")
            )
            db_rule_priority: int = int(
                details.get("rule_priority", 0)
                or _db_rule_obj.get("priority", 0)
                or 0
            )

            system_code: str = payload.get("system_type_code", "") or ""
            system_name: str = (
                system_info.get("name", "")
                or _SYSTEM_NAMES.get(system_code, system_code)
            )
            system_description: str = system_info.get("description", "")

            # Extract clean product name from recommended_option (strip the long description)
            raw_rec_option: str = result.recommended_option or payload.get("recommended_option", "")
            if " -- " in raw_rec_option:
                system_display = raw_rec_option.split(" -- ")[0].strip()
            elif " - " in raw_rec_option:
                system_display = raw_rec_option.split(" - ")[0].strip()
            elif " (" in raw_rec_option and system_code:
                system_display = system_name or raw_rec_option
            else:
                system_display = system_name or raw_rec_option

            # Stored reasoning_summary from the rules engine (used as fallback)
            stored_reasoning_summary: str = result.reasoning_summary or payload.get("reasoning_summary", "")
            confidence: float = float(result.confidence_score or payload.get("confidence", 0.0))
            confidence_pct: int = round(confidence * 100)

            stored_top_drivers: List[str] = (
                payload.get("top_decision_drivers", [])
                or payload.get("decision_drivers", [])
            )
            alternate_raw: Optional[str] = payload.get("alternate_option")
            cap_guidance: str = payload.get("indicative_capacity_guidance", "")
            human_validation: bool = bool(payload.get("required_human_validation", False))

            # -- Rules table (deterministic) ------------------------------------
            # For DB-driven rules (rule_engine=HVAC_RULES_DB), there is no
            # rules_fired list -- build a single-entry table from rule_code.
            if not rules_fired and db_rule_code:
                rules_table = [{
                    "code":        db_rule_code,
                    "description": db_rule_name or f"DB rule {db_rule_code}",
                    "role":        "Primary Selection",
                    "role_class":  "text-success fw-semibold",
                    "badge_class": "bg-success",
                }]
            else:
                rules_table = ReasonSummaryAgent._build_rules_table(rules_fired)

            # -- Conditions table (deterministic) --------------------------------
            # Resolve which input keys the matched rule actually tested so we
            # display only those rows (not all 13 captured inputs).
            # Priority:
            #   1. matched_condition_keys  -- written by rules_engine (new data)
            #   2. matched_conditions dict -- written by old seed commands
            #   3. Live DB rule lookup     -- works for any old record whose
            #                                reasoning_details has rule_matched/
            #                                rule_code stored
            #   4. None                   -- show all (genuine legacy fallback)
            _matched_keys: Optional[set] = None

            _explicit_keys = details.get("matched_condition_keys") or []
            if _explicit_keys:
                # New data: list written directly by rules_engine.py
                _matched_keys = set(_explicit_keys)
            else:
                # Old seed data: 'matched_conditions' is a dict of key->value
                _legacy_cond = details.get("matched_conditions")
                if isinstance(_legacy_cond, dict) and _legacy_cond:
                    _matched_keys = set(_legacy_cond.keys())
                else:
                    # Any other old data: derive from the live DB rule record
                    _matched_keys = ReasonSummaryAgent._matched_keys_from_db_rule(
                        db_rule_code, inputs
                    )

            # -- Rule conditions: ALL parameters with their configured filter
            # value (or "Any").  New: stored by rules_engine in rule_conditions.
            # Fallback: derive from the live DB rule record.
            _rule_conditions: Optional[Dict[str, str]] = None
            _stored_rc = details.get("rule_conditions")
            if isinstance(_stored_rc, dict) and _stored_rc:
                _rule_conditions = _stored_rc
            elif db_rule_code:
                _rule_conditions = ReasonSummaryAgent._rule_conditions_from_db_rule(
                    db_rule_code, inputs
                )

            conditions_table = ReasonSummaryAgent._build_conditions_table(
                inputs,
                matched_keys=_matched_keys,
                rule_conditions=_rule_conditions,
            )
            # -- Alternatives table (deterministic) ------------------------------
            alternatives_table = ReasonSummaryAgent._build_alternatives_table(
                system_code, alternate_raw, payload, inputs
            )

            # -- Constraints & assumptions (deterministic) -----------------------
            raw_c_and_a = payload.get("constraints_and_assumptions", {})
            if isinstance(raw_c_and_a, dict):
                constraints = {
                    "landlord":      raw_c_and_a.get("landlord", []),
                    "environmental": raw_c_and_a.get("environmental", []),
                    "operational":   raw_c_and_a.get("operational", []),
                    "budget":        raw_c_and_a.get("budget", []),
                }
                assumptions = raw_c_and_a.get("assumptions", [])
            else:
                raw_constraints = payload.get("constraints", [])
                flat = [
                    c["detail"] if isinstance(c, dict) else str(c)
                    for c in (raw_constraints or [])
                ]
                constraints = {"landlord": [], "environmental": flat, "operational": [], "budget": []}
                assumptions = []

            # -- Fallback headline (deterministic) --------------------------------
            fallback_headline = ReasonSummaryAgent._build_headline(
                system_code, system_display, inputs, rules_fired, payload
            )

            # -- AI-generated headline, reasoning_summary, and top_drivers -------
            ai_result = ReasonSummaryAgent._generate_ai_summary(
                system_name=system_display,
                system_code=system_code,
                rules_fired=rules_fired,
                conditions_table=conditions_table,
                constraints=constraints,
                standards=applicable_standards,
                fallback_headline=fallback_headline,
                fallback_summary=stored_reasoning_summary,
                fallback_drivers=stored_top_drivers,
            )

            # -- Thought steps from run.thought_process_log ----------------------
            thought_steps = []
            try:
                run = result.run
                log = getattr(run, "thought_process_log", None) or []
                for step in log:
                    if isinstance(step, dict):
                        thought_steps.append({
                            "step":      step.get("step", ""),
                            "stage":     step.get("stage", ""),
                            "decision":  step.get("decision", ""),
                            "reasoning": step.get("reasoning", ""),
                        })
            except Exception:
                pass

            return {
                "headline":           ai_result["headline"],
                "system_name":        system_display,
                "system_code":        system_code,
                "system_description": system_description or raw_rec_option,
                "reasoning_summary":  ai_result["reasoning_summary"],
                "confidence_pct":     confidence_pct,
                "compliance_status":  result.compliance_status or "NOT_CHECKED",
                "capacity_guidance":  cap_guidance,
                "human_validation":   human_validation,
                "alternate_option":   alternate_raw,
                "top_drivers":        ai_result["top_drivers"],
                "rules_table":        rules_table,
                "conditions_table":   conditions_table,
                "alternatives_table": alternatives_table,
                "constraints":        constraints,
                "assumptions":        assumptions,
                "thought_steps":      thought_steps,
                "standards":          applicable_standards,
                "ai_generated":       ai_result.get("ai_generated", False),
                # DB-rule fields (populated only for HVAC_RULES_DB engine matches)
                "rule_code":          db_rule_code,
                "rule_name":          db_rule_name,
                "rule_priority":      db_rule_priority,
                # True when matched a DB rule; False when fell through to AI/heuristic fallback
                "from_db_rule":       bool(db_rule_code),
            }

        except Exception as exc:
            logger.warning("ReasonSummaryAgent.generate failed: %s", exc, exc_info=True)
            return {
                "headline":           "Reasoning summary unavailable.",
                "system_name":        getattr(result, "recommended_option", "")[:60],
                "system_code":        "",
                "system_description": "",
                "reasoning_summary":  getattr(result, "reasoning_summary", ""),
                "confidence_pct":     round(float(getattr(result, "confidence_score", 0.0) or 0) * 100),
                "compliance_status":  getattr(result, "compliance_status", "NOT_CHECKED"),
                "capacity_guidance":  "",
                "human_validation":   False,
                "alternate_option":   None,
                "top_drivers":        [],
                "rules_table":        [],
                "conditions_table":   [],
                "alternatives_table": [],
                "constraints":        {},
                "assumptions":        [],
                "thought_steps":      [],
                "standards":          [],
                "ai_generated":       False,
            }

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_headline(
        system_code: str,
        system_display: str,
        inputs: Dict[str, Any],
        rules_fired: List[str],
        payload: Dict[str, Any],
    ) -> str:
        store_type = str(inputs.get("store_type") or "").title()
        area_sqm = inputs.get("area_sqm_derived", 0) or 0
        area_sqft = inputs.get("area_sqft") or 0
        ambient = inputs.get("ambient_temp_max")
        cw = str(inputs.get("chilled_water_derived") or "NO").upper()

        # Build context clause
        clauses = []
        if store_type:
            clauses.append(store_type.replace("_", " ").title() + " facility")
        if area_sqm:
            clauses.append(f"{area_sqm:,.0f} sqm floor area")
        if ambient:
            clauses.append(f"max ambient {ambient}C")
        if cw == "YES":
            clauses.append("chilled water infrastructure available")

        context_str = (", ".join(clauses) + " -- ") if clauses else ""

        # Primary rule
        primary_rules = [
            r for r in rules_fired
            if not any(r.startswith(p) for p in _MODIFIER_PREFIXES)
        ]
        rule_desc = ""
        if primary_rules:
            rule_desc = _RULE_DESCRIPTIONS.get(primary_rules[0], primary_rules[0].replace("_", " ").title())

        if rule_desc:
            return f"{context_str}{system_display} selected: {rule_desc.lower()}."
        elif system_display:
            return f"{context_str}{system_display} selected based on deterministic rule matching."
        return "Recommendation generated by the HVAC rules engine."

    @staticmethod
    def _build_rules_table(rules_fired: List[str]) -> List[Dict[str, str]]:
        rows = []
        for code in rules_fired:
            is_modifier = any(code.startswith(p) for p in _MODIFIER_PREFIXES)
            rows.append({
                "code":        code,
                "description": _RULE_DESCRIPTIONS.get(code, code.replace("_", " ").title()),
                "role":        "Modifier / Constraint" if is_modifier else "Primary Selection",
                "role_class":  "text-muted" if is_modifier else "text-success fw-semibold",
                "badge_class": "bg-secondary" if is_modifier else "bg-success",
            })
        return rows

    @staticmethod
    def _matched_keys_from_db_rule(
        rule_code: str,
        inputs: Dict[str, Any],
    ) -> Optional[set]:
        """Derive matched input keys from the DB rule record.

        Looks up HVACRecommendationRule by rule_code and returns the set of
        input-dict keys that rule actually tested via its configured condition
        fields.  Returns None if the rule cannot be found (caller falls back
        to showing all inputs).

        Also handles derived keys (outdoor_restriction, chilled_water) that
        are computed from landlord text: if the stored input shows YES we
        count them as matched.
        """
        if not rule_code:
            return None
        try:
            from apps.procurement.models import HVACRecommendationRule
            rule = (
                HVACRecommendationRule.objects
                .filter(rule_code=rule_code)
                .first()
            )
            if rule is None:
                return None
            keys: set = set()
            if rule.country_filter:
                keys.add("country")
            if rule.city_filter:
                keys.add("city")
            if rule.store_type_filter:
                keys.add("store_type")
            if rule.area_sq_ft_min is not None or rule.area_sq_ft_max is not None:
                keys.add("area_sqft")
                keys.add("area_sqm_derived")
            if rule.ambient_temp_min_c is not None:
                keys.add("ambient_temp_max")
            if rule.budget_level_filter:
                keys.add("budget_level")
            if rule.energy_priority_filter:
                keys.add("energy_efficiency_priority")
            # Include derived flags only when the stored value says YES
            if str(inputs.get("outdoor_restriction_derived", "")).upper() == "YES":
                keys.add("outdoor_restriction_derived")
            if str(inputs.get("chilled_water_derived", "")).upper() == "YES":
                keys.add("chilled_water_derived")
            return keys if keys else None
        except Exception:
            return None

    @staticmethod
    def _rule_conditions_from_db_rule(
        rule_code: str,
        inputs: Dict[str, Any],
    ) -> Optional[Dict[str, str]]:
        """Build a full rule_conditions dict from a live DB rule record.

        Returns a dict mapping every standard parameter key to its configured
        filter value, or "Any" when no filter is set.  Used for old records
        that were saved before rule_conditions was stored in reasoning_details.
        Returns None if the rule cannot be found.
        """
        if not rule_code:
            return None
        try:
            from apps.procurement.models import HVACRecommendationRule
            rule = (
                HVACRecommendationRule.objects
                .filter(rule_code=rule_code)
                .first()
            )
            if rule is None:
                return None

            # Area filter label helper
            lo = rule.area_sq_ft_min
            hi = rule.area_sq_ft_max
            if lo is not None and hi is not None:
                area_label = f"{lo:,.0f} - {hi:,.0f} sqft"
            elif lo is not None:
                area_label = f">= {lo:,.0f} sqft"
            elif hi is not None:
                area_label = f"<= {hi:,.0f} sqft"
            else:
                area_label = "Any"

            outdoor_r = str(inputs.get("outdoor_restriction_derived", "NO")).upper() == "YES"
            cw_avail = str(inputs.get("chilled_water_derived", "NO")).upper() == "YES"

            return {
                "country":                    rule.country_filter or "Any",
                "city":                       rule.city_filter or "Any",
                "store_type":                 rule.store_type_filter or "Any",
                "area_sqft":                  area_label,
                "ambient_temp_max": (
                    f">= {rule.ambient_temp_min_c}C"
                    if rule.ambient_temp_min_c is not None
                    else "Any"
                ),
                "budget_level":               rule.budget_level_filter or "Any",
                "energy_efficiency_priority": rule.energy_priority_filter or "Any",
                "outdoor_restriction_derived": "YES (required)" if outdoor_r else "Any",
                "chilled_water_derived":       "YES (required)" if cw_avail else "Any",
            }
        except Exception:
            return None

    @staticmethod
    def _build_conditions_table(
        inputs: Dict[str, Any],
        matched_keys: Optional[set] = None,
        rule_conditions: Optional[Dict[str, str]] = None,
    ) -> List[Dict[str, Any]]:
        """Build the Matched Input Conditions table rows.

        Parameters
        ----------
        inputs : dict
            All engine inputs (may contain derived fields too).
        matched_keys : set | None
            Legacy: keys the rule explicitly filtered on (used when
            rule_conditions is not available).
        rule_conditions : dict | None
            Preferred: full map of {input_key -> configured_filter_value | "Any"}
            for ALL standard parameters the rule can evaluate.  When provided,
            ALL parameters are shown so the user can see every condition the
            rule checked, not just the ones with active filters.
        """
        rows = []
        DISPLAY_ORDER = [
            "country", "city",
            "store_type", "store_format", "area_sqft", "area_sqm_derived",
            "ambient_temp_max", "heat_load_category", "zone_count_derived",
            "estimated_cooling_tr", "chilled_water_derived",
            "outdoor_restriction_derived", "budget_level",
            "energy_efficiency_priority", "maintenance_priority",
            "dust_exposure", "humidity_level", "footfall_category",
            "fresh_air_requirement",
        ]
        seen = set()

        # ----------------------------------------------------------------
        # Mode A: rule_conditions provided -- show ALL configured params
        #         regardless of whether the filter is "Any" or specific.
        # ----------------------------------------------------------------
        if rule_conditions:
            for key in DISPLAY_ORDER:
                if key not in rule_conditions:
                    # Not a parameter this rule evaluates -- include only if
                    # there is an actual input value and no filter at all.
                    val = inputs.get(key)
                    if val is None:
                        continue
                    seen.add(key)
                    derived = key.endswith("_derived") or key in (
                        "area_sqm_derived", "zone_count_derived", "estimated_cooling_tr",
                        "chilled_water_derived", "outdoor_restriction_derived"
                    )
                    rows.append({
                        "factor":      _FIELD_LABELS.get(key, key.replace("_", " ").title()),
                        "value":       val,
                        "rule_filter": "N/A",
                        "derived":     derived,
                        "impact":      _FIELD_IMPACT.get(key, "Informational"),
                        "highlight":   _highlight(key, val),
                        "is_key":      key in _SYSTEM_DECIDING_FIELDS,
                        "is_any":      False,
                    })
                    continue

                filter_val = rule_conditions[key]
                is_any = (filter_val == "Any" or not filter_val)
                # Input value -- show "Not provided" when absent
                val = inputs.get(key)
                display_val = val if val is not None else "Not provided"
                seen.add(key)
                derived = key.endswith("_derived") or key in (
                    "area_sqm_derived", "zone_count_derived", "estimated_cooling_tr",
                    "chilled_water_derived", "outdoor_restriction_derived"
                )
                # When "Any": override impact to explain wildcard
                impact = (
                    "No restriction -- rule accepts any value (wildcard)"
                    if is_any
                    else _FIELD_IMPACT.get(key, "Informational")
                )
                # When "Any": reduce highlight to muted; otherwise use normal
                highlight = "text-muted fst-italic" if is_any else _highlight(key, val if val is not None else "")
                # "Key" only when filter is specific (not Any) and field is deciding
                is_key = (not is_any) and (key in _SYSTEM_DECIDING_FIELDS)
                rows.append({
                    "factor":      _FIELD_LABELS.get(key, key.replace("_", " ").title()),
                    "value":       display_val,
                    "rule_filter": filter_val,
                    "derived":     derived,
                    "impact":      impact,
                    "highlight":   highlight,
                    "is_key":      is_key,
                    "is_any":      is_any,
                })

            # Any remaining actual inputs not in the rule_conditions map
            for key, val in inputs.items():
                if key in seen or val is None:
                    continue
                rows.append({
                    "factor":      _FIELD_LABELS.get(key, key.replace("_", " ").title()),
                    "value":       val,
                    "rule_filter": "N/A",
                    "derived":     False,
                    "impact":      _FIELD_IMPACT.get(key, "Informational"),
                    "highlight":   _highlight(key, val),
                    "is_key":      key in _SYSTEM_DECIDING_FIELDS,
                    "is_any":      False,
                })
            return rows

        # ----------------------------------------------------------------
        # Mode B: legacy -- use matched_keys filter (or show all)
        # ----------------------------------------------------------------
        for key in DISPLAY_ORDER:
            # Skip keys not in the rule's matched conditions (when provided)
            if matched_keys and key not in matched_keys:
                continue
            val = inputs.get(key)
            if val is None:
                continue
            seen.add(key)
            derived = key.endswith("_derived") or key in (
                "area_sqm_derived", "zone_count_derived", "estimated_cooling_tr",
                "chilled_water_derived", "outdoor_restriction_derived"
            )
            rows.append({
                "factor":      _FIELD_LABELS.get(key, key.replace("_", " ").title()),
                "value":       val,
                "rule_filter": None,
                "derived":     derived,
                "impact":      _FIELD_IMPACT.get(key, "Informational"),
                "highlight":   _highlight(key, val),
                "is_key":      key in _SYSTEM_DECIDING_FIELDS,
                "is_any":      False,
            })
        # Remaining keys not in display order (only when no filter is applied)
        if not matched_keys:
            for key, val in inputs.items():
                if key in seen or val is None:
                    continue
                rows.append({
                    "factor":      _FIELD_LABELS.get(key, key.replace("_", " ").title()),
                    "value":       val,
                    "rule_filter": None,
                    "derived":     False,
                    "impact":      _FIELD_IMPACT.get(key, "Informational"),
                    "highlight":   _highlight(key, val),
                    "is_key":      key in _SYSTEM_DECIDING_FIELDS,
                    "is_any":      False,
                })
        return rows

    @staticmethod
    def _build_alternatives_table(
        selected_code: str,
        alternate_raw: Optional[str],
        payload: Dict[str, Any],
        inputs: Dict[str, Any],
    ) -> List[Dict[str, str]]:
        rows = []
        # Add the alternate from the engine
        if alternate_raw:
            alt_name = alternate_raw.split(" -- ")[0].strip() if " -- " in alternate_raw else alternate_raw
            rows.append({
                "system":         alt_name,
                "reason_rejected": (
                    alternate_raw.split(" -- ", 1)[1].strip()
                    if " -- " in alternate_raw
                    else "Not optimal for the given parameters."
                ),
                "reason_class":   "text-muted",
            })

        # Budget-based exclusions
        budget = str(inputs.get("budget_level") or "").upper()
        if budget == "LOW" and selected_code in ("PACKAGED_DX_UNIT", "SPLIT_SYSTEM"):
            for excluded in ("VRF_SYSTEM", "CHILLER_PLANT", "FCU_CHILLED_WATER"):
                if excluded != selected_code and excluded not in [r["system"] for r in rows]:
                    rows.append({
                        "system":          _SYSTEM_NAMES.get(excluded, excluded),
                        "reason_rejected": "Excluded: LOW budget level cannot support higher CAPEX system.",
                        "reason_class":    "text-warning",
                    })
                    break

        # CW-based exclusion
        cw = str(inputs.get("chilled_water_derived") or "NO").upper()
        if cw == "NO" and "FCU_CHILLED_WATER" != selected_code:
            rows.append({
                "system":          _SYSTEM_NAMES.get("FCU_CHILLED_WATER", "FCU Chilled Water"),
                "reason_rejected": "Not viable: chilled water infrastructure not confirmed in landlord constraints.",
                "reason_class":    "text-danger",
            })

        return rows
