# Generated by Django 5.2.1 on 2026-03-12 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Uppercase machine name, e.g. ADMIN, AP_PROCESSOR', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable role label', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system_role', models.BooleanField(db_index=True, default=False, help_text='System roles cannot be deleted or have their code changed')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rank', models.PositiveIntegerField(default=100, help_text='Lower rank = higher authority. Used for display ordering.')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'accounts_role',
                'ordering': ['rank', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, default='', help_text='Bootstrap icon class, e.g. bi-speedometer2', max_length=100)),
                ('url_name', models.CharField(blank=True, default='', help_text='Django URL name to reverse, e.g. dashboard:index', max_length=200)),
                ('required_permission', models.CharField(blank=True, default='', help_text='Permission code required to see this menu item. Empty = visible to all.', max_length=100)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_separator', models.BooleanField(default=False, help_text='If true, renders as a visual separator line')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.menuconfig')),
            ],
            options={
                'verbose_name': 'Menu Config',
                'verbose_name_plural': 'Menu Configs',
                'db_table': 'accounts_menu_config',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Permission code, e.g. invoices.view, reconciliation.run', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission label', max_length=200)),
                ('module', models.CharField(db_index=True, help_text='Grouping module: invoices, reconciliation, cases, etc.', max_length=50)),
                ('action', models.CharField(help_text='Action within module: view, create, edit, delete, etc.', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'accounts_permission',
                'ordering': ['module', 'action'],
                'indexes': [models.Index(fields=['module', 'action'], name='idx_perm_module_action')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_allowed', models.BooleanField(default=True, help_text='True = role grants this permission')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'accounts_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('override_type', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = never expires', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_assigned', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='accounts.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission Override',
                'verbose_name_plural': 'User Permission Overrides',
                'db_table': 'accounts_user_permission_override',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_userpermovr_user_active')],
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Primary role is synced to the legacy User.role field')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = never expires', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'accounts_user_role',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_userrole_user_active'), models.Index(fields=['role', 'is_active'], name='idx_userrole_role_active')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
