# Generated by Django 5.0.14 on 2026-04-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userrole_scope_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Primary display name', max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', help_text='Registered legal name (for exact matching)', max_length=255)),
                ('tax_id', models.CharField(blank=True, default='', help_text='Primary GSTIN / VAT / TIN of the company', max_length=50)),
                ('country', models.CharField(blank=True, default='', help_text='ISO country code (IN, AE, US, ...)', max_length=10)),
                ('state_code', models.CharField(blank=True, default='', help_text='State code (for India GST)', max_length=10)),
                ('address', models.TextField(blank=True, default='')),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('website', models.URLField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text='Mark as the primary company profile for extraction')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'accounts_company_profile',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_name', models.CharField(max_length=255)),
                ('normalized_alias', models.CharField(blank=True, db_index=True, help_text='Auto-generated lowercase stripped version for matching', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Alias',
                'verbose_name_plural': 'Company Aliases',
                'db_table': 'accounts_company_alias',
                'ordering': ['company', 'alias_name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The organisation this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.companyprofile'),
        ),
        migrations.CreateModel(
            name='CompanyTaxID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_id', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(blank=True, default='', help_text="Optional label, e.g. 'Maharashtra GSTIN', 'Karnataka GSTIN'", max_length=100)),
                ('state_code', models.CharField(blank=True, default='', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_ids', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Tax ID',
                'verbose_name_plural': 'Company Tax IDs',
                'db_table': 'accounts_company_tax_id',
                'ordering': ['company', 'tax_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='companyalias',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_alias'), name='uq_company_alias_norm'),
        ),
        migrations.AddConstraint(
            model_name='companytaxid',
            constraint=models.UniqueConstraint(fields=('company', 'tax_id'), name='uq_company_tax_id'),
        ),
    ]
