# Generated by Django 5.0.14 on 2026-04-07 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Tenant / Company Profile', 'verbose_name_plural': 'Tenants / Company Profiles'},
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='max_users',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='plan_type',
            field=models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='trial', max_length=30),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe identifier used for subdomain or path routing.', max_length=80, unique=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=60),
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role_code', models.CharField(default='AP_PROCESSOR', max_length=50)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'Tenant Invitation',
                'verbose_name_plural': 'Tenant Invitations',
                'db_table': 'accounts_tenant_invitation',
                'unique_together': {('tenant', 'email')},
            },
        ),
    ]
