# Generated by Django 5.0.14 on 2026-04-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Platform-level super admin -- bypasses tenant scoping and has all permissions across all tenants.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('AP_PROCESSOR', 'AP Processor'), ('REVIEWER', 'Reviewer'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor')], default='AP_PROCESSOR', max_length=30),
        ),
    ]
