# Generated by Django 5.0.14 on 2026-04-08 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkcorridorrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='benchmarkcorridorrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchmarkcorridorrule',
            name='geography',
            field=models.CharField(choices=[('UAE', 'UAE (United Arab Emirates)'), ('KSA', 'KSA (Kingdom of Saudi Arabia)'), ('QATAR', 'Qatar'), ('ALL', 'All Geographies')], db_index=True, default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='benchmarkcorridorrule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='benchmarkcorridorrule',
            name='keywords',
            field=models.TextField(blank=True, default='', help_text='Comma-separated keywords used to match line descriptions to this corridor'),
        ),
        migrations.AlterField(
            model_name='benchmarkcorridorrule',
            name='scope_type',
            field=models.CharField(choices=[('SITC', 'SITC (Supply, Install, Test & Commission)'), ('ITC', 'ITC (Install, Test & Commission only)'), ('EQUIPMENT_ONLY', 'Equipment Only'), ('ALL', 'All Scopes')], db_index=True, default='ALL', max_length=30),
        ),
        migrations.AlterField(
            model_name='benchmarkcorridorrule',
            name='uom',
            field=models.CharField(blank=True, default='', help_text='Unit of measure (AED/ton, AED/m2, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='benchmarkcorridorrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchmarklineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='benchmarklineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchmarklineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchmarklineitem',
            name='variance_pct',
            field=models.FloatField(blank=True, help_text='(quoted_unit_rate - benchmark_mid) / benchmark_mid * 100', null=True),
        ),
        migrations.AlterField(
            model_name='benchmarkquotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='benchmarkquotation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchmarkquotation',
            name='quotation_ref',
            field=models.CharField(blank=True, default='', help_text='Supplier quotation reference number', max_length=100),
        ),
        migrations.AlterField(
            model_name='benchmarkquotation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchmarkrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='benchmarkrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchmarkrequest',
            name='store_type',
            field=models.CharField(blank=True, default='', help_text='Optional store/project type (MALL, HYPERMARKET, WAREHOUSE, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='benchmarkrequest',
            name='title',
            field=models.CharField(help_text='Short label for this request', max_length=255),
        ),
        migrations.AlterField(
            model_name='benchmarkrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchmarkresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='benchmarkresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchmarkresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
