# Generated by Django 5.0.14 on 2026-04-11 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0003_benchmarklineitem_benchmark_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarklineitem',
            name='classification_source',
            field=models.CharField(choices=[('KEYWORD', 'Keyword Rule'), ('AI', 'AI (OpenAI)'), ('MANUAL', 'Manual Override')], default='KEYWORD', help_text='How this line item was classified', max_length=20),
        ),
        migrations.AddField(
            model_name='benchmarkquotation',
            name='blob_name',
            field=models.CharField(blank=True, default='', help_text='Blob name (path) within the benchmarking container', max_length=512),
        ),
        migrations.AddField(
            model_name='benchmarkquotation',
            name='blob_url',
            field=models.URLField(blank=True, default='', help_text='Azure Blob Storage URL after upload (set by BlobStorageService)', max_length=512),
        ),
        migrations.AddField(
            model_name='benchmarkquotation',
            name='di_extraction_json',
            field=models.JSONField(blank=True, default=dict, help_text='Raw Azure Document Intelligence API response (tables, key-value pairs)'),
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. EQUIPMENT, CONTROLS, DUCTING -- must match LineCategory constant', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Human-readable category name', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Procurement definition used as AI context during classification')),
                ('keywords_csv', models.TextField(blank=True, default='', help_text='Comma-separated classification keywords (augments built-in rules)')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Master',
                'verbose_name_plural': 'Category Master',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VarianceThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('CONTROLS', 'Controls'), ('DUCTING', 'Ducting'), ('INSULATION', 'Insulation'), ('ACCESSORIES', 'Accessories'), ('INSTALLATION', 'Installation'), ('TC', 'Testing & Commissioning'), ('UNCATEGORIZED', 'Uncategorized'), ('ALL', 'All Categories')], db_index=True, default='ALL', help_text='Category this rule applies to; ALL = global default', max_length=30)),
                ('geography', models.CharField(choices=[('UAE', 'UAE (United Arab Emirates)'), ('KSA', 'KSA (Kingdom of Saudi Arabia)'), ('QATAR', 'Qatar'), ('ALL', 'All Geographies')], db_index=True, default='ALL', max_length=20)),
                ('within_range_max_pct', models.FloatField(default=5.0, help_text='Max absolute variance% to be classified as WITHIN_RANGE')),
                ('moderate_max_pct', models.FloatField(default=15.0, help_text='Max absolute variance% to be classified as MODERATE (else HIGH)')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variance Threshold Config',
                'verbose_name_plural': 'Variance Threshold Configs',
                'ordering': ['category', 'geography'],
            },
        ),
        migrations.AddConstraint(
            model_name='variancethresholdconfig',
            constraint=models.UniqueConstraint(fields=('category', 'geography'), name='uniq_variance_threshold_cat_geo'),
        ),
    ]
