# Generated by Django 5.0.14 on 2026-04-13 08:05

import apps.benchmarking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0005_benchmarklineitem_tenant_benchmarkquotation_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkquotation',
            name='document',
            field=models.FileField(upload_to=apps.benchmarking.models.benchmark_quotation_upload_to),
        ),
    ]
