# Generated by Django 5.0.14 on 2026-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0006_alter_benchmarkquotation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkrequest',
            name='rfq_document',
            field=models.FileField(blank=True, help_text='Externally uploaded RFQ document (PDF) provided by the user.', null=True, upload_to='benchmarking/rfq_uploads/'),
        ),
        migrations.AddField(
            model_name='benchmarkrequest',
            name='rfq_ref',
            field=models.CharField(blank=True, default='', help_text='RFQ reference string (system ref or filename from uploaded RFQ).', max_length=255),
        ),
        migrations.AddField(
            model_name='benchmarkrequest',
            name='rfq_source',
            field=models.CharField(blank=True, default='', help_text="Source of the RFQ: 'system', 'upload', or 'manual'.", max_length=20),
        ),
    ]
