# Generated by Django 5.0.14 on 2026-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0008_alter_benchmarkquotation_document_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkrequest',
            name='rfq_blob_path',
            field=models.CharField(blank=True, default='', help_text='Azure Blob path for uploaded external RFQ document.', max_length=512),
        ),
        migrations.AddField(
            model_name='benchmarkrequest',
            name='rfq_blob_url',
            field=models.URLField(blank=True, default='', help_text='Azure Blob URL for uploaded external RFQ document.', max_length=1024),
        ),
    ]
