# Generated by Django 5.0.14 on 2026-04-15

from django.db import migrations, models


def set_equipment_market_pricing(apps, schema_editor):
    CategoryMaster = apps.get_model("benchmarking", "CategoryMaster")
    CategoryMaster.objects.filter(code="EQUIPMENT").update(pricing_type="MARKET")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("benchmarking", "0009_benchmarkrequest_rfq_blob_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymaster",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("MARKET", "Market (live external research)"),
                    ("BENCHMARK", "Benchmark (internal configured corridor)"),
                ],
                db_index=True,
                default="BENCHMARK",
                help_text="Pricing source type: MARKET uses live external research, BENCHMARK uses corridor table",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_equipment_market_pricing, noop_reverse),
    ]
