# Generated by Django 5.0.14 on 2026-04-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0017_set_distinct_variance_band_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variancethresholdconfig',
            options={'ordering': ['category', 'geography', 'variance_status'], 'verbose_name': 'Variance Threshold Config', 'verbose_name_plural': 'Variance Threshold Configs'},
        ),
        migrations.AlterField(
            model_name='benchmarkcorridorrule',
            name='category',
            field=models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('PIPING', 'Piping'), ('ELECTRICAL', 'Electrical'), ('CONTROLS', 'Controls'), ('DUCTING', 'Ducting'), ('AIR_DISTRIBUTION', 'Air Distribution'), ('INSULATION', 'Insulation'), ('ACCESSORIES', 'Accessories (Dampers, Louvers, etc.)'), ('INSTALLATION', 'Installation'), ('TC', 'Testing & Commissioning'), ('UNCATEGORIZED', 'Uncategorized')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='benchmarklineitem',
            name='category',
            field=models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('PIPING', 'Piping'), ('ELECTRICAL', 'Electrical'), ('CONTROLS', 'Controls'), ('DUCTING', 'Ducting'), ('AIR_DISTRIBUTION', 'Air Distribution'), ('INSULATION', 'Insulation'), ('ACCESSORIES', 'Accessories (Dampers, Louvers, etc.)'), ('INSTALLATION', 'Installation'), ('TC', 'Testing & Commissioning'), ('UNCATEGORIZED', 'Uncategorized')], db_index=True, default='UNCATEGORIZED', max_length=30),
        ),
        migrations.AlterField(
            model_name='categorymaster',
            name='pricing_type',
            field=models.CharField(choices=[('MARKET', 'Market (live external research)'), ('HYBRID', 'Hybrid (benchmark plus market context)'), ('BENCHMARK', 'Benchmark (internal configured corridor)')], db_index=True, default='BENCHMARK', help_text='Pricing source type: MARKET uses live external research, BENCHMARK uses corridor table', max_length=20),
        ),
        migrations.AlterField(
            model_name='variancethresholdconfig',
            name='category',
            field=models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('PIPING', 'Piping'), ('ELECTRICAL', 'Electrical'), ('CONTROLS', 'Controls'), ('DUCTING', 'Ducting'), ('AIR_DISTRIBUTION', 'Air Distribution'), ('INSULATION', 'Insulation'), ('ACCESSORIES', 'Accessories (Dampers, Louvers, etc.)'), ('INSTALLATION', 'Installation'), ('TC', 'Testing & Commissioning'), ('UNCATEGORIZED', 'Uncategorized'), ('ALL', 'All Categories')], db_index=True, default='ALL', help_text='Category this rule applies to; ALL = global default', max_length=30),
        ),
    ]
