# Generated by Django 5.2.1 on 2026-03-18 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_alter_documentupload_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('normalized_description', models.TextField(blank=True, default='')),
                ('category_code', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('unit', models.CharField(blank=True, default='EA', max_length=50)),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'procurement_quotation_line_item',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('run_type', models.CharField(choices=[('RECOMMENDATION', 'Recommendation'), ('BENCHMARK', 'Benchmark')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_snapshot_json', models.JSONField(blank=True, null=True)),
                ('output_summary', models.TextField(blank=True, default='')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_triggered_runs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_analysis_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenchmarkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_benchmark_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('summary_json', models.JSONField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_results', to='procurement.analysisrun')),
            ],
            options={
                'db_table': 'procurement_benchmark_result',
            },
        ),
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PARTIAL', 'Partial'), ('NOT_CHECKED', 'Not Checked')], default='NOT_CHECKED', max_length=20)),
                ('rules_checked_json', models.JSONField(blank=True, null=True)),
                ('violations_json', models.JSONField(blank=True, null=True)),
                ('recommendations_json', models.JSONField(blank=True, null=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_result', to='procurement.analysisrun')),
            ],
            options={
                'db_table': 'procurement_compliance_result',
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('domain_code', models.CharField(db_index=True, help_text='Business domain (e.g. HVAC, IT, FACILITIES)', max_length=100)),
                ('schema_code', models.CharField(blank=True, default='', help_text='Attribute schema identifier for dynamic forms', max_length=100)),
                ('request_type', models.CharField(choices=[('RECOMMENDATION', 'Product / Solution Recommendation'), ('BENCHMARK', 'Should-Cost Benchmarking'), ('BOTH', 'Recommendation + Benchmarking')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REVIEW_REQUIRED', 'Review Required'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('geography_country', models.CharField(blank=True, default='', max_length=100)),
                ('geography_city', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='procurement.procurementrequest'),
        ),
        migrations.CreateModel(
            name='ProcurementRequestAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_code', models.CharField(db_index=True, max_length=120)),
                ('attribute_label', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('DATE', 'Date'), ('SELECT', 'Select')], default='TEXT', max_length=20)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('normalized_value', models.TextField(blank=True, default='')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='procurement.procurementrequest')),
            ],
            options={
                'db_table': 'procurement_request_attribute',
                'ordering': ['attribute_code'],
            },
        ),
        migrations.CreateModel(
            name='BenchmarkResultLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benchmark_min', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('benchmark_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('benchmark_max', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quoted_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('variance_status', models.CharField(choices=[('WITHIN_RANGE', 'Within Range'), ('ABOVE_BENCHMARK', 'Above Benchmark'), ('BELOW_BENCHMARK', 'Below Benchmark'), ('SIGNIFICANTLY_ABOVE', 'Significantly Above')], default='WITHIN_RANGE', max_length=30)),
                ('remarks', models.TextField(blank=True, default='')),
                ('benchmark_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.benchmarkresult')),
                ('quotation_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_lines', to='procurement.quotationlineitem')),
            ],
            options={
                'db_table': 'procurement_benchmark_result_line',
                'ordering': ['quotation_line__line_number'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_option', models.CharField(max_length=500)),
                ('reasoning_summary', models.TextField(blank=True, default='')),
                ('reasoning_details_json', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('constraints_json', models.JSONField(blank=True, null=True)),
                ('compliance_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PARTIAL', 'Partial'), ('NOT_CHECKED', 'Not Checked')], default='NOT_CHECKED', max_length=20)),
                ('output_payload_json', models.JSONField(blank=True, null=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_result', to='procurement.analysisrun')),
            ],
            options={
                'db_table': 'procurement_recommendation_result',
            },
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_name', models.CharField(db_index=True, max_length=300)),
                ('quotation_number', models.CharField(blank=True, default='', max_length=100)),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('extraction_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.procurementrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_quotations', to='documents.documentupload')),
            ],
            options={
                'db_table': 'procurement_supplier_quotation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.supplierquotation'),
        ),
        migrations.AddField(
            model_name='benchmarkresult',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_results', to='procurement.supplierquotation'),
        ),
        migrations.AddIndex(
            model_name='procurementrequest',
            index=models.Index(fields=['status', 'request_type'], name='procurement_status_5e100a_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementrequest',
            index=models.Index(fields=['domain_code', 'status'], name='procurement_domain__899d48_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['request', 'run_type', 'status'], name='procurement_request_bf272b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procurementrequestattribute',
            unique_together={('request', 'attribute_code')},
        ),
        migrations.AlterUniqueTogether(
            name='quotationlineitem',
            unique_together={('quotation', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='benchmarkresult',
            unique_together={('run', 'quotation')},
        ),
    ]
