# Generated by Django 5.2.1 on 2026-03-19 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='run_type',
            field=models.CharField(choices=[('RECOMMENDATION', 'Recommendation'), ('BENCHMARK', 'Benchmark'), ('VALIDATION', 'Validation')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation_type', models.CharField(choices=[('ATTRIBUTE_COMPLETENESS', 'Attribute Completeness'), ('DOCUMENT_COMPLETENESS', 'Document Completeness'), ('SCOPE_COVERAGE', 'Scope Coverage'), ('AMBIGUITY_CHECK', 'Ambiguity Check'), ('COMMERCIAL_COMPLETENESS', 'Commercial Completeness'), ('COMPLIANCE_READINESS', 'Compliance Readiness')], default='ATTRIBUTE_COMPLETENESS', help_text='Primary validation type (or ATTRIBUTE_COMPLETENESS for combined)', max_length=40)),
                ('overall_status', models.CharField(choices=[('PASS', 'Pass'), ('PASS_WITH_WARNINGS', 'Pass with Warnings'), ('REVIEW_REQUIRED', 'Review Required'), ('FAIL', 'Fail')], default='FAIL', max_length=30)),
                ('completeness_score', models.FloatField(default=0.0, help_text='0-100 percentage')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('readiness_for_recommendation', models.BooleanField(default=False)),
                ('readiness_for_benchmarking', models.BooleanField(default=False)),
                ('recommended_next_action', models.CharField(blank=True, choices=[('READY_FOR_RECOMMENDATION', 'Ready for Recommendation'), ('READY_FOR_BENCHMARKING', 'Ready for Benchmarking'), ('REQUEST_REFINEMENT', 'Request Refinement'), ('NEEDS_TECHNICAL_REVIEW', 'Needs Technical Review'), ('NEEDS_COMMERCIAL_REVIEW', 'Needs Commercial Review')], default='', max_length=40)),
                ('missing_items_json', models.JSONField(blank=True, help_text='List of missing item dicts', null=True)),
                ('warnings_json', models.JSONField(blank=True, help_text='List of warning dicts', null=True)),
                ('ambiguous_items_json', models.JSONField(blank=True, help_text='List of ambiguous item dicts', null=True)),
                ('output_payload_json', models.JSONField(blank=True, help_text='Full structured output for API consumers', null=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='procurement.analysisrun')),
            ],
            options={
                'db_table': 'procurement_validation_result',
            },
        ),
        migrations.CreateModel(
            name='ValidationResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(max_length=120)),
                ('item_label', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('ATTRIBUTE_COMPLETENESS', 'Attribute Completeness'), ('DOCUMENT_COMPLETENESS', 'Document Completeness'), ('SCOPE_COVERAGE', 'Scope Coverage'), ('AMBIGUITY_CHECK', 'Ambiguity Check'), ('COMMERCIAL_COMPLETENESS', 'Commercial Completeness'), ('COMPLIANCE_READINESS', 'Compliance Readiness')], help_text='Which validation dimension this item belongs to', max_length=40)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('MISSING', 'Missing'), ('WARNING', 'Warning'), ('AMBIGUOUS', 'Ambiguous'), ('FAILED', 'Failed')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='ERROR', max_length=20)),
                ('source_type', models.CharField(choices=[('ATTRIBUTE', 'Attribute'), ('DOCUMENT', 'Document'), ('LINE_ITEM', 'Line Item'), ('RULE', 'Rule'), ('AGENT', 'Agent')], default='RULE', max_length=20)),
                ('source_reference', models.CharField(blank=True, default='', help_text='Rule code, attribute code, or document reference', max_length=200)),
                ('remarks', models.TextField(blank=True, default='')),
                ('details_json', models.JSONField(blank=True, null=True)),
                ('validation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.validationresult')),
            ],
            options={
                'db_table': 'procurement_validation_result_item',
                'ordering': ['category', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_code', models.CharField(blank=True, db_index=True, default='', help_text='Business domain (blank = generic / all domains)', max_length=100)),
                ('schema_code', models.CharField(blank=True, default='', help_text='Attribute schema identifier (blank = all schemas)', max_length=100)),
                ('rule_set_code', models.CharField(db_index=True, max_length=120, unique=True)),
                ('rule_set_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('validation_type', models.CharField(choices=[('ATTRIBUTE_COMPLETENESS', 'Attribute Completeness'), ('DOCUMENT_COMPLETENESS', 'Document Completeness'), ('SCOPE_COVERAGE', 'Scope Coverage'), ('AMBIGUITY_CHECK', 'Ambiguity Check'), ('COMMERCIAL_COMPLETENESS', 'Commercial Completeness'), ('COMPLIANCE_READINESS', 'Compliance Readiness')], db_index=True, max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('config_json', models.JSONField(blank=True, help_text='Domain-specific checklist/config (e.g. expected docs, categories, commercial terms)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_validation_rule_set',
                'ordering': ['priority', 'rule_set_code'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(db_index=True, max_length=120)),
                ('rule_name', models.CharField(max_length=300)),
                ('rule_type', models.CharField(choices=[('REQUIRED_ATTRIBUTE', 'Required Attribute'), ('REQUIRED_DOCUMENT', 'Required Document'), ('REQUIRED_CATEGORY', 'Required Category'), ('AMBIGUITY_PATTERN', 'Ambiguity Pattern'), ('COMMERCIAL_CHECK', 'Commercial Check'), ('COMPLIANCE_CHECK', 'Compliance Check')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='ERROR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('evaluation_mode', models.CharField(choices=[('DETERMINISTIC', 'Deterministic'), ('AGENT_ASSISTED', 'Agent-Assisted')], default='DETERMINISTIC', max_length=20)),
                ('condition_json', models.JSONField(blank=True, help_text='Evaluation conditions (attribute_code, pattern, etc.)', null=True)),
                ('expected_value_json', models.JSONField(blank=True, help_text='Expected value or pattern for comparison', null=True)),
                ('failure_message', models.CharField(blank=True, default='', max_length=500)),
                ('remediation_hint', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='procurement.validationruleset')),
            ],
            options={
                'db_table': 'procurement_validation_rule',
                'ordering': ['display_order', 'rule_code'],
            },
        ),
        migrations.AddIndex(
            model_name='validationruleset',
            index=models.Index(fields=['domain_code', 'validation_type', 'is_active'], name='procurement_domain__2de00e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validationrule',
            unique_together={('rule_set', 'rule_code')},
        ),
    ]
