# Generated by Django 5.2.1 on 2026-03-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documentupload_document_type'),
        ('procurement', '0002_add_validation_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='prefill_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='prefill_payload_json',
            field=models.JSONField(blank=True, help_text='Raw extracted prefill payload before user confirmation', null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='prefill_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW_PENDING', 'Review Pending')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='source_document_type',
            field=models.CharField(blank=True, choices=[('RFQ', 'RFQ'), ('REQUIREMENT_NOTE', 'Requirement Note'), ('SPECIFICATION', 'Specification'), ('BOQ', 'BOQ'), ('PROPOSAL', 'Proposal'), ('QUOTATION', 'Quotation'), ('OTHER', 'Other')], default='', help_text='Type of source document (RFQ, BOQ, etc.)', max_length=30),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='uploaded_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='documents.documentupload'),
        ),
        migrations.AddField(
            model_name='procurementrequestattribute',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequestattribute',
            name='extraction_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PREFILL', 'Prefill'), ('SYSTEM', 'System')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='extraction_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PREFILL', 'Prefill'), ('SYSTEM', 'System')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='prefill_payload_json',
            field=models.JSONField(blank=True, help_text='Raw extracted prefill payload before user confirmation', null=True),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='prefill_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW_PENDING', 'Review Pending')], default='NOT_STARTED', max_length=20),
        ),
    ]
