# Generated by Django 5.0.14 on 2026-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_procurementrequest_prefill_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationresult',
            name='recommended_next_action',
            field=models.CharField(blank=True, choices=[('READY_FOR_RECOMMENDATION', 'Ready for Recommendation'), ('READY_FOR_BENCHMARKING', 'Ready for Benchmarking'), ('REQUEST_REFINEMENT', 'Request Refinement')], default='', max_length=40),
        ),
    ]
