# Generated by Django 5.0.14 on 2026-04-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_procurementagentexecutionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='thought_process_log',
            field=models.JSONField(blank=True, help_text='Step-by-step agent reasoning log: list of {"step": N, "stage": str, "decision": str, "reasoning": str} entries written during AI analysis for full traceability.', null=True),
        ),
        migrations.AddField(
            model_name='validationresult',
            name='failure_digest_text',
            field=models.TextField(blank=True, default='', help_text='Plain-English root-cause digest of every validation failure: what is missing, why each item is required, and the exact remediation step needed to fix it. Written after each run for developer and analyst debugging.'),
        ),
    ]
