# Generated by Django 5.0.14 on 2026-04-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_validationresult_recommended_next_action'),
        ('procurement', '0005_add_thought_process_and_failure_digest'),
    ]

    operations = [
    ]
