# Generated by Django 5.0.14 on 2026-04-07 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_merge_20260407_1053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSourceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(db_index=True, max_length=300)),
                ('domain', models.CharField(db_index=True, default='HVAC', max_length=100)),
                ('base_url', models.URLField(max_length=500)),
                ('source_type', models.CharField(choices=[('OEM_OFFICIAL', 'OEM Official Pages'), ('OEM_REGIONAL', 'OEM Regional Pages'), ('AUTHORIZED_DISTRIBUTOR', 'Authorized Distributor'), ('TECHNICAL_DATASHEET', 'Technical Datasheet (PDF)'), ('STANDARD', 'Standards Reference'), ('REGULATORY', 'Regulatory Source'), ('LANDLORD_GUIDE', 'Landlord / Mall Guide'), ('INTERNAL_HISTORICAL', 'Internal Historical Reference')], db_index=True, max_length=40)),
                ('country_scope', models.TextField(blank=True, default='', help_text='Comma-separated country codes (e.g. UAE,SAR,OMAN). Blank = all.')),
                ('system_family_scope', models.TextField(blank=True, default='', help_text='Comma-separated HVACSystemFamily codes. Blank = all.')),
                ('allowed_for_discovery', models.BooleanField(default=True, help_text='Source may be used for external product discovery.')),
                ('allowed_for_compliance', models.BooleanField(default=False, help_text='Source may be cited as compliance/standards evidence.')),
                ('fetch_mode', models.CharField(choices=[('WEB_PAGE', 'Web Page (HTML)'), ('PDF', 'PDF Document'), ('API', 'Structured API')], default='WEB_PAGE', max_length=20)),
                ('trust_score', models.FloatField(default=0.8, help_text='Trust score 0.0-1.0; applied to product candidates sourced from here.')),
                ('priority', models.PositiveIntegerField(default=50, help_text='Lower number = higher priority when multiple sources match.')),
                ('oem_brand', models.CharField(blank=True, default='', help_text='OEM brand name (e.g. Daikin, Carrier). Optional; used to filter by preferred_oems.', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_external_source_registry',
                'ordering': ['priority', 'source_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_code', models.CharField(db_index=True, default='HVAC', max_length=100)),
                ('system_family', models.CharField(choices=[('SPLIT', 'Split AC System'), ('PACKAGED_DX', 'Packaged DX Unit'), ('VRF', 'VRF / VRV System'), ('CHILLED_WATER_INTERFACE', 'Chilled Water Interface (FCU/AHU)'), ('ALTERNATE_OPTION', 'Alternate Option')], db_index=True, max_length=40)),
                ('oem_name', models.CharField(db_index=True, max_length=200)),
                ('product_family', models.CharField(max_length=200)),
                ('model_code', models.CharField(blank=True, default='', max_length=200)),
                ('capacity_min_tr', models.FloatField(blank=True, help_text='Minimum cooling capacity in Tonnes of Refrigeration.', null=True)),
                ('capacity_max_tr', models.FloatField(blank=True, help_text='Maximum cooling capacity in Tonnes of Refrigeration.', null=True)),
                ('efficiency_attributes_json', models.JSONField(blank=True, help_text='Key efficiency metadata: EER, COP, ESEER, refrigerant type, etc.', null=True)),
                ('geography_scope', models.TextField(blank=True, default='', help_text='Comma-separated country/region codes. Blank = global.')),
                ('source_type', models.CharField(blank=True, choices=[('OEM_OFFICIAL', 'OEM Official Pages'), ('OEM_REGIONAL', 'OEM Regional Pages'), ('AUTHORIZED_DISTRIBUTOR', 'Authorized Distributor'), ('TECHNICAL_DATASHEET', 'Technical Datasheet (PDF)'), ('STANDARD', 'Standards Reference'), ('REGULATORY', 'Regulatory Source'), ('LANDLORD_GUIDE', 'Landlord / Mall Guide'), ('INTERNAL_HISTORICAL', 'Internal Historical Reference')], default='', max_length=40)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_internal', models.BooleanField(default=True, help_text='True = product is from the internal approved product master.')),
                ('is_external_discovered', models.BooleanField(default=False, help_text='True = product was discovered via external source rather than pre-approved.')),
                ('approval_status', models.CharField(choices=[('APPROVED', 'Approved'), ('UNDER_REVIEW', 'Under Review'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('DEPRECATED', 'Deprecated')], db_index=True, default='PENDING', max_length=20)),
                ('technical_notes', models.TextField(blank=True, default='')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source_registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='procurement.externalsourceregistry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_product_catalog_item',
                'ordering': ['system_family', 'oem_name', 'product_family'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_source', models.CharField(choices=[('INTERNAL_APPROVED', 'Internal Approved Product'), ('EXTERNAL_DISCOVERED', 'External Candidate (Discovered)'), ('HISTORICAL_AWARD', 'Historical Award Record')], db_index=True, max_length=30)),
                ('fit_score', models.FloatField(default=0.0, help_text='Overall composite fit score.')),
                ('technical_fit_score', models.FloatField(default=0.0)),
                ('operational_fit_score', models.FloatField(default=0.0)),
                ('commercial_fit_score', models.FloatField(default=0.0)),
                ('source_trust_score', models.FloatField(default=0.0)),
                ('ranking_position', models.PositiveIntegerField(default=99, help_text='1-based ranking; 1 = top candidate.')),
                ('raw_product_name', models.CharField(blank=True, default='', max_length=300)),
                ('raw_oem_name', models.CharField(blank=True, default='', max_length=200)),
                ('raw_model_code', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('source_title', models.CharField(blank=True, default='', max_length=300)),
                ('reasoning_json', models.JSONField(blank=True, help_text='AI reasoning text: tradeoffs, operational notes, commercial notes.', null=True)),
                ('requires_validation', models.BooleanField(default=False, help_text='True = candidate needs human or engineering validation before being promoted.')),
                ('is_top_recommendation', models.BooleanField(db_index=True, default=False, help_text='True = this candidate is the final top recommendation for this run.')),
                ('system_family', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('capacity_band', models.CharField(blank=True, default='', max_length=20)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_candidates', to='procurement.productcatalogitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_candidates', to='procurement.analysisrun')),
            ],
            options={
                'db_table': 'procurement_recommendation_candidate',
                'ordering': ['ranking_position'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('STANDARDS_REFERENCE', 'Standards Reference'), ('OEM_DATASHEET', 'OEM Datasheet'), ('COMPLIANCE_NOTE', 'Compliance Note'), ('LANDLORD_GUIDE', 'Landlord / Mall Guide'), ('HISTORICAL_AWARD', 'Historical Award Data'), ('AI_GENERATED', 'AI-Generated Reasoning')], db_index=True, max_length=40)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('source_title', models.CharField(blank=True, default='', max_length=300)),
                ('source_class', models.CharField(blank=True, default='', help_text="ExternalSourceType value or 'INTERNAL'.", max_length=40)),
                ('snippet_json', models.JSONField(blank=True, help_text='Extracted text snippet or structured fact object from the source.', null=True)),
                ('used_in_stage', models.CharField(blank=True, default='', help_text="Pipeline stage where this evidence was used (e.g. 'compliance', 'product_discovery').", max_length=60)),
                ('source_trust_score', models.FloatField(default=1.0, help_text='Inherited from ExternalSourceRegistry.trust_score for external artifacts.')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True = evidence was generated by AI reasoning, not fetched from an external source.')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_evidences', to='procurement.analysisrun')),
            ],
            options={
                'db_table': 'procurement_recommendation_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externalsourceregistry',
            index=models.Index(fields=['domain', 'source_type'], name='procurement_domain_64f374_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsourceregistry',
            index=models.Index(fields=['allowed_for_discovery'], name='procurement_allowed_7f80e7_idx'),
        ),
        migrations.AddIndex(
            model_name='productcatalogitem',
            index=models.Index(fields=['domain_code', 'system_family'], name='procurement_domain__458bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='productcatalogitem',
            index=models.Index(fields=['oem_name', 'approval_status'], name='procurement_oem_nam_545556_idx'),
        ),
        migrations.AddIndex(
            model_name='productcatalogitem',
            index=models.Index(fields=['is_internal', 'is_external_discovered'], name='procurement_is_inte_abc2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationcandidate',
            index=models.Index(fields=['run', 'ranking_position'], name='procurement_run_id_ef0305_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationcandidate',
            index=models.Index(fields=['candidate_source', 'is_top_recommendation'], name='procurement_candida_3f392a_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationevidence',
            index=models.Index(fields=['run', 'evidence_type'], name='procurement_run_id_6cdc88_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationevidence',
            index=models.Index(fields=['used_in_stage'], name='procurement_used_in_66e254_idx'),
        ),
    ]
