# Generated by Django 5.0.14 on 2026-04-07 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_hvac_external_source_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationcandidate',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='recommendationcandidate',
            name='run',
        ),
        migrations.RemoveField(
            model_name='recommendationevidence',
            name='run',
        ),
        migrations.AlterField(
            model_name='externalsourceregistry',
            name='allowed_for_compliance',
            field=models.BooleanField(default=False, help_text='Allow this source to be cited as compliance / regulatory evidence'),
        ),
        migrations.AlterField(
            model_name='externalsourceregistry',
            name='allowed_for_discovery',
            field=models.BooleanField(default=True, help_text='Allow AI discovery agent to search this source for product candidates'),
        ),
        migrations.AlterField(
            model_name='externalsourceregistry',
            name='trust_score',
            field=models.FloatField(default=0.8, help_text='Trust score 0.0-1.0 used in candidate ranking'),
        ),
        migrations.CreateModel(
            name='HVACRecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(db_index=True, help_text='Display ID, e.g. R1, R2, R3', max_length=10, unique=True)),
                ('rule_name', models.CharField(help_text='Short description of the rule', max_length=200)),
                ('store_type_filter', models.CharField(blank=True, choices=[('', 'Any'), ('MALL', 'Mall'), ('STANDALONE', 'Standalone'), ('HOSPITAL', 'Hospital'), ('WAREHOUSE', 'Warehouse'), ('OFFICE', 'Office'), ('HYPERMARKET', 'Hypermarket'), ('DATA_CENTER', 'Data Center')], default='', help_text='Blank = any store type', max_length=20)),
                ('area_sq_ft_min', models.FloatField(blank=True, help_text='Lower bound on area (sq ft inclusive); null = no lower bound', null=True)),
                ('area_sq_ft_max', models.FloatField(blank=True, help_text='Upper bound on area (sq ft exclusive); null = no upper bound', null=True)),
                ('ambient_temp_min_c', models.FloatField(blank=True, help_text='Lower bound on ambient temperature (C inclusive); null = no lower bound', null=True)),
                ('budget_level_filter', models.CharField(blank=True, choices=[('', 'Any'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('LOW_MEDIUM', 'Low / Medium'), ('MEDIUM_HIGH', 'Medium / High')], default='', help_text='Blank = any.  LOW_MEDIUM = matches LOW or MEDIUM.', max_length=20)),
                ('energy_priority_filter', models.CharField(blank=True, choices=[('', 'Any'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('LOW_MEDIUM', 'Low / Medium'), ('MEDIUM_HIGH', 'Medium / High')], default='', help_text='Blank = any.  LOW_MEDIUM = matches LOW or MEDIUM.', max_length=20)),
                ('recommended_system', models.CharField(choices=[('VRF', 'VRF System'), ('SPLIT_AC', 'Split AC'), ('PACKAGED_DX', 'Packaged DX Unit'), ('FCU', 'Fan Coil Unit'), ('CHILLER', 'Chiller'), ('CASSETTE', 'Cassette Split')], db_index=True, help_text='Recommended HVAC system type when this rule matches', max_length=30)),
                ('alternate_system', models.CharField(blank=True, choices=[('', 'None'), ('VRF', 'VRF System'), ('SPLIT_AC', 'Split AC'), ('PACKAGED_DX', 'Packaged DX Unit'), ('FCU', 'Fan Coil Unit'), ('CHILLER', 'Chiller'), ('CASSETTE', 'Cassette Split')], default='', help_text='Optional fallback / alternate system type', max_length=30)),
                ('rationale', models.TextField(blank=True, default='', help_text='Brief plain-text explanation for this rule (shown in the UI)')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = evaluated first; first match wins')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HVAC Recommendation Rule',
                'verbose_name_plural': 'HVAC Recommendation Rules',
                'db_table': 'procurement_hvac_recommendation_rule',
                'ordering': ['priority', 'rule_code'],
            },
        ),
        migrations.DeleteModel(
            name='ProductCatalogItem',
        ),
        migrations.DeleteModel(
            name='RecommendationCandidate',
        ),
        migrations.DeleteModel(
            name='RecommendationEvidence',
        ),
        migrations.AddIndex(
            model_name='hvacrecommendationrule',
            index=models.Index(fields=['is_active', 'priority'], name='procurement_is_acti_2303d9_idx'),
        ),
    ]
