# Generated by Django 5.0.14 on 2026-04-07 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0008_hvac_recommendation_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HVACStoreProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, db_index=True)),
                ("store_id", models.CharField(db_index=True, max_length=120, unique=True)),
                ("brand", models.CharField(blank=True, default="", max_length=200)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("store_type", models.CharField(blank=True, default="", max_length=50)),
                ("store_format", models.CharField(blank=True, default="", max_length=50)),
                ("area_sqft", models.FloatField(blank=True, null=True)),
                ("ceiling_height_ft", models.FloatField(blank=True, null=True)),
                ("operating_hours", models.CharField(blank=True, default="", max_length=120)),
                ("footfall_category", models.CharField(blank=True, default="", max_length=50)),
                ("ambient_temp_max", models.FloatField(blank=True, null=True)),
                ("humidity_level", models.CharField(blank=True, default="", max_length=50)),
                ("dust_exposure", models.CharField(blank=True, default="", max_length=50)),
                ("heat_load_category", models.CharField(blank=True, default="", max_length=50)),
                ("fresh_air_requirement", models.CharField(blank=True, default="", max_length=50)),
                ("landlord_constraints", models.TextField(blank=True, default="")),
                ("existing_hvac_type", models.CharField(blank=True, default="", max_length=200)),
                ("budget_level", models.CharField(blank=True, default="", max_length=50)),
                ("energy_efficiency_priority", models.CharField(blank=True, default="", max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "procurement_hvac_store_profile",
                "ordering": ["store_id"],
            },
        ),
    ]
