# Generated by Django 5.0.14 on 2026-04-08 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_hvacstoreprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIntelligenceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rephrased_query', models.TextField(blank=True, default='')),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('market_context', models.TextField(blank=True, default='')),
                ('system_code', models.CharField(blank=True, default='', max_length=100)),
                ('system_name', models.CharField(blank=True, default='', max_length=200)),
                ('suggestions_json', models.JSONField(default=list, help_text='Full list of suggestion dicts as returned by the LLM.')),
                ('suggestion_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_suggestions_generated', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_suggestions', to='procurement.procurementrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_market_intelligence_suggestion',
                'ordering': ['-created_at'],
            },
        ),
    ]
