# Generated by Django 5.0.14 on 2026-04-09 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_externalsource_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HVACServiceScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_type', models.CharField(choices=[('VRF', 'VRF System'), ('SPLIT_AC', 'Split AC'), ('PACKAGED_DX', 'Packaged DX Unit'), ('FCU', 'Fan Coil Unit'), ('CHILLER', 'Chiller'), ('CASSETTE', 'Cassette Split')], db_index=True, help_text='HVAC system type (matches HVACSystemType enum)', max_length=30, unique=True)),
                ('equipment_scope', models.TextField(help_text='Physical equipment included (e.g. indoor & outdoor units)')),
                ('installation_services', models.TextField(help_text='Labor and installation work (e.g. mounting, fixing, alignment)')),
                ('piping_ducting', models.TextField(help_text='Refrigerant copper piping or GI ducting')),
                ('electrical_works', models.TextField(help_text='Power supply, cabling, panels, isolators')),
                ('controls_accessories', models.TextField(help_text='Control systems and small components (thermostat, dampers, sensors)')),
                ('testing_commissioning', models.TextField(help_text='Final verification stage (cooling test, performance check)')),
                ('sort_order', models.IntegerField(default=10, help_text='Display order -- lower value appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HVAC Service Scope',
                'verbose_name_plural': 'HVAC Service Scopes',
                'db_table': 'procurement_hvac_service_scope',
                'ordering': ['sort_order', 'system_type'],
            },
        ),
    ]
