# Generated by Django 5.0.14 on 2026-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_hvac_service_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='hvacservicescope',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="Override display label shown in the UI (e.g. 'Packaged Unit (Rooftop)'). Falls back to system_type if blank.", max_length=150),
        ),
        migrations.AlterField(
            model_name='hvacservicescope',
            name='system_type',
            field=models.CharField(db_index=True, help_text='HVAC system type key (e.g. SPLIT_AC, VRF, CHILLER, DUCTING)', max_length=30, unique=True),
        ),
    ]
