# Generated by Django 5.0.14 on 2026-04-09 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_hvac_service_scope_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq_ref', models.CharField(db_index=True, help_text='Human-readable reference e.g. RFQ-0001-20250101', max_length=80)),
                ('system_code', models.CharField(default='', help_text='HVAC system type code used for this RFQ (e.g. VRF, SPLIT_AC)', max_length=30)),
                ('system_label', models.CharField(default='', help_text='Human-readable system label at time of generation', max_length=150)),
                ('qty_json', models.JSONField(default=dict, help_text='Per-row quantity overrides used when building the scope table')),
                ('xlsx_blob_path', models.CharField(blank=True, default='', help_text='Azure Blob path for the Excel file (empty if blob not configured)', max_length=500)),
                ('pdf_blob_path', models.CharField(blank=True, default='', help_text='Azure Blob path for the PDF file (empty if blob not configured)', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_rfqs', to='procurement.procurementrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated RFQ',
                'verbose_name_plural': 'Generated RFQs',
                'db_table': 'procurement_generated_rfq',
                'ordering': ['-created_at'],
            },
        ),
    ]
