# Generated by Django 5.0.14 on 2026-04-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_recommendationresult_reason_summary_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketintelligencesuggestion',
            name='perplexity_citations_json',
            field=models.JSONField(blank=True, default=list, help_text='Raw citations list returned by Perplexity API (top-level field). These are the real URLs Perplexity fetched during live search.'),
        ),
    ]
