# Generated by Django 5.0.14 on 2026-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_add_perplexity_citations_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsourceregistry',
            name='equipment',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Equipment type within the HVAC system e.g. 'VRF Outdoor Unit', 'Chiller Unit', 'FCU / AHU Units'.", max_length=200),
        ),
    ]
