# Generated by Django 5.0.14 on 2026-04-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_add_tenant_fk'),
        ('procurement', '0019_add_equipment_field'),
    ]

    operations = [
    ]
