# Generated by Django 5.0.14 on 2026-04-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_merge_0005_add_tenant_fk_0019_add_equipment_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketintelligencesuggestion',
            name='source_reference_label',
            field=models.CharField(blank=True, default='Perplexity Source References', help_text='Display label for citations source, e.g. Perplexity or Azure OpenAI.', max_length=120),
        ),
    ]
