# Generated by Django 5.0.14 on 2026-04-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_email_thread_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_RFQ', 'Pending RFQ'), ('READY_RFQ', 'Ready RFQ'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING_RFQ', max_length=20),
        ),
    ]
