# Generated by Django 5.2.1 on 2026-03-21 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0007_add_extraction_approval'),
        ('extraction_configs', '0001_initial'),
        ('extraction_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(help_text='Original file name', max_length=500)),
                ('file_path', models.CharField(blank=True, default='', help_text='Storage path (blob or local)', max_length=1000)),
                ('file_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash for deduplication', max_length=128)),
                ('page_count', models.PositiveIntegerField(default=0, help_text='Number of pages in the document')),
                ('jurisdiction_confidence', models.FloatField(blank=True, help_text='0.0–1.0 confidence of jurisdiction resolution', null=True)),
                ('jurisdiction_signals_json', models.JSONField(blank=True, default=dict, help_text='Signals used for jurisdiction resolution (e.g. tax_ids_found, currency_detected)')),
                ('classified_document_type', models.CharField(blank=True, default='', help_text='Document type classification result', max_length=50)),
                ('classification_confidence', models.FloatField(blank=True, help_text='0.0–1.0 confidence of document classification', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLASSIFYING', 'Classifying'), ('EXTRACTING', 'Extracting'), ('NORMALIZING', 'Normalizing'), ('VALIDATING', 'Validating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30)),
                ('ocr_text', models.TextField(blank=True, default='', help_text='Raw OCR text extracted from the document')),
                ('ocr_engine', models.CharField(blank=True, default='', help_text='OCR engine used (e.g. azure_di, tesseract)', max_length=50)),
                ('extracted_data_json', models.JSONField(blank=True, default=dict, help_text='Structured extraction output (header + line items + tax)')),
                ('extraction_confidence', models.FloatField(blank=True, help_text='Overall extraction confidence 0.0–1.0', null=True)),
                ('extraction_method', models.CharField(blank=True, default='', help_text='Method used: deterministic, llm, hybrid', max_length=30)),
                ('validation_errors_json', models.JSONField(blank=True, default=list, help_text='List of validation errors found post-extraction')),
                ('validation_warnings_json', models.JSONField(blank=True, default=list, help_text='List of validation warnings')),
                ('is_valid', models.BooleanField(help_text='Whether the extraction passed validation', null=True)),
                ('extraction_started_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_upload', models.ForeignKey(blank=True, help_text='Source document upload (if originating from PO-recon pipeline)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_documents', to='documents.documentupload')),
                ('resolved_jurisdiction', models.ForeignKey(blank=True, help_text='Jurisdiction resolved by the JurisdictionResolverService', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_documents', to='extraction_core.taxjurisdictionprofile')),
                ('resolved_schema', models.ForeignKey(blank=True, help_text='Extraction schema selected for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_documents', to='extraction_core.extractionschemadefinition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Document',
                'verbose_name_plural': 'Extraction Documents',
                'db_table': 'extraction_documents_extraction_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionFieldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(db_index=True, help_text='Denormalized field key for fast queries', max_length=100)),
                ('raw_value', models.TextField(blank=True, default='', help_text='Value as extracted (before normalization)')),
                ('normalized_value', models.TextField(blank=True, default='', help_text='Value after normalization')),
                ('confidence', models.FloatField(blank=True, help_text='0.0–1.0 field-level extraction confidence', null=True)),
                ('extraction_method', models.CharField(choices=[('DETERMINISTIC', 'Deterministic (regex/rule)'), ('LLM', 'LLM-based'), ('HYBRID', 'Hybrid (rule + LLM)'), ('MANUAL', 'Manual Override')], default='DETERMINISTIC', max_length=20)),
                ('source_text_snippet', models.TextField(blank=True, default='', help_text='Surrounding text from OCR output that contains this field')),
                ('page_number', models.PositiveIntegerField(blank=True, help_text='Page where this field was found (1-indexed)', null=True)),
                ('line_item_index', models.PositiveIntegerField(blank=True, help_text='Line item index (0-based) if this is a line-item field', null=True)),
                ('is_valid', models.BooleanField(help_text='Whether this field passed validation', null=True)),
                ('validation_message', models.CharField(blank=True, default='', help_text='Validation error/warning message if applicable', max_length=500)),
                ('document', models.ForeignKey(help_text='Parent extraction document', on_delete=django.db.models.deletion.CASCADE, related_name='field_results', to='extraction_documents.extractiondocument')),
                ('field_definition', models.ForeignKey(help_text='Field definition from the registry', on_delete=django.db.models.deletion.PROTECT, related_name='extraction_results', to='extraction_configs.taxfielddefinition')),
            ],
            options={
                'verbose_name': 'Extraction Field Result',
                'verbose_name_plural': 'Extraction Field Results',
                'db_table': 'extraction_documents_extraction_field_result',
                'ordering': ['document', 'line_item_index', 'field_key'],
            },
        ),
    ]
