# Generated by Django 5.2.1 on 2026-03-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiondocument',
            name='declared_country_code',
            field=models.CharField(blank=True, default='', help_text='Caller-declared country code (document-level override)', max_length=3),
        ),
        migrations.AddField(
            model_name='extractiondocument',
            name='declared_regime_code',
            field=models.CharField(blank=True, default='', help_text='Caller-declared tax regime code (document-level override)', max_length=50),
        ),
        migrations.AddField(
            model_name='extractiondocument',
            name='jurisdiction_resolution_mode',
            field=models.CharField(blank=True, default='', help_text='Mode used for resolution (AUTO, FIXED, HYBRID)', max_length=20),
        ),
        migrations.AddField(
            model_name='extractiondocument',
            name='jurisdiction_source',
            field=models.CharField(blank=True, default='', help_text='Source of the resolved jurisdiction (e.g. DOCUMENT_OVERRIDE, AUTO_DETECTED)', max_length=30),
        ),
        migrations.AddField(
            model_name='extractiondocument',
            name='jurisdiction_warning',
            field=models.TextField(blank=True, default='', help_text='Warning message from hybrid mode mismatch or low confidence'),
        ),
    ]
