# Generated by Django 5.0.14 on 2026-04-17 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('integrations', '0003_add_tenant_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='integrationconfig',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='uq_integration_config_name_tenant'),
        ),
    ]
