# Generated by Django 5.2.1 on 2026-03-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('input_schema', models.JSONField(blank=True, help_text='JSON Schema for tool input', null=True)),
                ('output_schema', models.JSONField(blank=True, help_text='JSON Schema for tool output', null=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('module_path', models.CharField(blank=True, default='', help_text='Python dotted path to tool class', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool Definition',
                'verbose_name_plural': 'Tool Definitions',
                'db_table': 'tools_definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='REQUESTED', max_length=20)),
                ('input_payload', models.JSONField(blank=True, null=True)),
                ('output_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='agents.agentrun')),
                ('tool_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='tools.tooldefinition')),
            ],
            options={
                'verbose_name': 'Tool Call',
                'verbose_name_plural': 'Tool Calls',
                'db_table': 'tools_call',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool_name'], name='idx_toolcall_name'), models.Index(fields=['status'], name='idx_toolcall_status'), models.Index(fields=['agent_run'], name='idx_toolcall_agentrun')],
            },
        ),
    ]
