# Generated by Django 5.0.14 on 2026-04-08 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcall',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
