"""Report generation tracking model."""
from django.conf import settings
from django.db import models

from apps.core.models import BaseModel


class GeneratedReport(BaseModel):
    """Tracks reports generated by the system (CSV/Excel exports, etc.)."""

    report_type = models.CharField(max_length=100, db_index=True)
    title = models.CharField(max_length=300)
    file = models.FileField(upload_to="reports/%Y/%m/", null=True, blank=True)
    format = models.CharField(max_length=10, default="csv", help_text="csv or xlsx")
    parameters = models.JSONField(null=True, blank=True, help_text="Filters / params used to generate")
    record_count = models.PositiveIntegerField(default=0)
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="generated_reports"
    )
    celery_task_id = models.CharField(max_length=255, blank=True, default="")
    success = models.BooleanField(default=True)
    error_message = models.TextField(blank=True, default="")

    class Meta:
        db_table = "reports_generated"
        ordering = ["-created_at"]
        verbose_name = "Generated Report"
        verbose_name_plural = "Generated Reports"
        indexes = [
            models.Index(fields=["report_type"], name="idx_report_type"),
        ]

    def __str__(self) -> str:
        return f"Report #{self.pk} – {self.title}"
