# Generated by Django 5.2.1 on 2026-03-11 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_agentrecommendation_accepted_at_and_more'),
        ('documents', '0002_add_reconciliation_mode_support'),
        ('reconciliation', '0003_add_reconciliation_mode_support'),
        ('reviews', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('case_number', models.CharField(db_index=True, help_text='Auto-generated case identifier, e.g. AP-000123', max_length=50, unique=True)),
                ('source_channel', models.CharField(choices=[('WEB_UPLOAD', 'Web Upload'), ('EMAIL', 'Email'), ('API', 'API'), ('ERP_IMPORT', 'ERP Import'), ('SCAN', 'Scan')], default='WEB_UPLOAD', max_length=30)),
                ('invoice_type', models.CharField(choices=[('PO_BACKED', 'PO-Backed'), ('NON_PO', 'Non-PO'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('processing_path', models.CharField(choices=[('TWO_WAY', '2-Way Matching'), ('THREE_WAY', '3-Way Reconciliation'), ('NON_PO', 'Non-PO Validation'), ('UNRESOLVED', 'Unresolved')], db_index=True, default='UNRESOLVED', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INTAKE_IN_PROGRESS', 'Intake In Progress'), ('EXTRACTION_IN_PROGRESS', 'Extraction In Progress'), ('EXTRACTION_COMPLETED', 'Extraction Completed'), ('PATH_RESOLUTION_IN_PROGRESS', 'Path Resolution In Progress'), ('TWO_WAY_IN_PROGRESS', '2-Way Matching In Progress'), ('THREE_WAY_IN_PROGRESS', '3-Way Reconciliation In Progress'), ('NON_PO_VALIDATION_IN_PROGRESS', 'Non-PO Validation In Progress'), ('GRN_ANALYSIS_IN_PROGRESS', 'GRN Analysis In Progress'), ('EXCEPTION_ANALYSIS_IN_PROGRESS', 'Exception Analysis In Progress'), ('READY_FOR_REVIEW', 'Ready for Review'), ('IN_REVIEW', 'In Review'), ('REVIEW_COMPLETED', 'Review Completed'), ('READY_FOR_APPROVAL', 'Ready for Approval'), ('APPROVAL_IN_PROGRESS', 'Approval In Progress'), ('READY_FOR_GL_CODING', 'Ready for GL Coding'), ('READY_FOR_POSTING', 'Ready for Posting'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('FAILED', 'Failed')], db_index=True, default='NEW', max_length=50)),
                ('current_stage', models.CharField(blank=True, choices=[('INTAKE', 'Intake'), ('EXTRACTION', 'Extraction'), ('PATH_RESOLUTION', 'Path Resolution'), ('PO_RETRIEVAL', 'PO Retrieval'), ('TWO_WAY_MATCHING', '2-Way Matching'), ('THREE_WAY_MATCHING', '3-Way Matching'), ('GRN_ANALYSIS', 'GRN Analysis'), ('NON_PO_VALIDATION', 'Non-PO Validation'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary'), ('REVIEWER_COPILOT', 'Reviewer Copilot'), ('APPROVAL', 'Approval'), ('GL_CODING', 'GL Coding'), ('POSTING', 'Posting')], max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('eligible_for_posting', models.BooleanField(default=False)),
                ('duplicate_risk_flag', models.BooleanField(default=False)),
                ('assigned_role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('AP_PROCESSOR', 'AP Processor'), ('REVIEWER', 'Reviewer'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor')], max_length=30)),
                ('reconciliation_mode', models.CharField(blank=True, choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)')], max_length=20)),
                ('budget_check_status', models.CharField(blank=True, choices=[('NOT_CHECKED', 'Not Checked'), ('WITHIN_BUDGET', 'Within Budget'), ('OVER_BUDGET', 'Over Budget'), ('NO_BUDGET_DATA', 'No Budget Data')], max_length=30)),
                ('coding_status', models.CharField(blank=True, choices=[('NOT_STARTED', 'Not Started'), ('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ap_case', to='documents.invoice')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_cases', to='documents.purchaseorder')),
                ('reconciliation_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_cases', to='reconciliation.reconciliationresult')),
                ('review_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_cases', to='reviews.reviewassignment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_cases', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'AP Case',
                'verbose_name_plural': 'AP Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APCaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cases.apcase')),
            ],
            options={
                'verbose_name': 'AP Case Activity',
                'verbose_name_plural': 'AP Case Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APCaseArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('EXTRACTION_RESULT', 'Extraction Result'), ('PO_LINK', 'PO Link'), ('GRN_LINK', 'GRN Link'), ('RECONCILIATION_RESULT', 'Reconciliation Result'), ('VALIDATION_RESULT', 'Validation Result'), ('AGENT_OUTPUT', 'Agent Output'), ('REVIEW_DECISION', 'Review Decision'), ('SUPPORTING_DOCUMENT', 'Supporting Document'), ('APPROVAL_PACKET', 'Approval Packet'), ('GL_CODING_PROPOSAL', 'GL Coding Proposal')], max_length=50)),
                ('linked_object_type', models.CharField(blank=True, help_text="e.g. 'documents.Invoice', 'reconciliation.ReconciliationResult'", max_length=100)),
                ('linked_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='cases.apcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AP Case Artifact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APCaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('REVIEW', 'Review'), ('APPROVAL', 'Approval'), ('INVESTIGATION', 'Investigation'), ('CORRECTION', 'Correction')], max_length=30)),
                ('assigned_role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('AP_PROCESSOR', 'AP Processor'), ('REVIEWER', 'Reviewer'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor')], max_length=30)),
                ('queue_name', models.CharField(blank=True, max_length=100)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cases.apcase')),
            ],
            options={
                'verbose_name': 'AP Case Assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APCaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.apcase')),
            ],
            options={
                'verbose_name': 'AP Case Comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='APCaseDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_type', models.CharField(choices=[('PATH_SELECTED', 'Processing Path Selected'), ('PATH_REROUTED', 'Processing Path Rerouted'), ('PO_LINKED', 'PO Linked'), ('GRN_LINKED', 'GRN Linked'), ('MATCH_DETERMINED', 'Match Status Determined'), ('EXCEPTION_CLASSIFIED', 'Exception Classified'), ('AUTO_CLOSED', 'Auto-Closed'), ('SENT_TO_REVIEW', 'Sent to Review'), ('REVIEW_COMPLETED', 'Review Completed'), ('ESCALATED', 'Escalated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('GL_CODE_PROPOSED', 'GL Code Proposed')], max_length=50)),
                ('decision_source', models.CharField(choices=[('DETERMINISTIC', 'Deterministic'), ('POLICY', 'Policy Rule'), ('AGENT', 'Agent'), ('HUMAN', 'Human')], max_length=30)),
                ('decision_value', models.CharField(max_length=200)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='cases.apcase')),
            ],
            options={
                'verbose_name': 'AP Case Decision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APCaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(choices=[('INTAKE', 'Intake'), ('EXTRACTION', 'Extraction'), ('PATH_RESOLUTION', 'Path Resolution'), ('PO_RETRIEVAL', 'PO Retrieval'), ('TWO_WAY_MATCHING', '2-Way Matching'), ('THREE_WAY_MATCHING', '3-Way Matching'), ('GRN_ANALYSIS', 'GRN Analysis'), ('NON_PO_VALIDATION', 'Non-PO Validation'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary'), ('REVIEWER_COPILOT', 'Reviewer Copilot'), ('APPROVAL', 'Approval'), ('GL_CODING', 'GL Coding'), ('POSTING', 'Posting')], max_length=50)),
                ('stage_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('WAITING_HUMAN', 'Waiting for Human')], default='PENDING', max_length=30)),
                ('performed_by_type', models.CharField(blank=True, choices=[('SYSTEM', 'System'), ('DETERMINISTIC', 'Deterministic Engine'), ('AGENT', 'Agent'), ('HUMAN', 'Human')], max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='cases.apcase')),
                ('performed_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_stages', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'AP Case Stage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='APCaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_summary', models.TextField(blank=True, default='')),
                ('reviewer_summary', models.TextField(blank=True, default='')),
                ('finance_summary', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='cases.apcase')),
                ('generated_by_agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'AP Case Summary',
            },
        ),
        migrations.AddIndex(
            model_name='apcase',
            index=models.Index(fields=['status', 'processing_path'], name='cases_apcas_status_4fc17c_idx'),
        ),
        migrations.AddIndex(
            model_name='apcase',
            index=models.Index(fields=['priority', '-created_at'], name='cases_apcas_priorit_635cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='apcase',
            index=models.Index(fields=['assigned_to', 'status'], name='cases_apcas_assigne_c69f72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apcasestage',
            unique_together={('case', 'stage_name', 'retry_count')},
        ),
    ]
