# Generated by Django 5.2.1 on 2026-03-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apcasestage',
            name='config_snapshot_json',
            field=models.JSONField(blank=True, help_text='Config/tolerance snapshot at execution time', null=True),
        ),
        migrations.AddField(
            model_name='apcasestage',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apcasestage',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apcasestage',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='apcasestage',
            name='parent_span_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='apcasestage',
            name='span_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='apcasestage',
            name='trace_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
