# Generated by Django 5.0.14 on 2026-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_apcasestage_config_snapshot_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apcase',
            name='reconciliation_mode',
            field=models.CharField(blank=True, choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)'), ('NON_PO', 'Non-PO (No PO matching)')], max_length=20),
        ),
    ]
