# Generated by Django 5.0.14 on 2026-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_apcase_reconciliation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apcase',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('INTAKE', 'Intake'), ('EXTRACTION', 'Extraction'), ('EXTRACTION_APPROVAL', 'Extraction Approval'), ('PATH_RESOLUTION', 'Path Resolution'), ('PO_RETRIEVAL', 'PO Retrieval'), ('TWO_WAY_MATCHING', '2-Way Matching'), ('THREE_WAY_MATCHING', '3-Way Matching'), ('GRN_ANALYSIS', 'GRN Analysis'), ('NON_PO_VALIDATION', 'Non-PO Validation'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary'), ('REVIEWER_COPILOT', 'Reviewer Copilot'), ('APPROVAL', 'Approval'), ('GL_CODING', 'GL Coding'), ('POSTING', 'Posting')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apcase',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INTAKE_IN_PROGRESS', 'Intake In Progress'), ('EXTRACTION_IN_PROGRESS', 'Extraction In Progress'), ('EXTRACTION_COMPLETED', 'Extraction Completed'), ('PENDING_EXTRACTION_APPROVAL', 'Pending Extraction Approval'), ('PATH_RESOLUTION_IN_PROGRESS', 'Path Resolution In Progress'), ('TWO_WAY_IN_PROGRESS', '2-Way Matching In Progress'), ('THREE_WAY_IN_PROGRESS', '3-Way Reconciliation In Progress'), ('NON_PO_VALIDATION_IN_PROGRESS', 'Non-PO Validation In Progress'), ('GRN_ANALYSIS_IN_PROGRESS', 'GRN Analysis In Progress'), ('EXCEPTION_ANALYSIS_IN_PROGRESS', 'Exception Analysis In Progress'), ('READY_FOR_REVIEW', 'Ready for Review'), ('IN_REVIEW', 'In Review'), ('REVIEW_COMPLETED', 'Review Completed'), ('READY_FOR_APPROVAL', 'Ready for Approval'), ('APPROVAL_IN_PROGRESS', 'Approval In Progress'), ('READY_FOR_GL_CODING', 'Ready for GL Coding'), ('READY_FOR_POSTING', 'Ready for Posting'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('FAILED', 'Failed')], db_index=True, default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='apcasestage',
            name='stage_name',
            field=models.CharField(choices=[('INTAKE', 'Intake'), ('EXTRACTION', 'Extraction'), ('EXTRACTION_APPROVAL', 'Extraction Approval'), ('PATH_RESOLUTION', 'Path Resolution'), ('PO_RETRIEVAL', 'PO Retrieval'), ('TWO_WAY_MATCHING', '2-Way Matching'), ('THREE_WAY_MATCHING', '3-Way Matching'), ('GRN_ANALYSIS', 'GRN Analysis'), ('NON_PO_VALIDATION', 'Non-PO Validation'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary'), ('REVIEWER_COPILOT', 'Reviewer Copilot'), ('APPROVAL', 'Approval'), ('GL_CODING', 'GL Coding'), ('POSTING', 'Posting')], max_length=50),
        ),
    ]
