# Generated by Django 5.0.14 on 2026-04-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_apcase_current_stage_alter_apcase_status_and_more'),
        ('documents', '0009_add_tax_breakdown_vendor_tax_id_buyer_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apcase',
            name='document_upload',
            field=models.ForeignKey(blank=True, help_text='Link to the original upload; set at case creation (before extraction).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_cases', to='documents.documentupload'),
        ),
        migrations.AlterField(
            model_name='apcase',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='Linked after extraction persistence; null for pre-extraction cases.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_case', to='documents.invoice'),
        ),
    ]
