# Generated by Django 5.0.14 on 2026-04-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
        ('cases', '0006_apcase_tenant_id_apcaseactivity_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apcase',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='apcaseactivity',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='apcaseartifact',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='apcaseassignment',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='apcasecomment',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='apcasedecision',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='apcasestage',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='apcasesummary',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='apcase',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='apcaseactivity',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='apcaseartifact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='apcaseassignment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='apcasecomment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='apcasedecision',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='apcasestage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='apcasesummary',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
