# Generated by Django 5.0.14 on 2026-04-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_add_tenant_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apcase',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('AP_PROCESSOR', 'AP Processor'), ('REVIEWER', 'Reviewer'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='apcaseassignment',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('AP_PROCESSOR', 'AP Processor'), ('REVIEWER', 'Reviewer'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor')], max_length=30),
        ),
    ]
