# Generated by Django 5.0.14 on 2026-04-09 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('cases', '0008_recommendation_override_fields'),
        ('documents', '0012_add_tenant_fk'),
        ('reconciliation', '0015_receipt_availability_fields'),
        ('reviews', '0004_add_tenant_fk'),
        ('vendors', '0004_add_tenant_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apcase',
            index=models.Index(fields=['tenant', 'status'], name='idx_apcase_tenant_status'),
        ),
    ]
