# Generated by Django 5.0.14 on 2026-04-17 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('cases', '0010_absorb_reviews_app'),
        ('documents', '0014_tenant_scope_po_grn_unique'),
        ('reconciliation', '0017_alter_config_name_unique_per_tenant'),
        ('vendors', '0005_tenant_scope_po_grn_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apcase',
            name='case_number',
            field=models.CharField(db_index=True, help_text='Auto-generated case identifier, e.g. AP-000123', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='apcase',
            constraint=models.UniqueConstraint(fields=('case_number', 'tenant'), name='uq_case_number_tenant'),
        ),
    ]
