# Generated by Django 5.0.14 on 2026-04-20 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_tenant_scope_case_number_unique'),
        ('email_integration', '0003_alter_emailaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apcase',
            name='last_email_message',
            field=models.ForeignKey(blank=True, help_text='Most recent email message linked to this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_email_ap_cases', to='email_integration.emailmessage'),
        ),
        migrations.AddField(
            model_name='apcase',
            name='primary_email_thread',
            field=models.ForeignKey(blank=True, help_text='Primary inbound email thread that triggered or enriched this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_ap_cases', to='email_integration.emailthread'),
        ),
    ]
