# Generated by Django 5.2.1 on 2026-03-21 07:44
# Original migration created ExtractionApproval and ExtractionFieldCorrection.
# Those tables are now dropped by migration 0013. This file is kept as a
# no-op squash baseline to preserve the dependency chain.

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_extraction_approval'),
        ('extraction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Intentionally empty -- original CreateModel operations removed.
        # See 0013_drop_extraction_approval_tables for the DROP TABLE migration.
    ]
