# Generated by Django 5.2.1 on 2026-03-21 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_extraction_approval'),
        ('extraction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-Approved')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('confidence_at_review', models.FloatField(blank=True, null=True)),
                ('original_values_snapshot', models.JSONField(blank=True, default=dict, help_text='Invoice header + line item values as extracted (pre-correction).')),
                ('fields_corrected_count', models.PositiveIntegerField(default=0, help_text='Number of individual fields corrected by human.')),
                ('is_touchless', models.BooleanField(db_index=True, default=False, help_text='True if approved without any human field corrections.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('extraction_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='extraction.extractionresult')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_approval', to='documents.invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_approvals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Approval',
                'verbose_name_plural': 'Extraction Approvals',
                'db_table': 'extraction_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionFieldCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(help_text="'header' or 'line_item'", max_length=20)),
                ('entity_id', models.PositiveIntegerField(blank=True, help_text='PK of the InvoiceLineItem (null for header corrections).', null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('original_value', models.TextField(blank=True, default='')),
                ('corrected_value', models.TextField(blank=True, default='')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='extraction.extractionapproval')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_field_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Field Correction',
                'verbose_name_plural': 'Extraction Field Corrections',
                'db_table': 'extraction_field_correction',
                'ordering': ['approval', 'entity_type', 'field_name'],
            },
        ),
        migrations.AddIndex(
            model_name='extractionapproval',
            index=models.Index(fields=['status'], name='idx_extappr_status'),
        ),
        migrations.AddIndex(
            model_name='extractionapproval',
            index=models.Index(fields=['is_touchless'], name='idx_extappr_touchless'),
        ),
        migrations.AddIndex(
            model_name='extractionfieldcorrection',
            index=models.Index(fields=['field_name'], name='idx_extcorr_field'),
        ),
        migrations.AddIndex(
            model_name='extractionfieldcorrection',
            index=models.Index(fields=['entity_type'], name='idx_extcorr_entity'),
        ),
    ]
