# Generated by Django 5.2.1 on 2026-03-23 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0003_add_agent_run_id_to_extraction_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_credits', models.PositiveIntegerField(default=0)),
                ('reserved_credits', models.PositiveIntegerField(default=0)),
                ('monthly_limit', models.PositiveIntegerField(default=0, help_text='Maximum credits consumable per month. 0 = unlimited.')),
                ('monthly_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credit Account',
                'verbose_name_plural': 'User Credit Accounts',
                'db_table': 'extraction_user_credit_account',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ALLOCATE', 'Allocate'), ('RESERVE', 'Reserve'), ('CONSUME', 'Consume'), ('REFUND', 'Refund'), ('ADJUST', 'Adjust'), ('MONTHLY_RESET', 'Monthly Reset'), ('NEEDS_TECHNICAL_REVIEW', 'Needs Technical Review'), ('NEEDS_COMMERCIAL_REVIEW', 'Needs Commercial Review')], db_index=True, max_length=30)),
                ('credits', models.IntegerField(help_text='Positive for allocate/refund, negative for consume/adjust-down.')),
                ('balance_after', models.IntegerField()),
                ('reserved_after', models.IntegerField(default=0)),
                ('monthly_used_after', models.IntegerField(default=0)),
                ('reference_type', models.CharField(blank=True, default='', help_text='Context: upload, system, admin', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='extraction.usercreditaccount')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'db_table': 'extraction_credit_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
