# Generated by Django 5.2.1 on 2026-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0004_credit_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionresult',
            name='ocr_char_count',
            field=models.PositiveIntegerField(default=0, help_text='Characters extracted by OCR'),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='ocr_duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='OCR processing time in ms', null=True),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='ocr_page_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of pages processed by OCR'),
        ),
    ]
