# Generated by Django 5.2.1 on 2026-03-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0005_add_ocr_tracking_fields'),
        ('extraction_core', '0004_add_prompt_template_routing_rule_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionresult',
            name='extraction_run',
            field=models.ForeignKey(blank=True, help_text='Link to the governing ExtractionRun where available. Always reflects the most recent governed run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_results', to='extraction_core.extractionrun'),
        ),
    ]
