# Generated by Django 5.2.1 on 2026-03-23 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_superseded_invoice_status'),
        ('extraction', '0008_backfill_extraction_run_fk'),
        ('extraction_core', '0004_add_prompt_template_routing_rule_settings_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSourceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('LOCAL_FOLDER', 'Local Folder'), ('GOOGLE_DRIVE', 'Google Drive'), ('ONEDRIVE', 'OneDrive')], max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Source-specific config. LOCAL_FOLDER: {"folder_path": "..."} | GOOGLE_DRIVE: {"folder_id": "...", "credentials_json": "..."} | ONEDRIVE: {"folder_id": "...", "tenant_id": "...", "client_id": "...", "client_secret": "...", "folder_path": "..."}')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Source Connection',
                'verbose_name_plural': 'Bulk Source Connections',
                'db_table': 'extraction_bulk_source_connection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SCANNING', 'Scanning'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL_FAILED', 'Partial Failed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_found', models.PositiveIntegerField(default=0)),
                ('total_registered', models.PositiveIntegerField(default=0)),
                ('total_success', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('total_skipped', models.PositiveIntegerField(default=0)),
                ('total_credit_blocked', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_extraction_jobs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='extraction.bulksourceconnection')),
            ],
            options={
                'verbose_name': 'Bulk Extraction Job',
                'verbose_name_plural': 'Bulk Extraction Jobs',
                'db_table': 'extraction_bulk_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkExtractionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file_id', models.CharField(blank=True, default='', help_text='Cloud provider file ID or local file path', max_length=500)),
                ('source_name', models.CharField(max_length=500)),
                ('source_path', models.CharField(blank=True, default='', max_length=1000)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('SKIPPED', 'Skipped'), ('CREDIT_BLOCKED', 'Credit Blocked'), ('REGISTERED', 'Registered'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate'), ('UNSUPPORTED', 'Unsupported')], db_index=True, default='DISCOVERED', max_length=30)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('document_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='documents.documentupload')),
                ('extraction_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='extraction_core.extractionrun')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='extraction.bulkextractionjob')),
            ],
            options={
                'verbose_name': 'Bulk Extraction Item',
                'verbose_name_plural': 'Bulk Extraction Items',
                'db_table': 'extraction_bulk_item',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='extraction__job_id_a7c176_idx'), models.Index(fields=['source_file_id'], name='extraction__source__878bbd_idx')],
            },
        ),
    ]
