# Generated by Django 5.0.14 on 2026-03-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0009_bulk_extraction_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ALLOCATE', 'Allocate'), ('RESERVE', 'Reserve'), ('CONSUME', 'Consume'), ('REFUND', 'Refund'), ('ADJUST', 'Adjust'), ('MONTHLY_RESET', 'Monthly Reset')], db_index=True, max_length=30),
        ),
    ]
