# Generated by Django 5.0.14 on 2026-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0010_add_ocr_text_to_extraction_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionresult',
            name='langfuse_trace_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langfuse root trace ID for the extraction pipeline run', max_length=64),
        ),
    ]
