# Generated by Django 5.0.14 on 2026-03-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0010_add_ocr_text_to_extraction_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionresult',
            name='ocr_text',
            field=models.TextField(blank=True, default='', help_text='Raw OCR text sent to the LLM -- preserved for debugging missed extractions'),
        ),
    ]
