# Generated by Django 5.0.14 on 2026-04-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0011_add_langfuse_trace_id'),
        ('extraction', '0011_alter_extractionresult_ocr_text'),
    ]

    operations = [
    ]
