# Generated by Django 5.0.14 on 2026-04-08 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_add_tenant_fk'),
        ('extraction', '0014_strip_extraction_result_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-Approved')], db_index=True, default='PENDING', max_length=20)),
                ('confidence_at_review', models.FloatField(blank=True, help_text='Extraction confidence at time of review', null=True)),
                ('original_values_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of invoice values before corrections')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('fields_corrected_count', models.PositiveIntegerField(default=0)),
                ('is_touchless', models.BooleanField(default=False, help_text='True if approved without any field corrections')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('extraction_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='extraction.extractionresult')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_approval', to='documents.invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_approvals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Approval',
                'verbose_name_plural': 'Extraction Approvals',
                'db_table': 'extraction_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionFieldCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(help_text="'header' or 'line_item'", max_length=20)),
                ('entity_id', models.IntegerField(blank=True, help_text='PK of InvoiceLineItem (null for header corrections)', null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('original_value', models.TextField(blank=True, default='')),
                ('corrected_value', models.TextField(blank=True, default='')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='extraction.extractionapproval')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_field_corrections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Field Correction',
                'verbose_name_plural': 'Extraction Field Corrections',
                'db_table': 'extraction_field_correction',
                'ordering': ['-created_at'],
            },
        ),
    ]
