# Generated by Django 5.0.14 on 2026-04-09 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('extraction', '0016_extractionapproval_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkextractionjob',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Owning tenant for this bulk extraction job.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
