# Generated by Django 5.2.1 on 2026-03-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, help_text='e.g. Invoice, ReconciliationResult', max_length=100)),
                ('entity_id', models.BigIntegerField(db_index=True)),
                ('action', models.CharField(db_index=True, help_text='created, updated, status_change, etc.', max_length=50)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'db_table': 'auditlog_audit_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_entity'), models.Index(fields=['action'], name='idx_audit_action')],
            },
        ),
        migrations.CreateModel(
            name='FileProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(db_index=True, help_text='upload, extraction, validation, recon, etc.', max_length=100)),
                ('status', models.CharField(db_index=True, max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_statuses', to='documents.documentupload')),
            ],
            options={
                'verbose_name': 'File Processing Status',
                'verbose_name_plural': 'File Processing Statuses',
                'db_table': 'auditlog_file_status',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_upload', 'stage'], name='idx_filestatus_doc_stage')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(db_index=True, default='INFO', max_length=10)),
                ('source', models.CharField(db_index=True, help_text='Module or service name', max_length=100)),
                ('event', models.CharField(db_index=True, max_length=200)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('invoice_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('reconciliation_result_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('agent_run_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'db_table': 'auditlog_processing_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'event'], name='idx_proclog_src_event'), models.Index(fields=['level'], name='idx_proclog_level'), models.Index(fields=['trace_id'], name='idx_proclog_trace')],
            },
        ),
    ]
