# Generated by Django 5.2.1 on 2026-03-10 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='event_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Typed event (AuditEventType enum)', max_length=60),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='metadata_json',
            field=models.JSONField(blank=True, help_text='Additional structured context', null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='performed_by_agent',
            field=models.CharField(blank=True, default='', help_text='Agent name if action performed by an agent', max_length=100),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type'], name='idx_audit_event_type'),
        ),
    ]
