# Generated by Django 5.2.1 on 2026-03-13 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_auditevent_event_description_auditevent_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='access_granted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_primary_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_roles_snapshot_json',
            field=models.JSONField(blank=True, help_text='List of active role codes at action time', null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='agent_run_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='case_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='input_snapshot_json',
            field=models.JSONField(blank=True, help_text='Redacted input snapshot', null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='invoice_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='is_redacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='output_snapshot_json',
            field=models.JSONField(blank=True, help_text='Redacted output snapshot', null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='parent_span_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='permission_checked',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='permission_source',
            field=models.CharField(blank=True, default='', help_text='ROLE | USER_OVERRIDE_ALLOW | ADMIN_BYPASS | USER_OVERRIDE_DENY | NO_PERMISSION | USER_INACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='reason_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='reconciliation_result_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='review_assignment_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='span_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='status_after',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='status_before',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='access_granted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='actor_primary_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='case_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='endpoint_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='exception_class',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='permission_checked',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='retry_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='review_assignment_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='span_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='task_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['trace_id'], name='idx_audit_trace'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['invoice_id'], name='idx_audit_invoice'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['case_id'], name='idx_audit_case'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_primary_role'], name='idx_audit_role'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['permission_checked'], name='idx_audit_perm'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['access_granted'], name='idx_audit_access'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['task_name'], name='idx_proclog_task'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['success'], name='idx_proclog_success'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['case_id'], name='idx_proclog_case'),
        ),
    ]
