# Generated by Django 5.0.14 on 2026-04-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0004_auditevent_tenant_fileprocessingstatus_tenant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileProcessingStatus',
        ),
    ]
