# Generated by Django 5.2.1 on 2026-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Unique identifier (e.g. extraction.invoice_system, agent.po_retrieval)', max_length=120, unique=True)),
                ('name', models.CharField(help_text='Human-readable label', max_length=200)),
                ('category', models.CharField(db_index=True, help_text='Grouping category: extraction, agent, case, misc', max_length=50)),
                ('content', models.TextField(help_text='Prompt text. Use {variable} for runtime placeholders.')),
                ('description', models.TextField(blank=True, default='', help_text='Internal notes about this prompt')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'db_table': 'core_prompt_template',
                'ordering': ['category', 'slug'],
            },
        ),
    ]
