# Generated by Django 5.2.1 on 2026-03-25 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0008_add_superseded_invoice_status'),
        ('posting_core', '0002_postingrun_erp_source_metadata_json'),
        ('reconciliation', '0004_add_ap_processor_sees_all_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPReferenceCacheRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(db_index=True, max_length=500, unique=True)),
                ('resolution_type', models.CharField(choices=[('VENDOR', 'Vendor Lookup'), ('PO', 'Purchase Order Lookup'), ('GRN', 'GRN Lookup'), ('ITEM', 'Item Lookup'), ('TAX', 'Tax Code Lookup'), ('COST_CENTER', 'Cost Center Lookup'), ('DUPLICATE_INVOICE', 'Duplicate Invoice Check')], max_length=30)),
                ('connector_name', models.CharField(blank=True, default='', max_length=200)),
                ('value_json', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('source_type', models.CharField(choices=[('API', 'ERP API'), ('DB_FALLBACK', 'Database Fallback'), ('CACHE', 'Cache'), ('NONE', 'Not Resolved')], default='API', max_length=20)),
            ],
            options={
                'verbose_name': 'ERP Reference Cache Record',
                'verbose_name_plural': 'ERP Reference Cache Records',
                'db_table': 'erp_integration_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('connector_type', models.CharField(choices=[('CUSTOM', 'Custom ERP'), ('DYNAMICS', 'Microsoft Dynamics'), ('ZOHO', 'Zoho'), ('SALESFORCE', 'Salesforce')], db_index=True, default='CUSTOM', max_length=20)),
                ('base_url', models.URLField(max_length=500)),
                ('auth_config_json', models.JSONField(blank=True, default=dict, help_text='Secret references (env var names), never raw secrets')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error')], db_index=True, default='ACTIVE', max_length=20)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ERP Connection',
                'verbose_name_plural': 'ERP Connections',
                'db_table': 'erp_integration_connection',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ERPResolutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_type', models.CharField(choices=[('VENDOR', 'Vendor Lookup'), ('PO', 'Purchase Order Lookup'), ('GRN', 'GRN Lookup'), ('ITEM', 'Item Lookup'), ('TAX', 'Tax Code Lookup'), ('COST_CENTER', 'Cost Center Lookup'), ('DUPLICATE_INVOICE', 'Duplicate Invoice Check')], db_index=True, max_length=30)),
                ('lookup_key', models.CharField(db_index=True, max_length=500)),
                ('source_type', models.CharField(choices=[('API', 'ERP API'), ('DB_FALLBACK', 'Database Fallback'), ('CACHE', 'Cache'), ('NONE', 'Not Resolved')], max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('fallback_used', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('connector_name', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('freshness_timestamp', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_resolution_logs', to='documents.invoice')),
                ('related_posting_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_resolution_logs', to='posting_core.postingrun')),
                ('related_reconciliation_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_resolution_logs', to='reconciliation.reconciliationresult')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ERP Resolution Log',
                'verbose_name_plural': 'ERP Resolution Logs',
                'db_table': 'erp_integration_resolution_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolution_type', 'created_at'], name='idx_erp_reslog_type_date')],
            },
        ),
        migrations.CreateModel(
            name='ERPSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_type', models.CharField(choices=[('CREATE_INVOICE', 'Create Invoice'), ('PARK_INVOICE', 'Park Invoice'), ('GET_STATUS', 'Get Posting Status')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('UNSUPPORTED', 'Unsupported')], max_length=20)),
                ('connector_name', models.CharField(blank=True, default='', max_length=200)),
                ('request_payload_json', models.JSONField(blank=True, default=dict)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('erp_document_number', models.CharField(blank=True, default='', max_length=200)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_submission_logs', to='documents.invoice')),
                ('related_posting_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_submission_logs', to='posting_core.postingrun')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ERP Submission Log',
                'verbose_name_plural': 'ERP Submission Logs',
                'db_table': 'erp_integration_submission_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission_type', 'created_at'], name='idx_erp_sublog_type_date')],
            },
        ),
    ]
