# Generated by Django 5.2.1 on 2026-03-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpreferencecacherecord',
            name='cache_key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
