# Generated by Django 5.2.1 on 2026-03-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integration', '0002_alter_erpreferencecacherecord_cache_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpconnection',
            name='connector_type',
            field=models.CharField(choices=[('CUSTOM', 'Custom ERP'), ('SQLSERVER', 'SQL Server (Direct DB)'), ('DYNAMICS', 'Microsoft Dynamics'), ('ZOHO', 'Zoho'), ('SALESFORCE', 'Salesforce')], db_index=True, default='CUSTOM', max_length=20),
        ),
    ]
