# Generated by Django 5.2.1 on 2026-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integration', '0003_alter_erpconnection_connector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpconnection',
            name='base_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
