# Generated by Django 5.2.1 on 2026-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integration', '0004_alter_erpconnection_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpconnection',
            name='api_key_env',
            field=models.CharField(blank=True, default='', help_text='Env var name holding the API key / bearer token', max_length=200),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('BEARER', 'Bearer Token'), ('BASIC', 'Basic Auth'), ('API_KEY', 'API Key Header'), ('OAUTH2', 'OAuth 2.0')], default='BEARER', max_length=20),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='client_id_env',
            field=models.CharField(blank=True, default='', help_text='Env var name holding the OAuth client ID', max_length=200),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='client_secret_env',
            field=models.CharField(blank=True, default='', help_text='Env var name holding the OAuth client secret', max_length=200),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='connection_string_env',
            field=models.CharField(blank=True, default='', help_text='Env var name holding the ODBC connection string', max_length=200),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='database_name',
            field=models.CharField(blank=True, default='', help_text='Database name (display / reference only)', max_length=200),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='tenant_id',
            field=models.CharField(blank=True, default='', help_text='Tenant / Org ID for cloud ERP', max_length=200),
        ),
        migrations.AlterField(
            model_name='erpconnection',
            name='auth_config_json',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy JSON auth config. Prefer the typed fields below.'),
        ),
    ]
