# Generated by Django 5.2.1 on 2026-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integration', '0005_add_typed_connection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpconnection',
            name='db_driver',
            field=models.CharField(blank=True, default='ODBC Driver 17 for SQL Server', help_text='ODBC driver name', max_length=200),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='db_host',
            field=models.CharField(blank=True, default='', help_text='Database server hostname or IP', max_length=300),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='db_password_encrypted',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted database password'),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='db_port',
            field=models.PositiveIntegerField(blank=True, help_text='Database port (default 1433 for SQL Server)', null=True),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='db_username',
            field=models.CharField(blank=True, default='', help_text='Database login username', max_length=200),
        ),
        migrations.AlterField(
            model_name='erpconnection',
            name='connection_string_env',
            field=models.CharField(blank=True, default='', help_text='Env var name holding the ODBC connection string (advanced)', max_length=200),
        ),
        migrations.AlterField(
            model_name='erpconnection',
            name='database_name',
            field=models.CharField(blank=True, default='', help_text='Database name', max_length=200),
        ),
    ]
