# Generated by Django 5.2.1 on 2026-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integration', '0006_add_sql_builder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpconnection',
            name='db_trust_cert',
            field=models.BooleanField(default=False, help_text='Append TrustServerCertificate=yes and Encrypt=yes (common for on-prem servers with self-signed certs)'),
        ),
    ]
