# Generated by Django 5.2.1 on 2026-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integration', '0007_add_db_trust_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpconnection',
            name='connector_type',
            field=models.CharField(choices=[('CUSTOM', 'Custom ERP'), ('SQLSERVER', 'SQL Server (Direct DB)'), ('MYSQL', 'MySQL / MariaDB (Direct DB)'), ('DYNAMICS', 'Microsoft Dynamics'), ('ZOHO', 'Zoho'), ('SALESFORCE', 'Salesforce')], db_index=True, default='CUSTOM', max_length=20),
        ),
    ]
