# Generated by Django 5.0.14 on 2026-04-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integration', '0008_add_mysql_connector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpreferencecacherecord',
            name='source_type',
            field=models.CharField(choices=[('API', 'ERP API'), ('CACHE', 'Cache'), ('MIRROR_DB', 'Internal ERP Mirror'), ('DB_FALLBACK', 'Reference Import Snapshot'), ('MANUAL_OVERRIDE', 'Manual Override'), ('NONE', 'Not Resolved')], default='API', max_length=20),
        ),
        migrations.AlterField(
            model_name='erpresolutionlog',
            name='source_type',
            field=models.CharField(choices=[('API', 'ERP API'), ('CACHE', 'Cache'), ('MIRROR_DB', 'Internal ERP Mirror'), ('DB_FALLBACK', 'Reference Import Snapshot'), ('MANUAL_OVERRIDE', 'Manual Override'), ('NONE', 'Not Resolved')], max_length=20),
        ),
    ]
