# Generated by Django 5.0.14 on 2026-04-08 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
        ('erp_integration', '0009_alter_erpreferencecacherecord_source_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpconnection',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='erp_tenant_id',
            field=models.CharField(blank=True, default='', help_text='Tenant / Org ID for cloud ERP (e.g. Azure AD tenant ID)', max_length=200),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='erpreferencecacherecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='erpresolutionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='erpsubmissionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
