# Generated by Django 5.0.14 on 2026-04-17 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('erp_integration', '0010_remove_erpconnection_tenant_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpconnection',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='erpconnection',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='uq_erp_connection_name_tenant'),
        ),
    ]
