# Generated by Django 5.0.14 on 2026-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_integration", "0011_tenant_scope_name_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erpconnection",
            name="connector_type",
            field=models.CharField(
                choices=[
                    ("CUSTOM", "Custom ERP"),
                    ("SQLSERVER", "SQL Server (Direct DB)"),
                    ("VOUCHER_SQLSERVER", "Voucher SQL Server (Legacy ERP)"),
                    ("MYSQL", "MySQL / MariaDB (Direct DB)"),
                    ("DYNAMICS", "Microsoft Dynamics"),
                    ("ZOHO", "Zoho"),
                    ("SALESFORCE", "Salesforce"),
                ],
                db_index=True,
                default="CUSTOM",
                max_length=20,
            ),
        ),
    ]
