# Generated by Django 5.2.1 on 2026-03-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='is_service_item',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='is_stock_item',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='item_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='is_service_item',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='is_stock_item',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='item_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
