# Generated by Django 5.2.1 on 2026-03-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_reconciliation_mode_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='blob_path',
            field=models.CharField(blank=True, default='', help_text='Azure Blob Storage path (e.g. input/2026/03/42_invoice.pdf)', max_length=1000),
        ),
    ]
