# Generated by Django 5.2.1 on 2026-03-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_blob_path_to_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='blob_container',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='blob_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='blob_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='blob_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='blob_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
