# Generated by Django 5.2.1 on 2026-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_sync_blob_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='invoices/%Y/%m/'),
        ),
    ]
