# Generated by Django 5.2.1 on 2026-03-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('PO', 'Purchase Order'), ('GRN', 'Goods Receipt Note'), ('PROCUREMENT_RFQ', 'Procurement RFQ'), ('PROCUREMENT_QUOTATION', 'Procurement Quotation')], default='INVOICE', max_length=30),
        ),
    ]
