# Generated by Django 5.2.1 on 2026-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documentupload_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTION_IN_PROGRESS', 'Extraction In Progress'), ('EXTRACTED', 'Extracted'), ('VALIDATED', 'Validated'), ('INVALID', 'Invalid'), ('PENDING_APPROVAL', 'Pending Approval'), ('READY_FOR_RECON', 'Ready for Reconciliation'), ('RECONCILED', 'Reconciled'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=30),
        ),
    ]
