# Generated by Django 5.2.1 on 2026-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_extraction_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('DELIVERY_NOTE', 'Delivery Note'), ('STATEMENT', 'Statement'), ('PO', 'Purchase Order'), ('GRN', 'Goods Receipt Note'), ('PROCUREMENT_RFQ', 'Procurement RFQ'), ('PROCUREMENT_QUOTATION', 'Procurement Quotation')], default='INVOICE', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTION_IN_PROGRESS', 'Extraction In Progress'), ('EXTRACTED', 'Extracted'), ('VALIDATED', 'Validated'), ('INVALID', 'Invalid'), ('PENDING_APPROVAL', 'Pending Approval'), ('READY_FOR_RECON', 'Ready for Reconciliation'), ('RECONCILED', 'Reconciled'), ('SUPERSEDED', 'Superseded'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=30),
        ),
    ]
