# Generated by Django 5.0.14 on 2026-03-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_superseded_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_name',
            field=models.CharField(blank=True, default='', help_text='Billed-to entity as extracted from the invoice', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='raw_buyer_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='raw_due_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='raw_vendor_tax_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed tax split: {cgst, sgst, igst, vat}'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Effective tax rate as percentage (e.g. 18.0 for 18%%)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor_tax_id',
            field=models.CharField(blank=True, default='', help_text='Vendor GSTIN / VAT registration number', max_length=100),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Line-level tax rate as percentage (e.g. 18.0 for 18%%)', max_digits=7, null=True),
        ),
    ]
