# Generated by Django 5.0.14 on 2026-04-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
        ('documents', '0011_documentupload_tenant_id_goodsreceiptnote_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='grnlineitem',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
