# Generated by Django 5.0.14 on 2026-04-17 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('documents', '0013_add_compound_tenant_status_indexes'),
        ('vendors', '0004_add_tenant_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='grn_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnote',
            constraint=models.UniqueConstraint(fields=('grn_number', 'tenant'), name='uq_grn_number_tenant'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('po_number', 'tenant'), name='uq_po_number_tenant'),
        ),
    ]
