# Generated by Django 5.0.14 on 2026-04-20 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_tenant_scope_po_grn_unique'),
        ('email_integration', '0003_alter_emailaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='source_message',
            field=models.ForeignKey(blank=True, help_text='Email message that triggered this document upload when source is EMAIL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_uploads', to='email_integration.emailmessage'),
        ),
    ]
