# Generated by Django 5.2.1 on 2026-03-15 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_apcasestage_config_snapshot_json_and_more'),
        ('documents', '0005_alter_documentupload_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('actor_primary_role', models.CharField(blank=True, default='', max_length=50)),
                ('actor_roles_snapshot_json', models.JSONField(blank=True, help_text='List of active role codes at session creation', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('linked_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_sessions', to='cases.apcase')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_sessions', to='documents.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Copilot Session',
                'verbose_name_plural': 'Copilot Sessions',
                'db_table': 'copilot_session',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopilotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], db_index=True, max_length=20)),
                ('content', models.TextField(help_text='Plain-text / markdown content')),
                ('structured_payload_json', models.JSONField(blank=True, help_text='Structured response: summary, evidence, recommendation, follow_up_prompts', null=True)),
                ('consulted_agents_json', models.JSONField(blank=True, help_text='List of agent names consulted to build the response', null=True)),
                ('evidence_payload_json', models.JSONField(blank=True, help_text='Evidence cards: invoice, PO, GRN, exception details', null=True)),
                ('governance_payload_json', models.JSONField(blank=True, help_text='Governance metadata: trace_id, permissions, access decisions', null=True)),
                ('linked_case_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('span_id', models.CharField(blank=True, default='', max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='copilot.copilotsession')),
            ],
            options={
                'verbose_name': 'Copilot Message',
                'verbose_name_plural': 'Copilot Messages',
                'db_table': 'copilot_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopilotSessionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('CASE_SNAPSHOT', 'Case Snapshot'), ('EVIDENCE_CARD', 'Evidence Card'), ('RECOMMENDATION', 'Recommendation'), ('GOVERNANCE_TRACE', 'Governance Trace')], max_length=30)),
                ('linked_object_type', models.CharField(help_text='e.g. Invoice, PurchaseOrder, ReconciliationResult', max_length=100)),
                ('linked_object_id', models.BigIntegerField()),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='copilot.copilotsession')),
            ],
            options={
                'verbose_name': 'Copilot Session Artifact',
                'verbose_name_plural': 'Copilot Session Artifacts',
                'db_table': 'copilot_session_artifact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='copilotsession',
            index=models.Index(fields=['user', 'status'], name='copilot_ses_user_id_557656_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotsession',
            index=models.Index(fields=['linked_case'], name='copilot_ses_linked__9d6d61_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotsession',
            index=models.Index(fields=['is_pinned', '-last_message_at'], name='copilot_ses_is_pinn_b69007_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotmessage',
            index=models.Index(fields=['session', 'created_at'], name='copilot_mes_session_f1f253_idx'),
        ),
    ]
