# Generated by Django 5.2.1 on 2026-03-21 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extraction_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_input_formats', models.JSONField(blank=True, default=list, help_text="Accepted input date formats (e.g. ['DD/MM/YYYY', 'DD-MMM-YYYY'])")),
                ('date_output_format', models.CharField(default='YYYY-MM-DD', help_text='Target output date format (ISO 8601 recommended)', max_length=20)),
                ('decimal_separator', models.CharField(default='.', help_text='Decimal separator used in this locale', max_length=1)),
                ('thousands_separator', models.CharField(blank=True, default=',', help_text='Thousands separator used in this locale', max_length=1)),
                ('currency_symbol', models.CharField(blank=True, default='', help_text='Currency symbol to strip during normalization (e.g. ₹, AED, SAR)', max_length=10)),
                ('address_format_json', models.JSONField(blank=True, default=dict, help_text='Address normalization hints (field order, required components)')),
                ('custom_rules_json', models.JSONField(blank=True, default=dict, help_text='Additional custom normalization rules')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('jurisdiction', models.OneToOneField(help_text='Jurisdiction this normalization profile applies to', on_delete=django.db.models.deletion.CASCADE, related_name='normalization_profile', to='extraction_core.taxjurisdictionprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Normalization Profile',
                'verbose_name_plural': 'Normalization Profiles',
                'db_table': 'extraction_configs_normalization_profile',
            },
        ),
        migrations.CreateModel(
            name='TaxFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(db_index=True, help_text='Machine-readable field identifier (e.g. invoice_number, cgst_rate, supplier_gstin)', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable field label', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Description of what this field represents')),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('CURRENCY', 'Currency Amount'), ('TAX_ID', 'Tax Identification Number'), ('PERCENTAGE', 'Percentage'), ('ENUM', 'Enumeration'), ('ADDRESS', 'Address'), ('JSON', 'JSON Object')], default='STRING', help_text='Expected data type for parsing and validation', max_length=20)),
                ('category', models.CharField(choices=[('HEADER', 'Header'), ('LINE_ITEM', 'Line Item'), ('TAX', 'Tax'), ('PARTY', 'Party (Buyer/Seller)'), ('PAYMENT', 'Payment'), ('METADATA', 'Metadata')], default='HEADER', help_text='Field category for grouping', max_length=20)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether this field is required for a valid extraction')),
                ('is_tax_field', models.BooleanField(db_index=True, default=False, help_text='Whether this field is tax-specific')),
                ('validation_regex', models.CharField(blank=True, default='', help_text='Optional regex for field-level validation', max_length=500)),
                ('validation_rules_json', models.JSONField(blank=True, default=dict, help_text='Additional validation rules (e.g. min_value, max_value, allowed_values)')),
                ('normalization_rules_json', models.JSONField(blank=True, default=dict, help_text='Normalization rules (e.g. strip_chars, uppercase, date_format_target)')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names this field may appear as in OCR text or LLM output')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display/processing order within its category')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional field configuration (e.g. extraction_hint, llm_prompt_note)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('schemas', models.ManyToManyField(blank=True, help_text='Schemas this field belongs to', related_name='field_definitions', to='extraction_core.extractionschemadefinition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Field Definition',
                'verbose_name_plural': 'Tax Field Definitions',
                'db_table': 'extraction_configs_tax_field_definition',
                'ordering': ['category', 'sort_order', 'field_key'],
            },
        ),
    ]
