# Generated by Django 5.2.1 on 2026-03-21 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxJurisdictionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 or alpha-3 country code (e.g. IN, AE, SA)', max_length=3)),
                ('country_name', models.CharField(help_text='Human-readable country name', max_length=100)),
                ('tax_regime', models.CharField(db_index=True, help_text='Tax regime identifier (e.g. GST, VAT, ZATCA)', max_length=50)),
                ('regime_full_name', models.CharField(blank=True, default='', help_text='Full name of the tax regime (e.g. Goods and Services Tax)', max_length=200)),
                ('default_currency', models.CharField(help_text='ISO 4217 currency code (e.g. INR, AED, SAR)', max_length=3)),
                ('tax_id_label', models.CharField(help_text='Label for the primary tax registration number (e.g. GSTIN, TRN, VAT ID)', max_length=50)),
                ('tax_id_regex', models.CharField(blank=True, default='', help_text='Regex pattern to validate the tax registration number', max_length=500)),
                ('date_formats', models.JSONField(blank=True, default=list, help_text="Accepted date format patterns for this jurisdiction (e.g. ['DD/MM/YYYY', 'DD-MM-YYYY'])")),
                ('locale_code', models.CharField(blank=True, default='', help_text='Locale identifier for number/date parsing (e.g. en_IN, ar_SA)', max_length=10)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, help_text='Month when the fiscal year starts (1=Jan, 4=Apr for India)')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional jurisdiction-specific configuration (e.g. reverse_charge_supported, e-invoicing rules)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Jurisdiction Profile',
                'verbose_name_plural': 'Tax Jurisdiction Profiles',
                'db_table': 'extraction_core_tax_jurisdiction_profile',
                'ordering': ['country_code', 'tax_regime'],
                'unique_together': {('country_code', 'tax_regime')},
            },
        ),
        migrations.CreateModel(
            name='ExtractionSchemaDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(db_index=True, help_text='Document type this schema applies to (use DocumentType enum values)', max_length=50)),
                ('schema_version', models.CharField(default='1.0', help_text='Semantic version of the schema definition', max_length=20)),
                ('name', models.CharField(help_text='Human-readable schema name (e.g. India GST Invoice Schema v1.0)', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('header_fields_json', models.JSONField(blank=True, default=list, help_text='Ordered list of header-level field keys expected in extraction output')),
                ('line_item_fields_json', models.JSONField(blank=True, default=list, help_text='Ordered list of line-item-level field keys expected in extraction output')),
                ('tax_fields_json', models.JSONField(blank=True, default=list, help_text='Tax-specific field keys (e.g. cgst_rate, sgst_amount, vat_amount)')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional schema configuration (e.g. extraction hints, LLM prompt overrides)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('jurisdiction', models.ForeignKey(help_text='Jurisdiction this schema applies to', on_delete=django.db.models.deletion.PROTECT, related_name='schemas', to='extraction_core.taxjurisdictionprofile')),
            ],
            options={
                'verbose_name': 'Extraction Schema Definition',
                'verbose_name_plural': 'Extraction Schema Definitions',
                'db_table': 'extraction_core_extraction_schema_definition',
                'ordering': ['jurisdiction', 'document_type', '-schema_version'],
                'unique_together': {('jurisdiction', 'document_type', 'schema_version')},
            },
        ),
    ]
