# Generated by Django 5.2.1 on 2026-03-21 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_core', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityExtractionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_country_code', models.CharField(blank=True, default='', help_text='Default ISO country code for this entity', max_length=3)),
                ('default_regime_code', models.CharField(blank=True, default='', help_text='Default tax regime code for this entity (e.g. GST, VAT)', max_length=50)),
                ('default_document_language', models.CharField(blank=True, default='', help_text='ISO 639-1 language code (e.g. en, ar, hi)', max_length=10)),
                ('jurisdiction_mode', models.CharField(choices=[('AUTO', 'Auto-Detect'), ('FIXED', 'Fixed (configured)'), ('HYBRID', 'Hybrid (configured + detection fallback)')], default='AUTO', help_text='Jurisdiction resolution mode for this entity', max_length=20)),
                ('schema_override_code', models.CharField(blank=True, default='', help_text='Schema name or version pin (bypasses normal schema lookup)', max_length=100)),
                ('validation_profile_override_code', models.CharField(blank=True, default='', help_text='Validation profile code override', max_length=100)),
                ('normalization_profile_override_code', models.CharField(blank=True, default='', help_text='Normalization profile code override', max_length=100)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional entity-specific extraction configuration')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(help_text='Vendor / entity this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_profile', to='vendors.vendor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entity Extraction Profile',
                'verbose_name_plural': 'Entity Extraction Profiles',
                'db_table': 'extraction_core_entity_extraction_profile',
                'ordering': ['entity__name'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionRuntimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default', help_text='Human label for this settings profile', max_length=100)),
                ('jurisdiction_mode', models.CharField(choices=[('AUTO', 'Auto-Detect'), ('FIXED', 'Fixed (configured)'), ('HYBRID', 'Hybrid (configured + detection fallback)')], default='AUTO', help_text='How the system resolves jurisdiction (AUTO / FIXED / HYBRID)', max_length=20)),
                ('default_country_code', models.CharField(blank=True, default='', help_text='Default ISO country code when mode is FIXED or HYBRID', max_length=3)),
                ('default_regime_code', models.CharField(blank=True, default='', help_text='Default tax regime code when mode is FIXED or HYBRID (e.g. GST, VAT)', max_length=50)),
                ('enable_jurisdiction_detection', models.BooleanField(default=True, help_text='Whether auto-detection is enabled (always True for AUTO, configurable for HYBRID)')),
                ('allow_manual_override', models.BooleanField(default=True, help_text='Whether document-level overrides are permitted')),
                ('confidence_threshold_for_detection', models.FloatField(default=0.7, help_text='Minimum detection confidence to accept auto-detected jurisdiction (0.0–1.0)')),
                ('fallback_to_detection_on_schema_miss', models.BooleanField(default=True, help_text='In FIXED/HYBRID mode, fall back to detection if no schema exists for configured jurisdiction')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional runtime configuration')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Runtime Settings',
                'verbose_name_plural': 'Extraction Runtime Settings',
                'db_table': 'extraction_core_runtime_settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
