# Generated by Django 5.2.1 on 2026-03-22 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_core', '0003_add_extraction_run_pipeline_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='analytics_enabled',
            field=models.BooleanField(default=True, help_text='Whether analytics snapshot generation is enabled'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='auto_approval_enabled',
            field=models.BooleanField(default=False, help_text='Whether auto-approval is enabled for high-confidence extractions'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='auto_approval_threshold',
            field=models.FloatField(default=0.95, help_text='Minimum confidence for auto-approval (0.0–1.0)'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='contract_lookup_enabled',
            field=models.BooleanField(default=False, help_text='Whether contract lookup enrichment is enabled'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='correction_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Whether correction tracking for learning is enabled'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='llm_extraction_enabled',
            field=models.BooleanField(default=True, help_text='Whether LLM-based extraction is enabled'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='max_pages',
            field=models.PositiveSmallIntegerField(default=50, help_text='Maximum pages to process per document'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='multi_document_split_enabled',
            field=models.BooleanField(default=False, help_text='Whether multi-document splitting is enabled'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='ocr_enabled',
            field=models.BooleanField(default=True, help_text='Whether OCR processing is enabled'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='po_lookup_enabled',
            field=models.BooleanField(default=True, help_text='Whether PO lookup enrichment is enabled'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of extraction retries on failure'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='review_confidence_threshold',
            field=models.FloatField(default=0.7, help_text='Below this confidence, extraction is routed for review (0.0–1.0)'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Maximum seconds per extraction run'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='vendor_fuzzy_threshold',
            field=models.FloatField(default=0.8, help_text='Minimum fuzzy match score for vendor matching (0.0–1.0)'),
        ),
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='vendor_matching_enabled',
            field=models.BooleanField(default=True, help_text='Whether vendor matching enrichment is enabled'),
        ),
        migrations.CreateModel(
            name='ReviewRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human-readable rule name', max_length=200)),
                ('rule_code', models.CharField(db_index=True, help_text='Machine-readable rule identifier', max_length=100, unique=True)),
                ('condition_type', models.CharField(help_text='Trigger condition: low_confidence, tax_issues, vendor_mismatch, schema_missing, jurisdiction_mismatch, duplicate_suspicion, unsupported_document_type', max_length=50)),
                ('condition_config_json', models.JSONField(blank=True, default=dict, help_text='Condition parameters (e.g. threshold values)')),
                ('target_queue', models.CharField(choices=[('AP_REVIEW', 'AP Review'), ('TAX_REVIEW', 'Tax Review'), ('MASTER_DATA_REVIEW', 'Master Data Review'), ('EXCEPTION_OPS', 'Exception Ops'), ('COMPLIANCE', 'Compliance')], help_text='Target review queue', max_length=30)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = higher priority. Rules evaluated in priority order.')),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable explanation of what this rule does')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Routing Rule',
                'verbose_name_plural': 'Review Routing Rules',
                'db_table': 'extraction_core_review_routing_rule',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_code', models.CharField(db_index=True, help_text='Logical prompt identifier (e.g. extraction_core_v2)', max_length=120)),
                ('prompt_category', models.CharField(db_index=True, default='extraction', help_text='Category: extraction, enrichment, validation, classification', max_length=50)),
                ('country_code', models.CharField(blank=True, db_index=True, default='', help_text='ISO country code scope (blank = global)', max_length=3)),
                ('regime_code', models.CharField(blank=True, default='', help_text='Tax regime scope (blank = all regimes)', max_length=50)),
                ('document_type', models.CharField(blank=True, default='', help_text='Document type scope (blank = all types)', max_length=50)),
                ('schema_code', models.CharField(blank=True, default='', help_text='Schema name scope (blank = all schemas)', max_length=200)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number (auto-incremented on clone)')),
                ('status', models.CharField(db_index=True, default='DRAFT', help_text='DRAFT / ACTIVE / INACTIVE', max_length=20)),
                ('prompt_text', models.TextField(help_text='Full prompt text. Supports {variable} placeholders.')),
                ('variables_json', models.JSONField(blank=True, default=list, help_text='List of expected variables in prompt_text')),
                ('effective_from', models.DateTimeField(blank=True, help_text='When this prompt version becomes effective', null=True)),
                ('effective_to', models.DateTimeField(blank=True, help_text='When this prompt version expires', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Prompt Template',
                'verbose_name_plural': 'Extraction Prompt Templates',
                'db_table': 'extraction_core_extraction_prompt_template',
                'ordering': ['prompt_code', '-version'],
                'indexes': [models.Index(fields=['prompt_code', 'country_code', 'document_type', 'status'], name='extraction__prompt__5c529a_idx')],
            },
        ),
    ]
