# Generated by Django 5.0.14 on 2026-04-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_core', '0004_add_prompt_template_routing_rule_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionrun',
            name='classification_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='jurisdiction_signals_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='jurisdiction_warning',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
