# Generated by Django 5.0.14 on 2026-04-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_core', '0006_drop_extraction_documents_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionOCRText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('ocr_char_count', models.PositiveIntegerField(default=0)),
                ('ocr_page_count', models.PositiveSmallIntegerField(default=0)),
                ('ocr_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_text_record', to='extraction_core.extractionrun')),
            ],
            options={
                'db_table': 'extraction_core_ocr_text',
            },
        ),
    ]
