# Generated by Django 5.0.14 on 2026-04-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
        ('extraction_core', '0007_add_extraction_ocr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionapprovalrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='extractioncorrection',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='extractionevidence',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='extractionfieldvalue',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='extractionissue',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='extractionlineitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
