# Generated by Django 5.0.14 on 2026-04-30 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_system_export_field_mapping_permission'),
        ('extraction_core', '0009_add_document_upload_to_extraction_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionruntimesettings',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant/company this runtime settings profile belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runtime_settings', to='accounts.companyprofile'),
        ),
        migrations.AddConstraint(
            model_name='extractionruntimesettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant',), name='uniq_active_extraction_runtime_per_tenant'),
        ),
    ]
