# Generated by Django 5.2.1 on 2026-03-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('INVOICE_UNDERSTANDING', 'Invoice Understanding'), ('PO_RETRIEVAL', 'PO Retrieval'), ('GRN_RETRIEVAL', 'GRN Retrieval'), ('RECONCILIATION_ASSIST', 'Reconciliation Assist'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('llm_model', models.CharField(blank=True, default='', max_length=100)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('config_json', models.JSONField(blank=True, help_text='Agent-specific configuration', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Definition',
                'verbose_name_plural': 'Agent Definitions',
                'db_table': 'agents_definition',
                'ordering': ['agent_type'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('INVOICE_UNDERSTANDING', 'Invoice Understanding'), ('PO_RETRIEVAL', 'PO Retrieval'), ('GRN_RETRIEVAL', 'GRN Retrieval'), ('RECONCILIATION_ASSIST', 'Reconciliation Assist'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20)),
                ('input_payload', models.JSONField(blank=True, null=True)),
                ('output_payload', models.JSONField(blank=True, null=True)),
                ('summarized_reasoning', models.TextField(blank=True, default='', help_text='Enterprise-safe reasoning summary')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('llm_model_used', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agents.agentdefinition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('handed_off_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_off_from', to='agents.agentrun')),
                ('reconciliation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='reconciliation.reconciliationresult')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'db_table': 'agents_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_type', models.CharField(choices=[('AUTO_CLOSE', 'Auto Close'), ('SEND_TO_AP_REVIEW', 'Send to AP Review'), ('SEND_TO_PROCUREMENT', 'Send to Procurement'), ('SEND_TO_VENDOR_CLARIFICATION', 'Send to Vendor Clarification'), ('REPROCESS_EXTRACTION', 'Reprocess Extraction'), ('ESCALATE_TO_MANAGER', 'Escalate to Manager')], db_index=True, max_length=40)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('accepted', models.BooleanField(help_text='null=pending, True=accepted, False=rejected', null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reconciliation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_recommendations', to='reconciliation.reconciliationresult')),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Agent Recommendation',
                'verbose_name_plural': 'Agent Recommendations',
                'db_table': 'agents_recommendation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('message_index', models.PositiveIntegerField(default=0)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Agent Message',
                'verbose_name_plural': 'Agent Messages',
                'db_table': 'agents_message',
                'ordering': ['agent_run', 'message_index'],
            },
        ),
        migrations.CreateModel(
            name='AgentEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('reason', models.TextField()),
                ('suggested_assignee_role', models.CharField(blank=True, default='', max_length=50)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('reconciliation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_escalations', to='reconciliation.reconciliationresult')),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Agent Escalation',
                'verbose_name_plural': 'Agent Escalations',
                'db_table': 'agents_escalation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('action', models.CharField(max_length=200)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Agent Step',
                'verbose_name_plural': 'Agent Steps',
                'db_table': 'agents_step',
                'ordering': ['agent_run', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(max_length=500)),
                ('rationale', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence_refs', models.JSONField(blank=True, help_text='References to data that support the decision', null=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Decision Log',
                'verbose_name_plural': 'Decision Logs',
                'db_table': 'agents_decision_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent_type'], name='idx_agentrun_type'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status'], name='idx_agentrun_status'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['reconciliation_result'], name='idx_agentrun_result'),
        ),
        migrations.AddIndex(
            model_name='agentrecommendation',
            index=models.Index(fields=['recommendation_type'], name='idx_agentrec_type'),
        ),
        migrations.AddIndex(
            model_name='agentrecommendation',
            index=models.Index(fields=['reconciliation_result'], name='idx_agentrec_result'),
        ),
    ]
