# Generated by Django 5.2.1 on 2026-03-10 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('documents', '0001_initial'),
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrecommendation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrecommendation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_recommendations', to='documents.invoice'),
        ),
        migrations.AddField(
            model_name='agentrecommendation',
            name='recommended_action',
            field=models.CharField(blank=True, default='', help_text='Specific action description', max_length=200),
        ),
        migrations.AddIndex(
            model_name='agentrecommendation',
            index=models.Index(fields=['invoice'], name='idx_agentrec_invoice'),
        ),
    ]
