# Generated by Django 5.2.1 on 2026-03-13 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_make_reconciliation_result_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='actor_user_id',
            field=models.PositiveIntegerField(blank=True, help_text='User who triggered agent, if user-initiated', null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='cost_estimate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='invocation_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='permission_checked',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='span_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='actor_primary_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='actor_user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='authorization_snapshot_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='case_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='config_snapshot_json',
            field=models.JSONField(blank=True, help_text='Config/tolerance values at decision time', null=True),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='decision_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='E.g. path_selected, mode_resolved, match_determined, auto_closed', max_length=100),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='deterministic_flag',
            field=models.BooleanField(default=False, help_text='True if rule-based, False if LLM-generated'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='invoice_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='permission_checked',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='policy_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='policy_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='prompt_template_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='recommendation_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='reconciliation_result_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='rule_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='rule_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='span_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='decisionlog',
            name='agent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='agents.agentrun'),
        ),
    ]
