# Generated by Django 5.2.1 on 2026-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentrun_actor_user_id_agentrun_cost_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='access_granted',
            field=models.BooleanField(blank=True, help_text='Whether guardrail granted access', null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='actor_primary_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='actor_roles_snapshot_json',
            field=models.JSONField(blank=True, help_text='Role codes at execution time', null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='permission_source',
            field=models.CharField(blank=True, default='', help_text='ROLE | SYSTEM_AGENT | USER | ADMIN_BYPASS', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='agent_type',
            field=models.CharField(choices=[('INVOICE_EXTRACTION', 'Invoice Extraction'), ('INVOICE_UNDERSTANDING', 'Invoice Understanding'), ('PO_RETRIEVAL', 'PO Retrieval'), ('GRN_RETRIEVAL', 'GRN Retrieval'), ('RECONCILIATION_ASSIST', 'Reconciliation Assist'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='agent_type',
            field=models.CharField(choices=[('INVOICE_EXTRACTION', 'Invoice Extraction'), ('INVOICE_UNDERSTANDING', 'Invoice Understanding'), ('PO_RETRIEVAL', 'PO Retrieval'), ('GRN_RETRIEVAL', 'GRN Retrieval'), ('RECONCILIATION_ASSIST', 'Reconciliation Assist'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary')], db_index=True, max_length=40),
        ),
    ]
