# Generated by Django 5.2.1 on 2026-03-26 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_add_agentrun_rbac_fields'),
        ('reconciliation', '0004_add_ap_processor_sees_all_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentOrchestrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial (some agents failed)'), ('FAILED', 'Failed')], db_index=True, default='PLANNED', max_length=20)),
                ('plan_source', models.CharField(blank=True, default='', help_text='deterministic or llm', max_length=20)),
                ('plan_confidence', models.FloatField(blank=True, null=True)),
                ('planned_agents', models.JSONField(blank=True, help_text='Ordered list of agent types the planner chose', null=True)),
                ('executed_agents', models.JSONField(blank=True, help_text='Agent types actually executed (updated as each agent completes)', null=True)),
                ('final_recommendation', models.CharField(blank=True, default='', max_length=60)),
                ('final_confidence', models.FloatField(blank=True, null=True)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('actor_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reconciliation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_runs', to='reconciliation.reconciliationresult')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orchestration Run',
                'verbose_name_plural': 'Orchestration Runs',
                'db_table': 'agents_orchestration_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reconciliation_result', 'status'], name='idx_orchrun_result_status')],
            },
        ),
    ]
