# Generated by Django 5.2.1 on 2026-03-26 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_add_orchestration_run'),
        ('documents', '0008_add_superseded_invoice_status'),
        ('reconciliation', '0004_add_ap_processor_sees_all_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agentrecommendation',
            constraint=models.UniqueConstraint(fields=('reconciliation_result', 'recommendation_type', 'agent_run'), name='uq_rec_result_type_run'),
        ),
    ]
