# Generated by Django 5.0.14 on 2026-03-28 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentdefinition_catalog_fields'),
        ('documents', '0009_add_tax_breakdown_vendor_tax_id_buyer_due_date'),
        ('reconciliation', '0004_add_ap_processor_sees_all_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='document_upload',
            field=models.ForeignKey(blank=True, help_text='Upload that triggered this run (populated for INVOICE_EXTRACTION runs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='documents.documentupload'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['document_upload'], name='idx_agentrun_upload'),
        ),
    ]
