# Generated by Django 5.0.14 on 2026-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentrun_document_upload_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdefinition',
            name='agent_type',
            field=models.CharField(choices=[('INVOICE_EXTRACTION', 'Invoice Extraction'), ('INVOICE_UNDERSTANDING', 'Invoice Understanding'), ('PO_RETRIEVAL', 'PO Retrieval'), ('GRN_RETRIEVAL', 'GRN Retrieval'), ('RECONCILIATION_ASSIST', 'Reconciliation Assist'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary'), ('SYSTEM_REVIEW_ROUTING', 'System Review Routing'), ('SYSTEM_CASE_SUMMARY', 'System Case Summary'), ('SYSTEM_BULK_EXTRACTION_INTAKE', 'System Bulk Extraction Intake'), ('SYSTEM_CASE_INTAKE', 'System Case Intake'), ('SYSTEM_POSTING_PREPARATION', 'System Posting Preparation')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='agent_type',
            field=models.CharField(choices=[('INVOICE_EXTRACTION', 'Invoice Extraction'), ('INVOICE_UNDERSTANDING', 'Invoice Understanding'), ('PO_RETRIEVAL', 'PO Retrieval'), ('GRN_RETRIEVAL', 'GRN Retrieval'), ('RECONCILIATION_ASSIST', 'Reconciliation Assist'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary'), ('SYSTEM_REVIEW_ROUTING', 'System Review Routing'), ('SYSTEM_CASE_SUMMARY', 'System Case Summary'), ('SYSTEM_BULK_EXTRACTION_INTAKE', 'System Bulk Extraction Intake'), ('SYSTEM_CASE_INTAKE', 'System Case Intake'), ('SYSTEM_POSTING_PREPARATION', 'System Posting Preparation')], db_index=True, max_length=40),
        ),
    ]
