# Generated by Django 5.0.14 on 2026-04-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
        ('agents', '0011_agentescalation_tenant_id_agentmessage_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentescalation',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='agentmessage',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='agentorchestrationrun',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='agentrecommendation',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='agentrun',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='agentstep',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='decisionlog',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='agentescalation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='agentorchestrationrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='agentrecommendation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
