# Generated by Django 5.0.14 on 2026-04-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_add_tenant_fk'),
        ('cases', '0008_recommendation_override_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrecommendation',
            name='overridden_by_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_recommendations', to='cases.apcasedecision'),
        ),
        migrations.AddField(
            model_name='agentrecommendation',
            name='override_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
