# Generated by Django 5.0.14 on 2026-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_recommendation_override_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='actual_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='cost_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='LLMCostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(help_text='LLM deployment/model name, e.g. gpt-4o', max_length=100)),
                ('input_cost_per_1k_tokens', models.DecimalField(decimal_places=6, max_digits=10)),
                ('output_cost_per_1k_tokens', models.DecimalField(decimal_places=6, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'LLM Cost Rate',
                'verbose_name_plural': 'LLM Cost Rates',
                'db_table': 'agents_llm_cost_rate',
                'ordering': ['-effective_from'],
                'unique_together': {('model_name', 'effective_from')},
            },
        ),
    ]
