# Generated by Django 5.0.14 on 2026-04-09 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('agents', '0014_agentrun_cost_and_llm_rate'),
        ('documents', '0012_add_tenant_fk'),
        ('reconciliation', '0015_receipt_availability_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['tenant', 'status'], name='idx_agentrun_tenant_status'),
        ),
    ]
