# Generated by Django 5.0.14 on 2026-04-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_add_compound_tenant_status_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='parent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_runs', to='agents.agentrun'),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='agent_type',
            field=models.CharField(choices=[('INVOICE_EXTRACTION', 'Invoice Extraction'), ('INVOICE_UNDERSTANDING', 'Invoice Understanding'), ('PO_RETRIEVAL', 'PO Retrieval'), ('GRN_RETRIEVAL', 'GRN Retrieval'), ('RECONCILIATION_ASSIST', 'Reconciliation Assist'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('COMPLIANCE_AGENT', 'Compliance Agent'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary'), ('SYSTEM_REVIEW_ROUTING', 'System Review Routing'), ('SYSTEM_CASE_SUMMARY', 'System Case Summary'), ('SYSTEM_BULK_EXTRACTION_INTAKE', 'System Bulk Extraction Intake'), ('SYSTEM_CASE_INTAKE', 'System Case Intake'), ('SYSTEM_POSTING_PREPARATION', 'System Posting Preparation'), ('SUPERVISOR', 'Supervisor')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='agent_type',
            field=models.CharField(choices=[('INVOICE_EXTRACTION', 'Invoice Extraction'), ('INVOICE_UNDERSTANDING', 'Invoice Understanding'), ('PO_RETRIEVAL', 'PO Retrieval'), ('GRN_RETRIEVAL', 'GRN Retrieval'), ('RECONCILIATION_ASSIST', 'Reconciliation Assist'), ('EXCEPTION_ANALYSIS', 'Exception Analysis'), ('COMPLIANCE_AGENT', 'Compliance Agent'), ('REVIEW_ROUTING', 'Review Routing'), ('CASE_SUMMARY', 'Case Summary'), ('SYSTEM_REVIEW_ROUTING', 'System Review Routing'), ('SYSTEM_CASE_SUMMARY', 'System Case Summary'), ('SYSTEM_BULK_EXTRACTION_INTAKE', 'System Bulk Extraction Intake'), ('SYSTEM_CASE_INTAKE', 'System Case Intake'), ('SYSTEM_POSTING_PREPARATION', 'System Posting Preparation'), ('SUPERVISOR', 'Supervisor')], db_index=True, max_length=40),
        ),
    ]
