# Generated by Django 5.0.14 on 2026-04-24 12:00

from django.db import migrations, models


def create_system_export_field_mapping_definition(apps, schema_editor):
    AgentDefinition = apps.get_model("agents", "AgentDefinition")
    AgentDefinition.objects.update_or_create(
        agent_type="SYSTEM_EXPORT_FIELD_MAPPING",
        defaults={
            "name": "System Export Field Mapping",
            "description": "Deterministic export field mapping orchestration with optional unresolved-field AI fallback.",
            "enabled": True,
            "llm_model": "deterministic",
            "system_prompt": "",
            "max_retries": 0,
            "timeout_seconds": 60,
            "requires_tool_grounding": False,
            "min_tool_calls": 0,
            "lifecycle_status": "active",
            "owner_team": "AP Automation",
            "capability_tags": ["export", "mapping", "deterministic"],
            "domain_tags": ["erp", "extraction", "export"],
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0017_alter_agentdefinition_agent_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentdefinition",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("INVOICE_EXTRACTION", "Invoice Extraction"),
                    ("INVOICE_UNDERSTANDING", "Invoice Understanding"),
                    ("PO_RETRIEVAL", "PO Retrieval"),
                    ("GRN_RETRIEVAL", "GRN Retrieval"),
                    ("RECONCILIATION_ASSIST", "Reconciliation Assist"),
                    ("EXCEPTION_ANALYSIS", "Exception Analysis"),
                    ("COMPLIANCE_AGENT", "Compliance Agent"),
                    ("REVIEW_ROUTING", "Review Routing"),
                    ("CASE_SUMMARY", "Case Summary"),
                    ("SYSTEM_REVIEW_ROUTING", "System Review Routing"),
                    ("SYSTEM_CASE_SUMMARY", "System Case Summary"),
                    ("SYSTEM_BULK_EXTRACTION_INTAKE", "System Bulk Extraction Intake"),
                    ("SYSTEM_CASE_INTAKE", "System Case Intake"),
                    ("SYSTEM_POSTING_PREPARATION", "System Posting Preparation"),
                    ("SYSTEM_EXPORT_FIELD_MAPPING", "System Export Field Mapping"),
                    ("SUPERVISOR", "Supervisor"),
                    ("PROCUREMENT_RECOMMENDATION", "Procurement Recommendation"),
                    ("PROCUREMENT_VALIDATION", "Procurement Validation"),
                    ("PROCUREMENT_COMPLIANCE", "Procurement Compliance"),
                    ("PROCUREMENT_MARKET_INTELLIGENCE", "Procurement Market Intelligence"),
                    ("PROCUREMENT_REASON_SUMMARY", "Procurement Reason Summary"),
                    ("PROCUREMENT_AZURE_DI_EXTRACTION", "Procurement Azure DI Extraction"),
                    ("PROCUREMENT_FORM_FILLING", "Procurement Form Filling"),
                    ("PROCUREMENT_RFQ_GENERATOR", "Procurement RFQ Generator"),
                    ("PLATFORM_REASONING_PLANNER", "Platform Reasoning Planner"),
                ],
                max_length=40,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("INVOICE_EXTRACTION", "Invoice Extraction"),
                    ("INVOICE_UNDERSTANDING", "Invoice Understanding"),
                    ("PO_RETRIEVAL", "PO Retrieval"),
                    ("GRN_RETRIEVAL", "GRN Retrieval"),
                    ("RECONCILIATION_ASSIST", "Reconciliation Assist"),
                    ("EXCEPTION_ANALYSIS", "Exception Analysis"),
                    ("COMPLIANCE_AGENT", "Compliance Agent"),
                    ("REVIEW_ROUTING", "Review Routing"),
                    ("CASE_SUMMARY", "Case Summary"),
                    ("SYSTEM_REVIEW_ROUTING", "System Review Routing"),
                    ("SYSTEM_CASE_SUMMARY", "System Case Summary"),
                    ("SYSTEM_BULK_EXTRACTION_INTAKE", "System Bulk Extraction Intake"),
                    ("SYSTEM_CASE_INTAKE", "System Case Intake"),
                    ("SYSTEM_POSTING_PREPARATION", "System Posting Preparation"),
                    ("SYSTEM_EXPORT_FIELD_MAPPING", "System Export Field Mapping"),
                    ("SUPERVISOR", "Supervisor"),
                    ("PROCUREMENT_RECOMMENDATION", "Procurement Recommendation"),
                    ("PROCUREMENT_VALIDATION", "Procurement Validation"),
                    ("PROCUREMENT_COMPLIANCE", "Procurement Compliance"),
                    ("PROCUREMENT_MARKET_INTELLIGENCE", "Procurement Market Intelligence"),
                    ("PROCUREMENT_REASON_SUMMARY", "Procurement Reason Summary"),
                    ("PROCUREMENT_AZURE_DI_EXTRACTION", "Procurement Azure DI Extraction"),
                    ("PROCUREMENT_FORM_FILLING", "Procurement Form Filling"),
                    ("PROCUREMENT_RFQ_GENERATOR", "Procurement RFQ Generator"),
                    ("PLATFORM_REASONING_PLANNER", "Platform Reasoning Planner"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.RunPython(create_system_export_field_mapping_definition, migrations.RunPython.noop),
    ]
