# Generated by Django 5.2.1 on 2026-03-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0008_add_superseded_invoice_status'),
        ('extraction', '0009_bulk_extraction_intake'),
        ('extraction_core', '0004_add_prompt_template_routing_rule_settings_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_READY', 'Not Ready'), ('READY_FOR_POSTING', 'Ready for Posting'), ('MAPPING_IN_PROGRESS', 'Mapping In Progress'), ('MAPPING_REVIEW_REQUIRED', 'Mapping Review Required'), ('READY_TO_SUBMIT', 'Ready to Submit'), ('SUBMISSION_IN_PROGRESS', 'Submission In Progress'), ('POSTED', 'Posted'), ('POST_FAILED', 'Post Failed'), ('REJECTED', 'Rejected'), ('RETRY_PENDING', 'Retry Pending'), ('SKIPPED', 'Skipped')], db_index=True, default='NOT_READY', max_length=30)),
                ('stage', models.CharField(blank=True, choices=[('ELIGIBILITY_CHECK', 'Eligibility Check'), ('SNAPSHOT_BUILD', 'Snapshot Build'), ('REFERENCE_RESOLUTION', 'Reference Resolution'), ('MAPPING', 'Mapping'), ('VALIDATION', 'Validation'), ('REVIEW_ROUTING', 'Review Routing'), ('PAYLOAD_BUILD', 'Payload Build'), ('SUBMISSION', 'Submission'), ('FINALIZATION', 'Finalization')], default='', max_length=30)),
                ('posting_confidence', models.FloatField(blank=True, null=True)),
                ('review_queue', models.CharField(blank=True, choices=[('ITEM_MAPPING_REVIEW', 'Item Mapping Review'), ('VENDOR_MAPPING_REVIEW', 'Vendor Mapping Review'), ('TAX_REVIEW', 'Tax Review'), ('COST_CENTER_REVIEW', 'Cost Center Review'), ('PO_REVIEW', 'PO Review'), ('POSTING_OPS', 'Posting Ops')], default='', max_length=30)),
                ('is_touchless', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('mapping_summary_json', models.JSONField(blank=True, default=dict)),
                ('payload_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('posting_snapshot_batch_refs_json', models.JSONField(blank=True, default=dict)),
                ('erp_document_number', models.CharField(blank=True, default='', max_length=100)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=50)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('extraction_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='extraction.extractionresult')),
                ('extraction_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='extraction_core.extractionrun')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='documents.invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Posting',
                'verbose_name_plural': 'Invoice Postings',
                'db_table': 'posting_invoice_posting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePostingFieldCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(help_text='header, line_item, or mapping', max_length=20)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('original_value', models.TextField(blank=True, default='')),
                ('corrected_value', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_corrections', to=settings.AUTH_USER_MODEL)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_corrections', to='posting.invoiceposting')),
            ],
            options={
                'verbose_name': 'Posting Field Correction',
                'verbose_name_plural': 'Posting Field Corrections',
                'db_table': 'posting_field_correction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoiceposting',
            index=models.Index(fields=['status'], name='idx_posting_status'),
        ),
        migrations.AddIndex(
            model_name='invoiceposting',
            index=models.Index(fields=['status', 'created_at'], name='idx_posting_status_date'),
        ),
    ]
