# Generated by Django 5.0.14 on 2026-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceposting',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='invoicepostingfieldcorrection',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
    ]
