# Generated by Django 5.0.14 on 2026-04-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
        ('posting', '0002_invoiceposting_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceposting',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='invoicepostingfieldcorrection',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='invoiceposting',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='invoicepostingfieldcorrection',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
