"""
CaseSummaryService — builds and refreshes APCaseSummary.
"""

import logging

from apps.cases.models import APCase, APCaseSummary

logger = logging.getLogger(__name__)


class CaseSummaryService:

    @staticmethod
    def build_summary(case: APCase) -> APCaseSummary:
        """
        Build or update a deterministic summary for the case.

        This produces a structured summary from case data. For a narrative summary
        generated by the Case Summary Agent, see the agent's output which populates
        the same APCaseSummary record.
        """
        invoice = case.invoice
        parts = []

        # Invoice facts
        parts.append(
            f"Invoice {invoice.invoice_number} from {invoice.vendor.name if invoice.vendor else 'Unknown'} "
            f"for {invoice.currency} {invoice.total_amount or 0:,.2f}"
        )

        # Path
        parts.append(f"Processing path: {case.get_processing_path_display()}")

        # Reconciliation result
        if case.reconciliation_result:
            result = case.reconciliation_result
            parts.append(f"Match status: {result.get_match_status_display()}")
            exc_count = result.exceptions.count()
            if exc_count:
                parts.append(f"Exceptions: {exc_count}")

        # Validation result (non-PO)
        validation_artifact = case.artifacts.filter(artifact_type="VALIDATION_RESULT").last()
        if validation_artifact:
            payload = validation_artifact.payload
            parts.append(f"Non-PO validation: {payload.get('overall_status', 'N/A')}")
            issues = payload.get("issues", [])
            if issues:
                parts.append(f"Issues: {', '.join(issues[:3])}")

        # Current status
        parts.append(f"Status: {case.get_status_display()}")

        summary_text = ". ".join(parts)

        summary, _ = APCaseSummary.objects.update_or_create(
            case=case,
            defaults={
                "latest_summary": summary_text,
            },
        )
        return summary
