# Generated by Django 5.2.1 on 2026-03-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity_tolerance_pct', models.FloatField(default=2.0)),
                ('price_tolerance_pct', models.FloatField(default=1.0)),
                ('amount_tolerance_pct', models.FloatField(default=1.0)),
                ('auto_close_on_match', models.BooleanField(default=True)),
                ('enable_agents', models.BooleanField(default=True)),
                ('extraction_confidence_threshold', models.FloatField(default=0.75)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Config',
                'verbose_name_plural': 'Reconciliation Configs',
                'db_table': 'reconciliation_config',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched'), ('PARTIAL_MATCH', 'Partial Match'), ('UNMATCHED', 'Unmatched'), ('ERROR', 'Error'), ('REQUIRES_REVIEW', 'Requires Review')], db_index=True, max_length=30)),
                ('requires_review', models.BooleanField(db_index=True, default=False)),
                ('vendor_match', models.BooleanField(null=True)),
                ('currency_match', models.BooleanField(null=True)),
                ('po_total_match', models.BooleanField(null=True)),
                ('invoice_total_vs_po', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_amount_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_amount_difference_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grn_available', models.BooleanField(default=False)),
                ('grn_fully_received', models.BooleanField(null=True)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('deterministic_confidence', models.FloatField(blank=True, help_text='Computed header confidence 0-1', null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_results', to='documents.invoice')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_results', to='documents.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Result',
                'verbose_name_plural': 'Reconciliation Results',
                'db_table': 'reconciliation_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResultLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched'), ('PARTIAL_MATCH', 'Partial Match'), ('UNMATCHED', 'Unmatched'), ('ERROR', 'Error'), ('REQUIRES_REVIEW', 'Requires Review')], max_length=30)),
                ('qty_invoice', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('qty_po', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('qty_received', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('qty_difference', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('qty_within_tolerance', models.BooleanField(null=True)),
                ('price_invoice', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('price_po', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('price_difference', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('price_within_tolerance', models.BooleanField(null=True)),
                ('amount_invoice', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_po', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_within_tolerance', models.BooleanField(null=True)),
                ('tax_invoice', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_po', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('description_similarity', models.FloatField(blank=True, help_text='0-100 fuzzy score', null=True)),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.invoicelineitem')),
                ('po_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.purchaseorderlineitem')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_results', to='reconciliation.reconciliationresult')),
            ],
            options={
                'verbose_name': 'Reconciliation Result Line',
                'verbose_name_plural': 'Reconciliation Result Lines',
                'db_table': 'reconciliation_result_line',
                'ordering': ['result', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(choices=[('PO_NOT_FOUND', 'PO Not Found'), ('GRN_NOT_FOUND', 'GRN Not Found'), ('VENDOR_MISMATCH', 'Vendor Mismatch'), ('ITEM_MISMATCH', 'Item Mismatch'), ('QTY_MISMATCH', 'Quantity Mismatch'), ('PRICE_MISMATCH', 'Price Mismatch'), ('TAX_MISMATCH', 'Tax Mismatch'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('DUPLICATE_INVOICE', 'Duplicate Invoice'), ('EXTRACTION_LOW_CONFIDENCE', 'Extraction Low Confidence'), ('CURRENCY_MISMATCH', 'Currency Mismatch')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Structured context for agent consumption', null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='reconciliation.reconciliationresult')),
                ('result_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='reconciliation.reconciliationresultline')),
            ],
            options={
                'verbose_name': 'Reconciliation Exception',
                'verbose_name_plural': 'Reconciliation Exceptions',
                'db_table': 'reconciliation_exception',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('partial_count', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='reconciliation.reconciliationconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_runs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Run',
                'verbose_name_plural': 'Reconciliation Runs',
                'db_table': 'reconciliation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reconciliation.reconciliationrun'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresultline',
            index=models.Index(fields=['result'], name='idx_recon_rline_result'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresultline',
            index=models.Index(fields=['match_status'], name='idx_recon_rline_status'),
        ),
        migrations.AddIndex(
            model_name='reconciliationexception',
            index=models.Index(fields=['exception_type'], name='idx_recon_exc_type'),
        ),
        migrations.AddIndex(
            model_name='reconciliationexception',
            index=models.Index(fields=['severity'], name='idx_recon_exc_sev'),
        ),
        migrations.AddIndex(
            model_name='reconciliationexception',
            index=models.Index(fields=['resolved'], name='idx_recon_exc_resolved'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['status'], name='idx_recon_run_status'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['match_status'], name='idx_recon_result_status'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['requires_review'], name='idx_recon_result_review'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['run', 'invoice'], name='idx_recon_result_run_inv'),
        ),
    ]
