# Generated by Django 5.2.1 on 2026-03-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationconfig',
            name='auto_close_amount_tolerance_pct',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='auto_close_price_tolerance_pct',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='auto_close_qty_tolerance_pct',
            field=models.FloatField(default=5.0),
        ),
    ]
