# Generated by Django 5.2.1 on 2026-03-11 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_reconciliation_mode_support'),
        ('reconciliation', '0002_add_auto_close_tolerance_fields'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('policy_name', models.CharField(max_length=200)),
                ('reconciliation_mode', models.CharField(choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)')], max_length=20)),
                ('invoice_type', models.CharField(blank=True, default='', max_length=100)),
                ('item_category', models.CharField(blank=True, default='', max_length=100)),
                ('business_unit', models.CharField(blank=True, default='', max_length=100)),
                ('location_code', models.CharField(blank=True, default='', max_length=100)),
                ('is_service_invoice', models.BooleanField(blank=True, null=True)),
                ('is_stock_invoice', models.BooleanField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='Lower number = higher precedence')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Reconciliation Policy',
                'verbose_name_plural': 'Reconciliation Policies',
                'db_table': 'reconciliation_policy',
                'ordering': ['priority', 'policy_code'],
            },
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='default_reconciliation_mode',
            field=models.CharField(choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)')], db_index=True, default='THREE_WAY', max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='enable_grn_for_stock_items',
            field=models.BooleanField(default=True, help_text='Require GRN for stock/inventory items'),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='enable_mode_resolver',
            field=models.BooleanField(default=True, help_text='Use policy rules to auto-resolve 2-way vs 3-way per invoice'),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='enable_two_way_for_services',
            field=models.BooleanField(default=True, help_text='Auto-select 2-way mode for service invoices'),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='applies_to_mode',
            field=models.CharField(choices=[('TWO_WAY', '2-Way Only'), ('THREE_WAY', '3-Way Only'), ('BOTH', 'Both Modes')], db_index=True, default='BOTH', help_text='Which reconciliation mode(s) this exception is relevant for', max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='grn_checked_flag',
            field=models.BooleanField(blank=True, help_text='Whether GRN matching was actually executed', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='grn_required_flag',
            field=models.BooleanField(blank=True, help_text='Whether GRN verification was required for this invoice', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='is_three_way_result',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='is_two_way_result',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='mode_resolution_reason',
            field=models.TextField(blank=True, default='', help_text='Explanation of why this mode was selected'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='policy_applied',
            field=models.CharField(blank=True, default='', help_text='Policy code that determined the reconciliation mode', max_length=200),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='reconciliation_mode',
            field=models.CharField(blank=True, choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='grn_checked_flag',
            field=models.BooleanField(blank=True, help_text='Whether GRN matching was actually performed', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='grn_required_flag',
            field=models.BooleanField(blank=True, help_text='Whether GRN was required for this run', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='policy_name_applied',
            field=models.CharField(blank=True, default='', help_text='Policy code that determined the mode (if uniform)', max_length=200),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='reconciliation_mode',
            field=models.CharField(blank=True, choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)')], db_index=True, default='', help_text='Dominant mode used across invoices in this run', max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationexception',
            name='exception_type',
            field=models.CharField(choices=[('PO_NOT_FOUND', 'PO Not Found'), ('VENDOR_MISMATCH', 'Vendor Mismatch'), ('ITEM_MISMATCH', 'Item Mismatch'), ('QTY_MISMATCH', 'Quantity Mismatch'), ('PRICE_MISMATCH', 'Price Mismatch'), ('TAX_MISMATCH', 'Tax Mismatch'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('DUPLICATE_INVOICE', 'Duplicate Invoice'), ('EXTRACTION_LOW_CONFIDENCE', 'Extraction Low Confidence'), ('CURRENCY_MISMATCH', 'Currency Mismatch'), ('LOCATION_MISMATCH', 'Location Mismatch'), ('GRN_NOT_FOUND', 'GRN Not Found'), ('RECEIPT_SHORTAGE', 'Receipt Shortage'), ('INVOICE_QTY_EXCEEDS_RECEIVED', 'Invoice Qty Exceeds Received Qty'), ('OVER_RECEIPT', 'Over Receipt'), ('MULTI_GRN_PARTIAL_RECEIPT', 'Multi-GRN Partial Receipt'), ('RECEIPT_LOCATION_MISMATCH', 'Receipt Location Mismatch'), ('DELAYED_RECEIPT', 'Delayed Receipt')], db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['reconciliation_mode'], name='idx_recon_result_mode'),
        ),
        migrations.AddField(
            model_name='reconciliationpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationpolicy',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_policies', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='reconciliationpolicy',
            index=models.Index(fields=['priority'], name='idx_recon_pol_priority'),
        ),
        migrations.AddIndex(
            model_name='reconciliationpolicy',
            index=models.Index(fields=['reconciliation_mode'], name='idx_recon_pol_mode'),
        ),
    ]
