# Generated by Django 5.2.1 on 2026-03-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_add_reconciliation_mode_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationconfig',
            name='ap_processor_sees_all_cases',
            field=models.BooleanField(default=False, help_text='When False, AP Processors only see cases for documents they uploaded'),
        ),
    ]
