# Generated by Django 5.0.14 on 2026-03-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_add_ap_processor_sees_all_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationresult',
            name='data_is_stale',
            field=models.BooleanField(default=False, help_text='True if any ERP source data exceeded the configured freshness threshold'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='erp_source_metadata_json',
            field=models.JSONField(blank=True, default=dict, help_text='Full ERP resolution provenance for PO and GRN sources (to_provenance_dict output)'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='grn_erp_source_type',
            field=models.CharField(blank=True, default='', help_text='ERPSourceType value for the GRN data used in this match', max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='po_erp_source_type',
            field=models.CharField(blank=True, default='', help_text='ERPSourceType value for the PO data used in this match', max_length=20),
        ),
    ]
