# Generated by Django 5.0.14 on 2026-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0005_erp_source_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationrun',
            name='langfuse_trace_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langfuse root trace ID for this reconciliation run', max_length=64),
        ),
    ]
