# Generated by Django 5.0.14 on 2026-04-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0006_add_langfuse_trace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='default_reconciliation_mode',
            field=models.CharField(choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)'), ('NON_PO', 'Non-PO (No PO matching)')], db_index=True, default='THREE_WAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationpolicy',
            name='reconciliation_mode',
            field=models.CharField(choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)'), ('NON_PO', 'Non-PO (No PO matching)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationresult',
            name='reconciliation_mode',
            field=models.CharField(blank=True, choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)'), ('NON_PO', 'Non-PO (No PO matching)')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='reconciliation_mode',
            field=models.CharField(blank=True, choices=[('TWO_WAY', '2-Way (Invoice vs PO)'), ('THREE_WAY', '3-Way (Invoice vs PO vs GRN)'), ('NON_PO', 'Non-PO (No PO matching)')], db_index=True, default='', help_text='Dominant mode used across invoices in this run', max_length=20),
        ),
    ]
