# Generated by Django 5.0.14 on 2026-04-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0008_alter_reconciliationexception_exception_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationexception',
            name='exception_type',
            field=models.CharField(choices=[('PO_NOT_FOUND', 'PO Not Found'), ('VENDOR_MISMATCH', 'Vendor Mismatch'), ('ITEM_MISMATCH', 'Item Mismatch'), ('QTY_MISMATCH', 'Quantity Mismatch'), ('PRICE_MISMATCH', 'Price Mismatch'), ('TAX_MISMATCH', 'Tax Mismatch'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('DUPLICATE_INVOICE', 'Duplicate Invoice'), ('EXTRACTION_LOW_CONFIDENCE', 'Extraction Low Confidence'), ('MISSING_MANDATORY_FIELDS', 'Missing Mandatory Fields'), ('CURRENCY_MISMATCH', 'Currency Mismatch'), ('LOCATION_MISMATCH', 'Location Mismatch'), ('GSTIN_MISMATCH', 'GSTIN / Tax ID Mismatch'), ('SUPPLY_TYPE_MISMATCH', 'Supply Type Mismatch (Intra/Inter)'), ('TAX_RATE_MISMATCH', 'Tax Rate Mismatch'), ('COUNTRY_MISMATCH', 'Country Mismatch'), ('GRN_NOT_FOUND', 'GRN Not Found'), ('RECEIPT_SHORTAGE', 'Receipt Shortage'), ('INVOICE_QTY_EXCEEDS_RECEIVED', 'Invoice Qty Exceeds Received Qty'), ('OVER_RECEIPT', 'Over Receipt'), ('MULTI_GRN_PARTIAL_RECEIPT', 'Multi-GRN Partial Receipt'), ('RECEIPT_LOCATION_MISMATCH', 'Receipt Location Mismatch'), ('DELAYED_RECEIPT', 'Delayed Receipt')], db_index=True, max_length=40),
        ),
    ]
