# Generated by Django 5.0.14 on 2026-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0010_add_vendor_not_verified_exception_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationconfig',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationpolicy',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
    ]
