# Generated by Django 5.0.14 on 2026-04-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
        ('reconciliation', '0011_reconciliationconfig_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationconfig',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='reconciliationexception',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='reconciliationpolicy',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='reconciliationresult',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='reconciliationresultline',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='reconciliationrun',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='reconciliationpolicy',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
