# Generated by Django 5.0.14 on 2026-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0013_add_partial_invoice_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationresultline',
            name='amount_match_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='candidate_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='confidence_band',
            field=models.CharField(blank=True, default='', help_text='HIGH / GOOD / MODERATE / LOW / NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='description_match_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='fuzzy_similarity_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='is_ambiguous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='line_match_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed scorer metadata: top_gap, second_best_score, etc.'),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='match_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Composite score 0.0000..1.0000 from deterministic scorer', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='match_method',
            field=models.CharField(blank=True, default='', help_text='EXACT / DETERMINISTIC / LLM_FALLBACK / NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='matched_signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='price_match_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='quantity_match_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='rejected_signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='token_similarity_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='partial_invoice_threshold_pct',
            field=models.FloatField(default=95.0, help_text='When an invoice total is below this percentage of the PO total and no prior invoices exist, treat it as a partial/milestone invoice.'),
        ),
        migrations.AlterField(
            model_name='reconciliationexception',
            name='exception_type',
            field=models.CharField(choices=[('PO_NOT_FOUND', 'PO Not Found'), ('VENDOR_MISMATCH', 'Vendor Mismatch'), ('ITEM_MISMATCH', 'Item Mismatch'), ('QTY_MISMATCH', 'Quantity Mismatch'), ('PRICE_MISMATCH', 'Price Mismatch'), ('TAX_MISMATCH', 'Tax Mismatch'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('DUPLICATE_INVOICE', 'Duplicate Invoice'), ('EXTRACTION_LOW_CONFIDENCE', 'Extraction Low Confidence'), ('MISSING_MANDATORY_FIELDS', 'Missing Mandatory Fields'), ('CURRENCY_MISMATCH', 'Currency Mismatch'), ('LOCATION_MISMATCH', 'Location Mismatch'), ('GSTIN_MISMATCH', 'GSTIN / Tax ID Mismatch'), ('SUPPLY_TYPE_MISMATCH', 'Supply Type Mismatch (Intra/Inter)'), ('TAX_RATE_MISMATCH', 'Tax Rate Mismatch'), ('COUNTRY_MISMATCH', 'Country Mismatch'), ('PARTIAL_INVOICE', 'Partial Invoice'), ('VENDOR_NOT_VERIFIED', 'Vendor Not Verified'), ('GRN_NOT_FOUND', 'GRN Not Found'), ('RECEIPT_SHORTAGE', 'Receipt Shortage'), ('INVOICE_QTY_EXCEEDS_RECEIVED', 'Invoice Qty Exceeds Received Qty'), ('OVER_RECEIPT', 'Over Receipt'), ('MULTI_GRN_PARTIAL_RECEIPT', 'Multi-GRN Partial Receipt'), ('RECEIPT_LOCATION_MISMATCH', 'Receipt Location Mismatch'), ('DELAYED_RECEIPT', 'Delayed Receipt'), ('NO_CONFIDENT_PO_LINE_MATCH', 'No Confident PO Line Match'), ('MULTIPLE_PO_LINE_CANDIDATES', 'Multiple PO Line Candidates'), ('LINE_DESCRIPTION_AMBIGUOUS', 'Line Description Ambiguous'), ('LINE_MATCH_LOW_CONFIDENCE', 'Line Match Low Confidence')], db_index=True, max_length=40),
        ),
    ]
