# Generated by Django 5.0.14 on 2026-04-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0014_line_match_v2_scorer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationresultline',
            name='available_qty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='cumulative_received_qty - previously_consumed_qty (available for this invoice)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='contributing_grn_line_ids',
            field=models.JSONField(blank=True, default=list, help_text='GRN line item PKs that contribute to cumulative_received_qty'),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='cumulative_received_qty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Total GRN-received qty for the matched PO line (across all GRNs)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='invoiced_exceeds_available',
            field=models.BooleanField(default=False, help_text='True when qty_invoice > available_qty (overbilling against available receipt)'),
        ),
        migrations.AddField(
            model_name='reconciliationresultline',
            name='previously_consumed_qty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sum of qty_invoice from prior reconciliation result lines paired to the same PO line', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationexception',
            name='exception_type',
            field=models.CharField(choices=[('PO_NOT_FOUND', 'PO Not Found'), ('VENDOR_MISMATCH', 'Vendor Mismatch'), ('ITEM_MISMATCH', 'Item Mismatch'), ('QTY_MISMATCH', 'Quantity Mismatch'), ('PRICE_MISMATCH', 'Price Mismatch'), ('TAX_MISMATCH', 'Tax Mismatch'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('DUPLICATE_INVOICE', 'Duplicate Invoice'), ('EXTRACTION_LOW_CONFIDENCE', 'Extraction Low Confidence'), ('MISSING_MANDATORY_FIELDS', 'Missing Mandatory Fields'), ('CURRENCY_MISMATCH', 'Currency Mismatch'), ('LOCATION_MISMATCH', 'Location Mismatch'), ('GSTIN_MISMATCH', 'GSTIN / Tax ID Mismatch'), ('SUPPLY_TYPE_MISMATCH', 'Supply Type Mismatch (Intra/Inter)'), ('TAX_RATE_MISMATCH', 'Tax Rate Mismatch'), ('COUNTRY_MISMATCH', 'Country Mismatch'), ('PARTIAL_INVOICE', 'Partial Invoice'), ('VENDOR_NOT_VERIFIED', 'Vendor Not Verified'), ('GRN_NOT_FOUND', 'GRN Not Found'), ('RECEIPT_SHORTAGE', 'Receipt Shortage'), ('INVOICE_QTY_EXCEEDS_RECEIVED', 'Invoice Qty Exceeds Received Qty'), ('OVER_RECEIPT', 'Over Receipt'), ('MULTI_GRN_PARTIAL_RECEIPT', 'Multi-GRN Partial Receipt'), ('RECEIPT_LOCATION_MISMATCH', 'Receipt Location Mismatch'), ('DELAYED_RECEIPT', 'Delayed Receipt'), ('INVOICE_QTY_EXCEEDS_AVAILABLE', 'Invoice Qty Exceeds Available Receipt'), ('NO_CONFIDENT_PO_LINE_MATCH', 'No Confident PO Line Match'), ('MULTIPLE_PO_LINE_CANDIDATES', 'Multiple PO Line Candidates'), ('LINE_DESCRIPTION_AMBIGUOUS', 'Line Description Ambiguous'), ('LINE_MATCH_LOW_CONFIDENCE', 'Line Match Low Confidence')], db_index=True, max_length=40),
        ),
    ]
