# Generated by Django 5.0.14 on 2026-04-09 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('documents', '0013_add_compound_tenant_status_indexes'),
        ('reconciliation', '0015_receipt_availability_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['tenant', 'match_status'], name='idx_recon_result_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['tenant', 'status'], name='idx_recon_run_tenant_status'),
        ),
    ]
