# Generated by Django 5.0.14 on 2026-04-17 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('reconciliation', '0016_add_compound_tenant_status_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='reconciliationconfig',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='uq_reconconfig_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('name',), name='uq_reconconfig_name_global'),
        ),
    ]
