# Generated by Django 5.0.14 on 2026-04-17 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('reconciliation', '0017_alter_config_name_unique_per_tenant'),
        ('vendors', '0005_tenant_scope_po_grn_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationpolicy',
            name='policy_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='reconciliationpolicy',
            constraint=models.UniqueConstraint(fields=('policy_code', 'tenant'), name='uq_recon_policy_code_tenant'),
        ),
    ]
