# Generated by Django 5.0.14 on 2026-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0019_remove_global_partial_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='enable_mode_resolver',
            field=models.BooleanField(default=False, help_text='Use policy rules to auto-resolve 2-way vs 3-way per invoice'),
        ),
    ]
