# Generated by Django 5.2.1 on 2026-03-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(help_text='Unique vendor code from ERP', max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=100)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors_vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_name', models.CharField(db_index=True, max_length=255)),
                ('normalized_alias', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source', models.CharField(blank=True, default='manual', help_text='Origin of alias: manual, extraction, erp', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Alias',
                'verbose_name_plural': 'Vendor Aliases',
                'db_table': 'vendors_vendor_alias',
                'ordering': ['alias_name'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['code'], name='idx_vendor_code'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['normalized_name'], name='idx_vendor_norm_name'),
        ),
        migrations.AddIndex(
            model_name='vendoralias',
            index=models.Index(fields=['normalized_alias'], name='idx_valias_norm'),
        ),
        migrations.AlterUniqueTogether(
            name='vendoralias',
            unique_together={('vendor', 'normalized_alias')},
        ),
    ]
