# Generated by Django 5.0.14 on 2026-03-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorAlias',
        ),
    ]
