# Generated by Django 5.0.14 on 2026-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_add_vendor_fk_to_alias_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
    ]
