# Generated by Django 5.0.14 on 2026-04-17 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_platform_admin'),
        ('vendors', '0004_add_tenant_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(db_index=True, help_text='Vendor code from ERP', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('code', 'tenant'), name='uq_vendor_code_tenant'),
        ),
    ]
