"""Application-wide constants."""

# Tolerance defaults (percent)
DEFAULT_QTY_TOLERANCE_PCT = 2.0
DEFAULT_PRICE_TOLERANCE_PCT = 1.0
DEFAULT_AMOUNT_TOLERANCE_PCT = 1.0

# Auto-close tolerance (wider band — discrepancies within this skip AI agents)
AUTO_CLOSE_QTY_TOLERANCE_PCT = 5.0
AUTO_CLOSE_PRICE_TOLERANCE_PCT = 3.0
AUTO_CLOSE_AMOUNT_TOLERANCE_PCT = 3.0

# Extraction
EXTRACTION_CONFIDENCE_THRESHOLD = 0.75
MAX_UPLOAD_SIZE_MB = 25
ALLOWED_UPLOAD_EXTENSIONS = [".pdf", ".png", ".jpg", ".jpeg", ".tiff", ".tif"]

# Reconciliation
MAX_LINE_MATCH_CANDIDATES = 10
FUZZY_MATCH_THRESHOLD = 80  # fuzzywuzzy score
DEFAULT_RECONCILIATION_MODE = "THREE_WAY"

# Exception types valid in TWO_WAY mode (no receipt/GRN exceptions)
TWO_WAY_EXCEPTION_TYPES = {
    "PO_NOT_FOUND", "VENDOR_MISMATCH", "ITEM_MISMATCH", "QTY_MISMATCH",
    "PRICE_MISMATCH", "TAX_MISMATCH", "AMOUNT_MISMATCH", "DUPLICATE_INVOICE",
    "EXTRACTION_LOW_CONFIDENCE", "CURRENCY_MISMATCH", "LOCATION_MISMATCH",
}

# Additional exception types valid only in THREE_WAY mode
THREE_WAY_ONLY_EXCEPTION_TYPES = {
    "GRN_NOT_FOUND", "RECEIPT_SHORTAGE", "INVOICE_QTY_EXCEEDS_RECEIVED",
    "OVER_RECEIPT", "MULTI_GRN_PARTIAL_RECEIPT", "RECEIPT_LOCATION_MISMATCH",
    "DELAYED_RECEIPT",
}

# Agent
AGENT_MAX_RETRIES = 2
AGENT_TIMEOUT_SECONDS = 120
AGENT_CONFIDENCE_THRESHOLD = 0.70

# Review
REVIEW_AUTO_CLOSE_THRESHOLD = 0.95

# Pagination
DEFAULT_PAGE_SIZE = 25
MAX_PAGE_SIZE = 200

# Date formats
STANDARD_DATE_FORMAT = "%Y-%m-%d"
DISPLAY_DATE_FORMAT = "%d %b %Y"

# Currency
DEFAULT_CURRENCY = "USD"
