# Generated by Django 5.2.1 on 2026-03-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('format', models.CharField(default='csv', help_text='csv or xlsx', max_length=10)),
                ('parameters', models.JSONField(blank=True, help_text='Filters / params used to generate', null=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'db_table': 'reports_generated',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type'], name='idx_report_type')],
            },
        ),
    ]
