# Generated by Django 5.0.14 on 2026-04-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_tenant_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedReport',
        ),
    ]
