# Generated by Django 5.2.1 on 2026-03-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingrun',
            name='erp_source_metadata_json',
            field=models.JSONField(blank=True, default=dict, help_text='ERP resolution source metadata (connector, fallback, confidence per field)'),
        ),
    ]
