# Generated by Django 5.0.14 on 2026-03-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_core', '0002_postingrun_erp_source_metadata_json'),
        ('vendors', '0002_add_vendor_fk_to_alias_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraliasmapping',
            name='source',
            field=models.CharField(blank=True, default='manual', help_text='Origin: manual, extraction, erp', max_length=50),
        ),
        migrations.AddField(
            model_name='vendoraliasmapping',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Resolved Vendor record (used by extraction and reconciliation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_mappings', to='vendors.vendor'),
        ),
    ]
