# Generated by Django 5.0.14 on 2026-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_core', '0003_add_vendor_fk_to_alias_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingrun',
            name='langfuse_trace_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langfuse root trace ID for this posting run', max_length=64),
        ),
    ]
