# Generated by Django 5.0.14 on 2026-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_core', '0004_add_langfuse_trace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingrun',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
    ]
