# Generated by Django 5.0.14 on 2026-04-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_fields_and_invitation'),
        ('posting_core', '0005_postingrun_tenant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postingrun',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='postingrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile'),
        ),
    ]
