# Generated by Django 5.0.14 on 2026-04-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_system_export_field_mapping_permission'),
        ('posting_core', '0007_erpcostcenterreference_tenant_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='erpcostcenterreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'cost_center_code'), name='uq_erp_cc_ref_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='erpitemreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'item_code'), name='uq_erp_item_ref_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='erpporeference',
            constraint=models.UniqueConstraint(fields=('tenant', 'po_number', 'po_line_number'), name='uq_erp_po_ref_tenant_po_line'),
        ),
        migrations.AddConstraint(
            model_name='erptaxcodereference',
            constraint=models.UniqueConstraint(fields=('tenant', 'tax_code'), name='uq_erp_tax_ref_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='erpvendorreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'vendor_code'), name='uq_erp_vendor_ref_tenant_code'),
        ),
    ]
