# Generated by Django 5.0.14 on 2026-04-27 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_system_export_field_mapping_permission'),
        ('posting_core', '0008_upsert_erp_reference_unique_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpreferenceimportbatch',
            name='batch_type',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('ITEM', 'Item'), ('TAX', 'Tax'), ('COST_CENTER', 'Cost Center'), ('OPEN_PO', 'Open PO'), ('GRN', 'GRN')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ERPGRNReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grn_number', models.CharField(db_index=True, max_length=100)),
                ('po_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('po_voucher_no', models.CharField(blank=True, default='', max_length=50)),
                ('po_line_number', models.CharField(blank=True, default='', max_length=20)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=50)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('item_description', models.TextField(blank=True, default='')),
                ('order_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('grn_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('grn_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('grn_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_refs', to='posting_core.erpreferenceimportbatch')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'ERP GRN Reference',
                'verbose_name_plural': 'ERP GRN References',
                'db_table': 'posting_core_erp_grn_ref',
                'ordering': ['grn_number', 'po_line_number'],
                'indexes': [models.Index(fields=['grn_number'], name='idx_grnref_number'), models.Index(fields=['po_number'], name='idx_grnref_po_number')],
            },
        ),
        migrations.AddConstraint(
            model_name='erpgrnreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'grn_number', 'po_voucher_no', 'po_line_number'), name='uq_erp_grn_ref_tenant_grn_line'),
        ),
    ]
