# Generated by Django 5.2.1 on 2026-03-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REPROCESSED', 'Reprocessed')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='1=highest, 10=lowest')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reconciliation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='reconciliation.reconciliationresult')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Assignment',
                'verbose_name_plural': 'Review Assignments',
                'db_table': 'reviews_assignment',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_INFO', 'Request Info'), ('REPROCESS', 'Reprocess'), ('ESCALATE', 'Escalate'), ('CORRECT_FIELD', 'Correct Field'), ('ADD_COMMENT', 'Add Comment')], db_index=True, max_length=30)),
                ('field_name', models.CharField(blank=True, default='', help_text='Field corrected, if applicable', max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reviews.reviewassignment')),
            ],
            options={
                'verbose_name': 'Manual Review Action',
                'verbose_name_plural': 'Manual Review Actions',
                'db_table': 'reviews_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal vs. visible to vendor')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.reviewassignment')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Comment',
                'verbose_name_plural': 'Review Comments',
                'db_table': 'reviews_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REPROCESSED', 'Reprocessed')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='reviews.reviewassignment')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Decision',
                'verbose_name_plural': 'Review Decisions',
                'db_table': 'reviews_decision',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['status'], name='idx_revassign_status'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['assigned_to'], name='idx_revassign_user'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['priority'], name='idx_revassign_priority'),
        ),
        migrations.AddIndex(
            model_name='manualreviewaction',
            index=models.Index(fields=['action_type'], name='idx_revaction_type'),
        ),
    ]
