# Generated by Django 5.2.1 on 2026-03-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer_agreed_with_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer_recommendation',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer_risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer_suggested_actions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
