# Generated by Django 5.0.14 on 2026-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_add_reviewer_summary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreviewaction',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
    ]
