# Generated by Django 5.0.14 on 2026-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_integration', '0002_email_rbac_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaction',
            name='action_type',
            field=models.CharField(choices=[('CREATE_DOCUMENT_UPLOAD', 'Create Document Upload'), ('CREATE_AP_CASE', 'Create AP Case'), ('LINK_TO_AP_CASE', 'Link to AP Case'), ('LINK_TO_PROCUREMENT_REQUEST', 'Link to Procurement Request'), ('LINK_TO_SUPPLIER_QUOTATION', 'Link to Supplier Quotation'), ('CREATE_SUPPLIER_QUOTATION', 'Create Supplier Quotation'), ('TRIGGER_EXTRACTION', 'Trigger Extraction'), ('TRIGGER_QUOTATION_PREFILL', 'Trigger Quotation Prefill'), ('TRIGGER_RECONCILIATION', 'Trigger Reconciliation'), ('TRIGGER_PROCUREMENT_ANALYSIS', 'Trigger Procurement Analysis'), ('SEND_OUTBOUND_EMAIL', 'Send Outbound Email'), ('SEND_CLARIFICATION_EMAIL', 'Send Clarification Email'), ('SYNC_MAILBOX', 'Sync Mailbox'), ('TEST_MAILBOX_CONNECTION', 'Test Mailbox Connection'), ('RELINK_THREAD', 'Relink Thread'), ('QUEUE_FOR_TRIAGE', 'Queue For Triage'), ('REOPEN_ENTITY', 'Reopen Entity'), ('IGNORE_EMAIL', 'Ignore Email')], db_index=True, max_length=40),
        ),
    ]
